### ISSUE TITLE
[x-peer] Can't observe remote peer, but remote peer can observe me.

### ISSUE THREAD

**Issue by NickolaiVarin** [subutai-io/base#1000]
For replay this bug you need:

Test case
1) Create an environment on two peers which are not within local LAN

Result: Can't observe remote peer, but remote peer can observe me.
![pasted image at 2016_06_07 02_09 pm](https://cloud.githubusercontent.com/assets/16968797/15851028/869575b4-2cb4-11e6-8dd9-a7333ed3b42b.png)
![cansee](https://cloud.githubusercontent.com/assets/16968797/15851166/153d3d42-2cb5-11e6-8a80-023ff48a2118.jpg)

**Comment by Commander223** [comment]
![image](https://cloud.githubusercontent.com/assets/1281861/15858200/2877c3c4-2ce1-11e6-84d7-dd38423bc17e.png)

**Comment by Commander223** [comment]
![image](https://cloud.githubusercontent.com/assets/1281861/15858218/424698ca-2ce1-11e6-9dbf-a51eef37b899.png)

**Comment by Commander223** [comment]
[karaflogs2016-06-07 19-00-05.txt](https://github.com/subutai-io/base/files/302604/karaflogs2016-06-07.19-00-05.txt)

**Comment by larenso** [comment]
Tested with Manas, bug confirmed, but after @Commander223 upgraded to the latest commit 6c8cc90336ba91b3c9af9fa84ba886ace97a3e23, this error dissolved

**Comment by Dilshat** [comment]
done
