### ISSUE TITLE
[acceptance-testing] [cross-peer] cross-peers ping not working

### ISSUE THREAD

**Issue by p1gmale0n** [subutai-io/base#1003]
cannot ping cross-peer containers:
created cross-peer env. from containers on peer1 cannot ping containers on peer2,
in the reverse direction - same

![2016-06-07_15-41-26](https://cloud.githubusercontent.com/assets/1177402/15853323/5150daf8-2cc6-11e6-84af-057ad98874d4.png)
[peer2.p2p.txt](https://github.com/subutai-io/base/files/302265/peer2.p2p.txt)
[peer1.p2p.txt](https://github.com/subutai-io/base/files/302266/peer1.p2p.txt)

**Comment by p1gmale0n** [comment]
same issue on other 2 peers:
![2016-06-08_13-52-50](https://cloud.githubusercontent.com/assets/1177402/15886701/4e95bd32-2d80-11e6-842d-4415af4b7e50.png)
[peer2.p2p.txt](https://github.com/subutai-io/base/files/304262/peer2.p2p.txt)
[peer1.p2p.txt](https://github.com/subutai-io/base/files/304263/peer1.p2p.txt)

**Comment by p1gmale0n** [comment]
![2016-06-09_14-09-54](https://cloud.githubusercontent.com/assets/1177402/15922882/e9180db2-2e4b-11e6-8a01-6289faa16cbf.png)

[p2p.peer1.txt](https://github.com/subutai-io/base/files/306402/p2p.peer1.txt)
[p2p.peer2.txt](https://github.com/subutai-io/base/files/306403/p2p.peer2.txt)

**Comment by crioto** [comment]
Updating control peer logic. This configuration needs to be tested again. No need to update client side

**Comment by asanaliev** [comment]
Duplicates #364: Containers on remote peer are not accessible

**Comment by crioto** [comment]
Updated control peer services. Testing is required

**Comment by p1gmale0n** [comment]
created x-peer env - after creating x-peer pings working
rebooted peer1 - after reboot pings working
rebooted peer2 - after reboot pings working
rebooted peer1 and peer2 - after reboot pings working

**Comment by crioto** [comment]
@p1gmale0n Thank you. Please close the issue if it's fixed
