### ISSUE TITLE
[acceptance-testing] [ui] "Public key" window does not disappear

### ISSUE THREAD

**Issue by p1gmale0n** [subutai-io/base#1004]
create 2 keys on Subutai E2E plugin
login into SS - select key for use
go User Identity - Account Settings
get "Public key" window

"Public key" window does not have control elements (for close/hide)
and does not disappear when navigating

![2016-06-07_16-37-09](https://cloud.githubusercontent.com/assets/1177402/15855280/6c2f021e-2cd0-11e6-9a79-ef9337062559.png)
![2016-06-07_16-42-02](https://cloud.githubusercontent.com/assets/1177402/15855285/6f8d1ca2-2cd0-11e6-90d5-a45b2e4bb291.png)

**Comment by Dilshat** [comment]
Fixed
