### ISSUE TITLE
cannot login into SS

### ISSUE THREAD

**Issue by p1gmale0n** [subutai-io/base#1005]
reinstsalled management (destroy/import)
logged in, created cross-peer..
after some time trying login, get
> Wrong Auth Credentials

after some time - logged in successfully

![2016-06-07_16-58-16](https://cloud.githubusercontent.com/assets/1177402/15855388/0bac87bc-2cd1-11e6-8a73-47efb7b479fa.png)
[karaflogs2016-06-07 16-58-38.txt](https://github.com/subutai-io/base/files/302382/karaflogs2016-06-07.16-58-38.txt)

**Comment by Dilshat** [comment]
This error is probably due to cookie left on client side whereas session on server side is expired.
To solve it each login request should clear the ​**sptoken**​ cookie before sending the credentials to server @larenso @Commander223

**Comment by larenso** [comment]
less likely, login is implemented outside of cxf implementation, so interceptors has no effect on login and 'sptoken' checks, 

UPDATE: tested with wrong sptoken, login was successful

I reproduced this problem with the following steps:
1) Turned on PC, turned on a vm 'subutai-[number]'
2) Via tray, launched SS Console
3) Tried to login, once ui responded
currently cannot reproduce it

**Comment by Dilshat** [comment]
Seems this happens after restart or fresh installation of VM. This is related to slow db initialization

**Comment by Dilshat** [comment]
Does not reproduce
