### ISSUE TITLE
Add minimal number of nodes when plugin tool is used

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/base#1009]
When a plugin is installed in Bazaar , user can use it in Environment Builder.
But only one node is placed automatically whereas some templates require say minimum 3 nodes.
We need to fix this.
@larenso @eabyshev please work together on this

**Comment by larenso** [comment]
![image](https://cloud.githubusercontent.com/assets/4501130/15940423/d715f852-2e9d-11e6-8bd8-425c7420ac6b.png)
usergrid already have configuration of minimum 3 different containers, need to go though list of plugins and configure it there

**Comment by eabyshev** [comment]
@larenso here page with recommended nodes for plugins, please check it. https://confluence.critical-factor.com/display/~eabyshev/Plugins+configuration

**Comment by eabyshev** [comment]
done
