### ISSUE TITLE
Move nodes items dont work 

### ISSUE THREAD

**Issue by akylbekesenaliev** [subutai-io/base#1013]
![screenshot_20160608165543](https://cloud.githubusercontent.com/assets/17665678/15892159/dd6c91a2-2d80-11e6-8d21-ae37539b36e6.png)
When trying to move nodes the moving Items are not working ..

**Comment by Dilshat** [comment]
yes you have to click the item to move it

**Comment by akylbekesenaliev** [comment]
@Dilshat then those items are in no use, maybe its better to delete them..

**Comment by Dilshat** [comment]
actully this is a ui bug, they should work to move all items back and forth

**Comment by akylbekesenaliev** [comment]
@Dilshat ok let me then re-assign this ticket

**Comment by Commander223** [comment]
fixed in plugins repo 5a58aeceb580b2e545e30aaee66d5586719fd649
