### ISSUE TITLE
Add method to get peer registration status

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/base#1021]
Currently we have only isOnline check for a remote peer.
But there is a case when a remote peer deletes registration on its side with Force option, that can delete it only on one side. We need to have something like peer.getRegistrationState that returns enum
[CANCELED, OK, OFFLINE]

**Comment by Dilshat** [comment]
Seems in both cases when remote peer is offline or it deleted peer registration from its side only, the resulting error is javax.ws.rs.ProcessingException: Response timeout
so we can not reliably check this via 8444 port.
We need to either use 8443 port or give up on this method if this introduces some security breach.

**Comment by tjamakeev** [comment]
implemented new method
