### ISSUE TITLE
Peer obtains new ID after restarting VM - MAC OS(Net Installer)

### ISSUE THREAD

**Issue by Ernisto** [subutai-io/base#1025]
![image](https://cloud.githubusercontent.com/assets/13309012/15937116/7e33139a-2e8f-11e6-8964-ebacf2c27bd4.png)

**Comment by Dilshat** [comment]
There is no confirmation of the ID change in the screen above.
Please take screenshot before restart and after and attach karaf.logs
@Ernisto

**Comment by Dilshat** [comment]
Please attach karaf log and About page

**Comment by Ernisto** [comment]
![image](https://cloud.githubusercontent.com/assets/13309012/15962164/0be7d072-2f2b-11e6-9758-aba634b5158f.png)

**Comment by Dilshat** [comment]
This is a very old peer

**Comment by Ernisto** [comment]
Net Installer from subutai.io

**Comment by Dilshat** [comment]
@p1gmale0n please see ^

**Comment by Ernisto** [comment]
[karaflogs2016-06-10 17-03-06.txt](https://github.com/subutai-io/base/files/308863/karaflogs2016-06-10.17-03-06.txt)

**Comment by Ernisto** [comment]
Also SS Console url changes from https://192.168.0.102:8443 to https://192.168.56.101:8443 while network is stable

**Comment by Ernisto** [comment]
![image](https://cloud.githubusercontent.com/assets/13309012/15963227/2166048a-2f32-11e6-943c-126ce36646fa.png)

Same for Windows Net Installer

**Comment by Ernisto** [comment]
Net Dev installer is ok. Net Installer has problems.
