### ISSUE TITLE
[UI] Set a download progress bar for the Update

### ISSUE THREAD

**Issue by akylbekesenaliev** [subutai-io/base#1026]
![update](https://cloud.githubusercontent.com/assets/17665678/15955273/dc0ad382-2ee8-11e6-8d2d-0d1c4750ebd2.png)
It is impossible right now to know and see what is going on while the Update is being initialized, to make this process more user friendly we have to set a download progress bar that shows that Update is being downloaded. The download progress bar does not have to display actual Updating processes since its really hard to implement but it has to show some kind of process just to make users calm and show users that some process is being worked on.
![approximate](https://cloud.githubusercontent.com/assets/17665678/15955415/b5e084b2-2ee9-11e6-819b-7e32c20d58cf.png)

**Comment by Dilshat** [comment]
This is not critical. We can close this for now

**Comment by akarasulu** [comment]
Let's leave these issues open @Dilshat - closing them makes us ignore them.

**Comment by akarasulu** [comment]
Actually thinking about this it would be nice. As a user sometimes I wait a long time sometimes less and I wonder what's happening.
