### ISSUE TITLE
Change text message after completion of Update 

### ISSUE THREAD

**Issue by akylbekesenaliev** [subutai-io/base#1027]
![after update](https://cloud.githubusercontent.com/assets/17665678/15955663/c1c91b70-2eeb-11e6-8ad8-a78d08ea169a.png)
After update is been processed it should:
1. The text in the picture should be changed to "Successfully updated Subutai"
or
2. after this message :
![window](https://cloud.githubusercontent.com/assets/17665678/15955704/0de57d3c-2eec-11e6-95e0-754841c1c4b5.png)
it should take me right back to the monitoring stats page.
Current result is :
After update is complete it keeps me on the same page with exactly the same text message which brings some kind of confusion.

**Comment by eabyshev** [comment]
fixed
