### ISSUE TITLE
Can't create Spark cluster 

### ISSUE THREAD

**Issue by akylbekesenaliev** [subutai-io/base#1034]
Cannot create Spark cluster:
![cant create spark cluster](https://cloud.githubusercontent.com/assets/17665678/15983337/f699b104-2fac-11e6-9df6-2da0f2827820.png)
About page:
![about](https://cloud.githubusercontent.com/assets/17665678/15983352/69435c1e-2fad-11e6-94cc-a7e8bf469ce6.png)
Karaflogs:
[karaflogs2016-06-11 11-21-04.txt](https://github.com/subutai-io/base/files/310109/karaflogs2016-06-11.11-21-04.txt)

**Comment by eabyshev** [comment]
@akylbekesenaliev can you attach logs please?

**Comment by akylbekesenaliev** [comment]
@eabyshev I have

**Comment by eabyshev** [comment]
sorry, not noticed my bad, also will be good paste about version of plugin too.

**Comment by eabyshev** [comment]
These error appear because for installation you choose node which contains in already created cluster, need to show proper output for that, will fix it.
