### ISSUE TITLE
The Error message should be more digestible 

### ISSUE THREAD

**Issue by akylbekesenaliev** [subutai-io/base#1035]
![cant create spark cluster](https://cloud.githubusercontent.com/assets/17665678/15983394/1f2b2920-2faf-11e6-9819-78dcb8871fa4.png)
The error message should be more informative , right now it brings this "Not working" feeling when everything is working well, this might confuse users.
Suggestion:
Remove all the brackets and etc and leave only the main message and that is "Node 99e2717c-cec7-4575-bd8e-fed566f92067 already belongs to Spark cluster AAA" and etc..."

**Comment by eabyshev** [comment]
fixed
