### ISSUE TITLE
Quick environment creation does not set required container size.  

### ISSUE THREAD

**Issue by soffokl** [subutai-io/base#1041]
Trying to create appscale using fast plugin configuration, but it add container with "SMALL" size by default instead of "HUGE". 
I guess, if we are using fast configuration it should set required container size too.
![anim](https://cloud.githubusercontent.com/assets/8612618/15996990/16ad2a8a-3150-11e6-9c4f-7f3f14d56828.gif)

**Comment by larenso** [comment]
fixed
