### ISSUE TITLE
Implement clone added template on Environment manager workspace.

### ISSUE THREAD

**Issue by eabyshev** [subutai-io/base#1045]
After conversation with @akylbekesenaliev I noticed that when you using **Plugin tool** there is appear only one container of appropriate template. And for adding another need to find in right panel. Will be easy to have some button to clone added template which we have on working environment space.

![screenshot from 2016-06-13 14 17 04](https://cloud.githubusercontent.com/assets/16954849/16001013/a046deb4-3171-11e6-9aca-d101fd63bc41.png)

![screenshot from 2016-06-13 14 17 13](https://cloud.githubusercontent.com/assets/16954849/16001014/a405ff3a-3171-11e6-9d81-3f817f6e05f7.png)

**Comment by Commander223** [comment]
added in commit a3feeeaa840518ed10769d5795568f1a41c7ab1b
