### ISSUE TITLE
[Environments] [database] Create/remove environments without waiting and you can observe that containers removed from other environments.

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/base#1046]
For replay this bug you need:

Test case
1) Go to SS and create a few environments.
2) Create/remove envi with elasticSearch templates without waiting while it fully removes (under_modification state).

Result: you can observe that containers removed from other environments.
[karaflogs2016-06-13 13-19-06.txt](https://github.com/subutai-io/base/files/311645/karaflogs2016-06-13.13-19-06.txt)
![pasted image at 2016_06_13 04_27 pm](https://cloud.githubusercontent.com/assets/11311924/16005131/6bdee160-3187-11e6-9da9-d6ec424b4ff5.png)
![pasted image at 2016_06_13 04_30 pm](https://cloud.githubusercontent.com/assets/11311924/16005141/76937bfc-3187-11e6-8348-54a18bd053f0.png)

**Comment by Dilshat** [comment]
Can not reproduce on peer that is not registered with Hub

**Comment by NikolaiB** [comment]
Can't reproduce on remote peer, without registered and with registered on Hub peer.

**Comment by Dilshat** [comment]
Seems we need to limit number of total containers per RH to avoid this situation

**Comment by Dilshat** [comment]
@NikolaiB please retest and close if fixed

**Comment by NikolaiB** [comment]
Fixed.
