### ISSUE TITLE
Timing while creating environments is wrong 

### ISSUE THREAD

**Issue by akylbekesenaliev** [subutai-io/base#1053]
![timing](https://cloud.githubusercontent.com/assets/17665678/16037506/815098d4-3229-11e6-8233-9930944c45e2.png)
When I create environments I see timing is getting incorrect, it starts with correct time but then a bit later it reduces.
About page:
![image](https://cloud.githubusercontent.com/assets/17665678/16037661/2b7c1428-322a-11e6-9050-bfbcfc369fd1.png)

**Comment by larenso** [comment]
need your pc, to overview error, could be incorrect server time

**Comment by akylbekesenaliev** [comment]
@larenso mm, I also thought so but then I checked everything ..

**Comment by Dilshat** [comment]
@akylbekesenaliev please retest and fix if closed

**Comment by akylbekesenaliev** [comment]
@Dilshat roger that

**Comment by larenso** [comment]
wrong timezone was set in OS, thus browser used invalid timezone +3GMT instead of +6GMT, which resulted in 3h offset, changing timezone to correct one fixed this

**Comment by samsonbek** [comment]
There is a difference between seconds in event time, some events are logged in ahead. I'm creating x-peer env. with appscale template on two peers, which are in local network. This is minor issue.
![image](https://cloud.githubusercontent.com/assets/4163679/16370012/2573ccf4-3c5e-11e6-9f2f-e071308516fd.png)

**Comment by Dilshat** [comment]
These timestamps are of background threads that log in parallel with the main thread
