### ISSUE TITLE
[Front-end] html tags in text of error.

### ISSUE THREAD

**Issue by NickolaiVarin** [subutai-io/base#1056]
![500error](https://cloud.githubusercontent.com/assets/16968797/16043115/94bd47b8-3257-11e6-9774-c18f748a00c8.png)
For replay this bug you need:

Test case
1) Go to SS.
2) Change password and login.
3) Logout
4) Change password on "root"
5) Try to login

Result: Observe error with html tags.

**Comment by larenso** [comment]
I suppose this caused that some services hasn't started, need to check status code

**Comment by larenso** [comment]
Seems smth was broken internally, but cannot reproduce
