### ISSUE TITLE
Most of the peers have "Not active" statuses

### ISSUE THREAD

**Issue by akylbekesenaliev** [subutai-io/base#1061]
For the sake of testing I was trying to play with templates, environments, wanted to create a bunch of them and see how my system and Subutai are gonna react, and while doing that I have faced a strange behaviour, most of my environments have Not active statuses, I thought maybe - Running/Checking containers will help but it didn't.
![most of the envts are not active](https://cloud.githubusercontent.com/assets/17665678/16069957/fbbf92bc-32da-11e6-83c7-1ba1cd3d45f7.png)
About page:
![image](https://cloud.githubusercontent.com/assets/17665678/16069968/10fe42a4-32db-11e6-8bb8-802316e1d4ee.png)

**Comment by Dilshat** [comment]
@akylbekesenaliev are these env-s created on SS or on Hub?

**Comment by akylbekesenaliev** [comment]
@Dilshat these environments were created from the Subutai side

**Comment by Dilshat** [comment]
@akylbekesenaliev please retest and close if fixed
