### ISSUE TITLE
jdbc error creating environment

### ISSUE THREAD

**Issue by larenso** [subutai-io/base#1063]
log of env creation:
![image](https://cloud.githubusercontent.com/assets/4501130/16072567/51d099f8-3303-11e6-8c92-131fb0e9457f.png)

container is also created, but it doesn't show up in the env list, as found later jdbc error occured:
[karaflogs2016-06-15.13-22-23.txt](https://github.com/subutai-io/base/files/315653/karaflogs2016-06-15.13-22-23.txt)

**Comment by larenso** [comment]
cannot reproduce

**Comment by Dilshat** [comment]
Does not reproduce

**Comment by Commander223** [comment]
[karaflogs2016-06-18 15-15-51.txt](https://github.com/subutai-io/base/files/321671/karaflogs2016-06-18.15-15-51.txt)

**Comment by Commander223** [comment]
![image](https://cloud.githubusercontent.com/assets/1281861/16170076/c0fe2870-3567-11e6-9aca-83c0a723ea2f.png)

**Comment by Dilshat** [comment]
@TalasZh please try to use container managed transactions to solve this issue.
See Env Mgr DAO as an example

**Comment by Commander223** [comment]
But on hub i can see this env :)
![image](https://cloud.githubusercontent.com/assets/1281861/16176414/a1153368-3630-11e6-9a0a-e2599a5919ba.png)

**Comment by Commander223** [comment]
but not on subutai
![image](https://cloud.githubusercontent.com/assets/1281861/16176426/b3a8aa96-3630-11e6-85cc-e9e2f646da4c.png)

**Comment by Dilshat** [comment]
@Commander223 please retest and fix if closed

**Comment by Dilshat** [comment]
Fixed
