### ISSUE TITLE
[AppScale] Need add text error like in HUB

### ISSUE THREAD

**Issue by NickolaiVarin** [subutai-io/base#1064]
![ssapp](https://cloud.githubusercontent.com/assets/16968797/16075986/b2c22aa4-330a-11e6-97fb-6b15b6b2f705.png)

go to SS with 2Gb RAM -> Environments -> create AppScale envi

Observe that Preparing templates is Failed. 
Should add message to SS like in HUB and do not let the user to start create AS envi, without RAM increasing.

![hubapp](https://cloud.githubusercontent.com/assets/16968797/16076387/85aa02a6-330c-11e6-9b82-4bea03ff1aaa.png)

**Comment by asanaliev** [comment]
Related: [AppScale fails to install if RAM is not enough](https://github.com/optdyn/hub/issues/1287)
>The solution can be generic here, i.e. not specific to AppScale. For this, when environment is started we check if RH of peers have enough RAM to run containers with given size.
