### ISSUE TITLE
Changing password : Passwords dont match text appears before second input field is typed in

### ISSUE THREAD

**Issue by akylbekesenaliev** [subutai-io/base#1065]
#![not yet](https://cloud.githubusercontent.com/assets/17665678/16078205/2f80cfbe-3306-11e6-942f-a1d57cc27ea7.png)
While changing password  "password dont match" text appears before the second "Confirm password" input field is typed.
To play the bug go to:
1. User Identity
2.Account Settings
3.Change password
When a pop up message appears saying "You have successfully saved password" and when the pop up message is closed input fields should get emptied:
![after](https://cloud.githubusercontent.com/assets/17665678/16078299/bd70124e-3306-11e6-96ea-422127a4c4a4.png)
and when there is any kind of password mismatch and etc.. a poping message window should containe more digestible message in it:
![image](https://cloud.githubusercontent.com/assets/17665678/16078319/e2cdff1a-3306-11e6-9c7c-6702fd80faf6.png)

**Comment by larenso** [comment]
Not a bug, 
sometime it's ok to notify so user see that he must retype

**Comment by akylbekesenaliev** [comment]
@larenso ok , let me close the ticket then
