### ISSUE TITLE
User must not have access to RH console

### ISSUE THREAD

**Issue by samsonbek** [subutai-io/base#1076]
Currently any user, who accessed peer's management console (he may access it directly or rent peer and open MNG console), has access to RH's console, he can execute dangerous commands there: reboot or shutdown RH, ping any device in local network, create shell script and run it.

![image](https://cloud.githubusercontent.com/assets/4163679/16175523/962bb4d6-3612-11e6-9b53-84ef75f6aa60.png)

![image](https://cloud.githubusercontent.com/assets/4163679/16175524/aa02cbf2-3612-11e6-82c5-8eb269a23243.png)

So, for security terms, this RH console should be accessible only to owner of peer.

**Comment by Dilshat** [comment]
We need to close access both in UI and in code for the following sections:
Console->RH
Advanced->Console
These two must be available only to admin
Also in Karaf CLI we need to check if all probable breaches are closed for admin too (liek accessing other users' containers)

@TalasZh

**Comment by larenso** [comment]
Peer-Management security filter added for karaf and peer consoles
