### ISSUE TITLE
Cannot create ssh tunnel to container from Web UI

### ISSUE THREAD

**Issue by tzununbekov** [subutai-io/base#1082]
1) Setup peer, create environment
2) Go to environment console, choose container, press "SSH" button
3) Nothing will happen in UI, in karaf log following appears:

`2016-06-20 09:24:06,214 | ERROR | tp680253481-7715 | JAXRSUtils                       | 90 - org.apache.cxf.cxf-rt-frontend-jaxrs - 3.1.0 | No message body writer has been found for class io.subutai.common.environment.EnvironmentNotFoundException, ContentType: text/plain
`

**Comment by Dilshat** [comment]
Please attach karaf.log and About page screenshot

**Comment by Dilshat** [comment]
After testing on @tzununbekov machine, I found out that for env-s created from Hub we can not create ssh tunnels in SS UI whereas they can be created for env-s created on SS directly. 
After debugging I found that this method throws exception EnvironmentNotFoundException `io.subutai.core.environment.impl.EnvironmentManagerSecureProxy#setupSshTunnelForContainer`
@TalasZh

**Comment by TalasZh** [comment]
please attach logs @Dilshat @tzununbekov

**Comment by Dilshat** [comment]
@TalasZh there is no logs except the one provided by @tzununbekov

**Comment by zubaidullo** [comment]
I'm getting this, when I repeat above workflow with the latest SS 

![selection_115](https://cloud.githubusercontent.com/assets/4469949/16221784/6db81a8a-37b6-11e6-97fd-d48b4aee5b8c.png)

**Comment by Dilshat** [comment]
Did you create env from hub @zubaidullo

**Comment by zubaidullo** [comment]
No, in workflow there is nothing about Hub. 
I create on SS side

**Comment by Dilshat** [comment]
Please see my comment. Create env from Hub

**Comment by Dilshat** [comment]
@asanaliev Can you take a look?
Seems we need to relate Hub Env Owner with the env and its containers on SS side in the class io/subutai/core/hubmanager/impl/environment/state/build/BuildContainerStateHandler.java
Otherwise relation verification fails and we can not manipulate Hub env and its containers from SS side

**Comment by Dilshat** [comment]
This might be related to #1077

**Comment by Dilshat** [comment]
We can bypass checks for Hub env-s because we obtain their metadata from Hub and dont store them locally, thus Hub will filter data

**Comment by Dilshat** [comment]
Fixed

**Comment by Dilshat** [comment]
@tzununbekov please retest

**Comment by zubaidullo** [comment]
What I found on testing: EnvironmentNotFoundException
![selection_127](https://cloud.githubusercontent.com/assets/4469949/16327725/5dd5a912-39f4-11e6-8776-814b0d3c9caf.png)

**Comment by TalasZh** [comment]
what kind of environment it is (Hub, SS, cross-peer)?

**Comment by zubaidullo** [comment]
Hub

**Comment by TalasZh** [comment]
Hm, does this cause some anomalies? and in what conditions does this error is thrown?
btw attach logs here

**Comment by zubaidullo** [comment]
By debugging got this message: "You should pass relation token challenge first." 
![selection_128](https://cloud.githubusercontent.com/assets/4469949/16328148/b2d41d50-39f8-11e6-84d0-4e2dffb254ed.png)

**Comment by TalasZh** [comment]
give me more info about hub user and peer relation.
is it rented peer? peer about page?
btw update to latest version from dev branch, yesterday some fixes were merged

**Comment by zubaidullo** [comment]
Environment created from Hub side, by owner of peer.
  
About page: 
![selection_129](https://cloud.githubusercontent.com/assets/4469949/16328250/29f89d06-39fa-11e6-8a46-36c8085a7deb.png)

**Comment by TalasZh** [comment]
yeah try again when you update peer
and let me know about this error, thanks

**Comment by zubaidullo** [comment]
this is updated peer, from morning

**Comment by TalasZh** [comment]
probably management template is not updated on gorjun
commit ID should be https://github.com/subutai-io/base/commit/793ee97125db127ff929c14f4b4ff0673131b395

**Comment by Dilshat** [comment]
If you are trying to open ssh tunnel to a remote container for hub env then there is no relation on local peer. Soon such containers will not be shown in ui. Waiting for @larenso.

**Comment by zubaidullo** [comment]
It's working!

**Comment by zubaidullo** [comment]
@tzununbekov can you close this issue, pls?

**Comment by Dilshat** [comment]
does not reproduce since remote containers are not accessible from SS UI for Hub envs now
