### ISSUE TITLE
[Console] Can't observe remote peer.

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/base#1097]
For replay this bug you need:

Test case
1) Go to SS -> create x-peer environment with two containers (one on local, another one on remote peer).
2) Go to Console -> choose created environment -> containers.

Result: you can't observe remote container. 
![pasted image at 2016_06_24 01_29 pm](https://cloud.githubusercontent.com/assets/11311924/16333117/5cbde6e4-3a1b-11e6-99c0-32f005ddb719.png)

If you go to containers, you can observe two containers.
![pasted image at 2016_06_24 01_30 pm](https://cloud.githubusercontent.com/assets/11311924/16333148/8a7c1e2a-3a1b-11e6-8da1-76837ed64553.png)

**Comment by Dilshat** [comment]
Only SS env containers should be visible, for Hub envs we show only local containers

**Comment by NikolaiB** [comment]
Fixed.
