### ISSUE TITLE
Bugs in user management UI

### ISSUE THREAD

**Issue by samsonbek** [subutai-io/base#1101]
I created new user 'testpeer1owner' and assigned several roles to him.
![image](https://cloud.githubusercontent.com/assets/4163679/16370727/d28175f4-3c63-11e6-831f-26dcc422deaa.png)

sometimes when open edit form, assigned roles not listed in 'Assigned roles' section
![image](https://cloud.githubusercontent.com/assets/4163679/16370746/f7960a26-3c63-11e6-81ae-7cfe370c22bd.png)

sometimes when i click to remove role 'Environment manager' in user list, for that user, in confirmation dialog role name is 'undefined'
![image](https://cloud.githubusercontent.com/assets/4163679/16370778/3196a596-3c64-11e6-9c56-239595024e6f.png)

and sometimes when i click to edit that user, i see popup form with empty 'Assigned roles' and error in browser console
![image](https://cloud.githubusercontent.com/assets/4163679/16370792/4fb21fb0-3c64-11e6-9fe4-57e29450cf40.png)

**Comment by samsonbek** [comment]
if one of users has long name, table right side goes behind the screen border (my screen is 15''), and 'delete' controls become not visible, and there is no horizontal scrollbar.
![image](https://cloud.githubusercontent.com/assets/4163679/16370995/90d33064-3c65-11e6-8309-eed3fc76fa1b.png)

**Comment by TalasZh** [comment]
@samsonbek can you post here about page of peer?

**Comment by samsonbek** [comment]
@TalasZh 
![image](https://cloud.githubusercontent.com/assets/4163679/16404642/b9179d40-3d22-11e6-9b11-e69b1c56f8c9.png)

**Comment by samsonbek** [comment]
After updating to latest subutai/base bugs is still actual
![anim](https://cloud.githubusercontent.com/assets/4163679/16405037/3cc89cb8-3d26-11e6-93a6-2498860185c0.gif)

**Comment by Dilshat** [comment]
@TalasZh ^

**Comment by TalasZh** [comment]
@larenso seems this issue on front-end, have a look pls
