### ISSUE TITLE
Install the subutai browser plugin notification appears even if the plugin is added to browser extentions

### ISSUE THREAD

**Issue by akylbekesenaliev** [subutai-io/base#1109]
![plugin](https://cloud.githubusercontent.com/assets/17665678/16491434/c202eda4-3eff-11e6-870a-5784b0c9fb5b.png)
After installation of Subutai is done I receive this "Install the subutai browser plugin " notification even though I have already added this plugin to the chrome browser's extentions, when I click the notification it takes me to the plugin's page :
![plugin page](https://cloud.githubusercontent.com/assets/17665678/16491506/09947fa2-3f00-11e6-8975-b1c98e5306e9.png)
but as you can see the plugin is already added to the Chrome's extentions.
@Dilshat can you pls clarify this ticket, is this a bug or we need this to be the way it is now? 
While installing Subutai it gives a pop up about Installing the plugin so is it necessary to repeat the notification or was this intentionally made so users can double see it (kinda reminder)?  
But main point here is even if the plugin is installed the notification appears.

**Comment by Dilshat** [comment]
@larenso @TalasZh please comment

**Comment by larenso** [comment]
This could happen if you installed plugin, and then returned to Subutai, the message could still be there for some time, simple refresh triggers check function

**Comment by Dilshat** [comment]
@akylbekesenaliev is this comment enough? can we close the issue?

**Comment by akylbekesenaliev** [comment]
@Dilshat let me re-test
I am gonna delete the plugin from the browser, delete SS and install all over again, let me see if I am still gonna receive that notification if not I will close the issue.

**Comment by larenso** [comment]
@akylbekesenaliev btw, also pls check if plugin is enabled, it could also happen when your plugins is installed but disabled

**Comment by akylbekesenaliev** [comment]
@larenso sure

**Comment by akylbekesenaliev** [comment]
Re-tested, looks like the issue is gone now, closing the issue.
