### ISSUE TITLE
apt-get doesn't work in docker templates

### ISSUE THREAD

**Issue by asanaliev** [subutai-io/base#1110]
Almost in all docker templates `apt-get update` completes with the following errors:
```
W: GPG error: http://172.26.114.1 trusty-updates InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 40976EAF437D05B5 NO_PUBKEY 3B4FE6ACC0B21F32
W: GPG error: http://172.26.114.1 trusty-security InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 40976EAF437D05B5 NO_PUBKEY 3B4FE6ACC0B21F32
W: GPG error: http://172.26.114.1 trusty Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 40976EAF437D05B5 NO_PUBKEY 3B4FE6ACC0B21F32
```
Install doesn't work: 
`apt-get install vi`
```
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package vi
```

**Comment by tzununbekov** [comment]
Docker templates mostly based on Debian parent, whereas clone operation replacing apt repo list to local cache, which is configured for Ubuntu repositories. We'll fix it.

**Comment by tzununbekov** [comment]
@asanaliev fix merged to dev, please check if bug has gone
https://github.com/subutai-io/subos/pull/416

**Comment by akarasulu** [comment]
@asanaliev When you get a chance can you check if bug is gone and close this issue?

**Comment by eabyshev** [comment]
checked all docker templates, apt-get update works.
