### ISSUE TITLE
[UI] Every time users open the Chrome Browser E2E plugin extention appears in a new tab

### ISSUE THREAD

**Issue by akylbekesenaliev** [subutai-io/base#1131]
![image](https://cloud.githubusercontent.com/assets/17665678/16863463/a2cbb3aa-4a74-11e6-918d-f080103dfe15.png)
Was this intentionally made so? because its a bit annoying.... : 
Windows 10 OS, Chrome Browser

**Comment by Dilshat** [comment]
i think this happens intentionally until you generate a pgp key

**Comment by akylbekesenaliev** [comment]
@Dilshat I think its better to display this in a form of a notification , for example in SS : Generate E2E Key - text  and a green Generate button and when users click the button it takes them to this page , because this current situation kinda reminds of some viruses ) you know when a virus redirects you to another page...and thats not a good reminder for users ) , wdyt?

**Comment by Dilshat** [comment]
Yes we need to work on UX of plugin, agree.
We can do this later though

**Comment by Dilshat** [comment]
Fixed
