### ISSUE TITLE
Failed to change container size from Environment UI

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/base#1154]
Env as local and created with default small sized apache2 containers: three were created for the env. I was simply upgrading their size from small to medium on all of them and pressing change on this pre-created local environment and got stuck like this:

![screen shot 2016-07-24 at 7 32 04 pm](https://cloud.githubusercontent.com/assets/10051386/17087344/8dce8708-51d5-11e6-80cd-b5e0bd8b0feb.png)

Attached is the karaf.log file.

[karaflogs2016-07-24 19-34-31.txt](https://github.com/subutai-io/base/files/380549/karaflogs2016-07-24.19-34-31.txt)

**Comment by Dilshat** [comment]
Larik please use **io.subutai.core.lxc.quota.api.QuotaManager#setQuota**

**Comment by Dilshat** [comment]
@larenso use **io.subutai.common.peer.ContainerHost#setQuota**
