### ISSUE TITLE
Why are we still getting these errors on a fresh new peer?

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/base#1157]
The user will get confused thinking something is wrong. 

![screen shot 2016-07-24 at 7 55 15 pm](https://cloud.githubusercontent.com/assets/10051386/17087455/ae052d44-51d8-11e6-9e3e-e1e37706a5f2.png)

**Comment by crioto** [comment]
Reviewed log messages.

**Comment by crioto** [comment]
Issue can be closed.
