### ISSUE TITLE
Take assigned names from UI as hostnames of containers

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/base#1161]
To make user friendly container hostnames we need to use container names specified in UI as hostnames

**Comment by akarasulu** [comment]
@larenso we should review these issues there are other usability problems. I noticed that when people use SS or the Hub to login they're loosing track which container (belonging to which environment) they're logging into. 

Perhaps the environment's name should be used as the domain name too. If a domain is not explicitly assigned to the environment then use env name as the UNIX domain name. If a domain name is explicitly assigned we should use instead for the UNIX domain name. The fully qualified host name should be visible then on the command line after ssh'ing into the host. If this is a problem on the CLI we can also modify the banner that is shown on login. These names should also be clearly visible in the environment editor and in the container listings on the Hub and on SS. @larenso we really did not do UX on this as we should have but I think after using it more this is becoming clear. There's already an issue about this here:   #1156  and #1160.
