### ISSUE TITLE
Create config in apps/data dir to overwrite params from default file

### ISSUE THREAD

**Issue by p1gmale0n** [subutai-io/base#1184]
for support changing default settings of agent and don't lost changes after update rh,
need config file into apps/data dir

> it'll be a config which will overwrite params from default file
> because for now management section is enough but in future there may be another requirements

**Comment by tzununbekov** [comment]
Feature merged to dev
Config items from `/var/lib/apps/subutai/current/agent.gcfg` overwrites default values from config in app-path
