### ISSUE TITLE
Nice to show on RH listing which RH is running the management container

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/base#1203]
![screen shot 2016-08-06 at 12 30 54 pm](https://cloud.githubusercontent.com/assets/10051386/17457871/bb966dc6-5bd1-11e6-9d19-c1be93effba2.png)

Seeing from this I have no idea which one is running management. Sometimes I want to use non-management resources hosts for some workloads. But I cannot know which because this UI does not tell me. 

Would be nice if we can see this in the environment builder as well so we do not create containers on MH running RH.

**Comment by Dilshat** [comment]
@larenso you may use this method io.subutai.common.peer.ResourceHost#isManagementHost
