### ISSUE TITLE
On a start of the subutai VM is a heartbeat sent to the Hub?

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/base#1204]
I guess interfaces will change and a heartbeat will be sent. If not we need to make sure one is sent on startup. Also one should be sent on shutdown to indicate that the peer is going down.

**Comment by zubaidullo** [comment]
Heartbeat is running as one process in SS, on start of VM processes will start running, so heartbeat will be sent.

**Comment by tzununbekov** [comment]
Agent sends heartbeat when it starts to communicate with SS, don't know when SS sends it further to Hub. About pre-shutdown heartbeat - need to investigate Snappy ability to work with system runlevels

**Comment by Dilshat** [comment]
#1205

**Comment by akarasulu** [comment]
I think we should use both a run level script and jvm hook as in #1205. This will make it more solid. @tzununbekov can you add this as a todo but low priority for later. Right now let's not forget with filing an issue.

**Comment by tzununbekov** [comment]
subutai-io/subos#515

**Comment by Dilshat** [comment]
Fixed
