### ISSUE TITLE
[multi-rh] cannot re-approve rh on peer after reject

### ISSUE THREAD

**Issue by p1gmale0n** [subutai-io/base#1215]
create peer with few resource hosts
approve remote rh 
reject approved rh
try re-approve rejected rh

**Comment by Dilshat** [comment]
This is related to https://github.com/subutai-io/base/issues/1212
Once this issue is implemented the workflow will become like this:
Rejected request can be removed to allow re-registration, otherwise it will block the RH from joiining the peer.

**Comment by Dilshat** [comment]
@p1gmale0n can you check on last SS and close if fixed

**Comment by p1gmale0n** [comment]
fixed
