### ISSUE TITLE
[multi-rh] add RH id to list of Resource hosts (Environments->Advanced->Peer)

### ISSUE THREAD

**Issue by p1gmale0n** [subutai-io/base#1217]
If peer have >1 rh, 
cannot identify rh on advanced env creation:
![2016-08-09_13-27-36](https://cloud.githubusercontent.com/assets/1177402/17508180/7f43d280-5e35-11e6-8d0e-c0de7eaf9fb5.png)

**Comment by Dilshat** [comment]
Fixed
