### ISSUE TITLE
[UI] Getting "Role permission is safe :). Error: " when I am trying to delete a role

### ISSUE THREAD

**Issue by akylbekesenaliev** [subutai-io/base#1230]
![image](https://cloud.githubusercontent.com/assets/17665678/17587371/c4441178-5fe9-11e6-8f0f-98be3b24abd5.png)
When I am trying to remove a role I am getting that error above ^^^ 
To play the bug go to:
User Management > Environment Manager > Remove it

**Comment by Dilshat** [comment]
we should hide system users and permissions from editing

**Comment by Dilshat** [comment]
@akylbekesenaliev  please retest and close if fixed

**Comment by akylbekesenaliev** [comment]
@Dilshat tested, roles are hidden now, the ticket is fixed, closing it.
