### ISSUE TITLE
Throttle down when in use feature

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/base#1252]
While at Linux Foundation ContainerCon I was given some great advice on a throttle down feature which I think we should implement. 

On a desktop system with a peer, if we detect through the tray that the user is active browsing and using the machine then we make sure to throttle down activities. I guess other user containers are limited through the VM and perhaps we do not need this feature. However maybe we can suspend the VM if the user wants, or just throttle down activities to not disturb the user or degrade their experience on their own desktop because they're sharing resources. 

Something to think about. But the configuration for this should be managed by SS. This might need to be implemented by SS, subos, and tray through their interactions. Basically we have to prevent a degraded user experience on their own laptop/desktop when they're heavily using it. Of course this is only a concern of others' containers are heavily using the network, CPU and disk. Might not be a problem in most cases. Maybe we pass on this feature but we should have a discussion about it regardless.

**Comment by Dilshat** [comment]
Since SS resides inside VM, isn't it better for tray to control it?

**Comment by akarasulu** [comment]
Perhaps yes let's discuss this further. It's most likely going to need to be tray driven. Maybe tray can suspend the VM and then bring it back online based on user activity (keyboard + mouse). I know we cannot throttle a VM - need to turn it off to be able to throttle it down. However we might be able to suspend it. @Lezh1k any ideas?

**Comment by Dilshat** [comment]
Will be handled in the course of https://github.com/subutai-io/tray/issues/254
