### ISSUE TITLE
[UI] Make the message more digestible  > Environments > Add > pop up window

### ISSUE THREAD

**Issue by akylbekesenaliev** [subutai-io/base#1254]
![image](https://cloud.githubusercontent.com/assets/17665678/18002396/5d52f882-6ba9-11e6-9cd7-3609af2dafa6.png)
talked this out with @eabyshev and he suggested to change envID to  envName < @Commander223 
Enhancement: 
Make the message more digestible  > Environments > Add > pop up window

**Comment by Dilshat** [comment]
Fixed
