### ISSUE TITLE
Cannot clone ubu16 template

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/base#1257]
<img width="759" alt="screen shot 2016-09-02 at 6 13 42 pm" src="https://cloud.githubusercontent.com/assets/10051386/18219648/479f8b78-7139-11e6-9973-882e9b84c1c2.png">
<img width="557" alt="screen shot 2016-09-02 at 6 14 39 pm" src="https://cloud.githubusercontent.com/assets/10051386/18219652/4a12767c-7139-11e6-8c40-ce4b101226dc.png">
[karaflogs2016-09-02 18-16-12.txt](https://github.com/subutai-io/base/files/452992/karaflogs2016-09-02.18-16-12.txt)

**Comment by Dilshat** [comment]
`2016-09-02 22:05:40,910 | DEBUG | ool-119-thread-2 | CommandProcessor                 | 159 - io.subutai.core.executor.impl - 4.0.3 | Sending:
{
  "request": {
    "type": "EXECUTE_REQUEST",
    "id": "1F6BC3C2693CD78EE28EFB236C9E34FAAC217EB4",
    "commandId": "6f7498aa-2fb0-4404-b9a2-8673fe9925d5",
    "workingDirectory": "/",
    "command": "subutai clone",
    "args": [
      "id:c0d9f79ca76a7eb7e9f0a4f8ed522585",
      "Container-2-106-2",
      "-i",
      "\"172.20.145.2/24 106\"",
      "-e",
      "6ea9a273-da4d-4519-8e83-7043792303a2",
      "-t",
      "6395771d-cdd7-47ec-ba0d-df897d1a5654"
    ],
    "stdOut": "RETURN",
    "stdErr": "RETURN",
    "runAs": "root",
    "timeout": 300,
    "isDaemon": 0
  }
}


2016-09-02 22:06:08,343 | DEBUG | p1685034846-2879 | CommandProcessor                 | 159 - io.subutai.core.executor.impl - 4.0.3 | Response: ResponseImpl[type=EXECUTE_RESPONSE,id=1F6BC3C2693CD78EE28EFB236C9E34FAAC217EB4,commandId=6f7498aa-2fb0-4404-b9a2-8673fe9925d5,pid=0,responseNumber=1,stdOut=time="2016-09-02 22:05:43" level=info msg="[CDN unreachable, retrying]" 
time="2016-09-02 22:05:48" level=info msg="[CDN unreachable, retrying]" 
time="2016-09-02 22:05:53" level=info msg="[CDN unreachable, retrying]" 
time="2016-09-02 22:05:58" level=info msg="[CDN unreachable, retrying]" 
time="2016-09-02 22:06:03" level=info msg="[CDN unreachable, retrying]" 
time="2016-09-02 22:06:08" level=warning msg="Checking CDN accessibility, dial tcp: i/o timeout" 
,stdErr=<null>,exitCode=0]`

**Comment by Dilshat** [comment]
Seems this is a network glitch, @akarasulu please close if does not reproduce

**Comment by akarasulu** [comment]
Yes it's looking like that exactly. Closing issue.
