### ISSUE TITLE
Installation duplication of plugin, if plugin was installed manualy

### ISSUE THREAD

**Issue by p1gmale0n** [subutai-io/base#1267]
newer hadoop plugin was installed manually
i'm tried install Flume plugin.
Got popup - flume have additional dependency - proceed ? 
after confirm - SS installed 2nd hadoop plugin 
and it is broke SS

**Comment by Commander223** [comment]
SS broken because we have 2 state 'hadoop' in subutai-app.js, first add manually, second added after hadoop was installed from bazzar (hadoop was installed like dependency from Flume)
2 similar state broke routing on SS
It mean if we install plugin manually it didn't write info about installation in database or somewhere else, that's why it installed second time

**Comment by Dilshat** [comment]
We might go 2 ways:

1) Register manually installed plugin into plugin db
But in this case we don't have Hub properties of plugin such as Kurjun url, hub plugin id etc
here we might incorporate this information into bundle manifest somehow and extract from it

2) Remove manually installed bundle if it has the same bundle name, version or other property and then install Hub plugin

**Comment by p1gmale0n** [comment]
@Dilshat 
> //remove existing plugin with the same name if any to avoid corruptions
not it fixed only, if name of plugin is same

in current implementation, remove plugins by name is not enough.
on manual plugin install form we can set any name to plugin:
![2016-09-13_12-17-59](https://cloud.githubusercontent.com/assets/1177402/18463457/244330aa-79ac-11e6-8350-2064849aa57c.png)
maybe kar file have some meta info with plugin name? and dont set name manualy

**Comment by Dilshat** [comment]
We must include plugin id into kar metadata @eabyshev @zubaidullo

**Comment by p1gmale0n** [comment]
also, after reinstall plugin via bazaar, am still have plugin on Advanced tab

**Comment by zubaidullo** [comment]
Product ID, it's given by Hub id or it's ID from kurgun?

**Comment by Dilshat** [comment]
Seems it is given by Hub

**Comment by zubaidullo** [comment]
Hmm, actually this ID is provided, but it's not used on SS side

**Comment by Dilshat** [comment]
Is this ID inside kar?

**Comment by zubaidullo** [comment]
When, SS requests to get Products info, Hub provides product info like: id, name, url, logo,etc. in JSON format. SS uses only metadata URL

**Comment by soffokl** [comment]
Do we need ability to install plugins directly to SS? May be easiest way just disable it, and show message to user like "if you want to install your own plugin please upload it to HUB first".
Like we did for templates.

**Comment by Dilshat** [comment]
We can not prevent user from copying a plugin kar directly to deploy folder I guess

**Comment by Dilshat** [comment]
@p1gmale0n  please retest and close if fixed

**Comment by p1gmale0n** [comment]
Installation duplication of plugin - not broke SS.
