### ISSUE TITLE
Do checks in env build before executing next step received from Hub to make it idempotent

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/base#1276]
We need to perform check on SS side to see if we already executed the current step received from Hub.
For example consider a situation:
Peer performs CLONE step and goes offline/looses connectivity without having sent DONE response to Hub.
Next time when peer goes online, it will again receive the CLONE command.
Here we need to perform checks to avoid duplicate clones.
This concerns each step in env build.

**Comment by zubaidullo** [comment]
What can be done here (IMO):
- Check existing of current command (ex: is container cloned), just before executing
- Save this thread, that when goes online peer could continue

**Comment by Dilshat** [comment]
We should at least add some checks for now.
This will help in the case when connectivity was gone for a while but step was performed correctly on a peer.
For the case when peer is rebooted or stopped in the middle of performing a step, we can not guarantee the result, such environment should be marked as Unhealthy and preferably destroyed later on.

**Comment by Dilshat** [comment]
Seems necessary checks are present and sufficient for now
