### ISSUE TITLE
We need "preferredSize" field in template metadata

### ISSUE THREAD

**Issue by tjamakeev** [subutai-io/base#1289]
1. the export procedure should have switch to specify the subutai.preferredSize property and inject into LXC configuration (if nothing is specified I guess we can default to using TINY)
2. the upload to gorjun should extract this and be able to answer questions about the preferredSize of the container to use for instantiating the template (answer question is REST endpoint on Gorjun)

**Comment by tzununbekov** [comment]
Gorjun in production, CLI merged to dev

https://eu0.cdn.subut.ai:8338/kurjun/rest/template/info?name=master
parameter name is `prefsize`
