### ISSUE TITLE
Change output of "subutai management_network detect" command for case if address can not be detected

### ISSUE THREAD

**Issue by btemir** [subutai-io/base#1303]
If address is not detected we have output: 
![pasted image at 2016_09_29 18_09](https://cloud.githubusercontent.com/assets/16958983/18956149/2feca364-867c-11e6-8a10-4ef0d0697eaa.png)
 
It is not empty string or Null or space
Would be good to have definite message  like "No address" or something (anyways we will analyze if it is proper ipv4 address in code, but non-empty string with unprintable characters can confuse)

**Comment by tzununbekov** [comment]
Output value changed to "null" *string*
