### ISSUE TITLE
Create Security & Identity Infrastructure documentation

### ISSUE THREAD

**Issue by nk-the-crazy** [subutai-io/base#1323]
Create Security & Identity Infrastructure documentation .
Document SS overall security architecture and developer guide with API.

**Comment by nk-the-crazy** [comment]
Images for Security documentation:
![ss_arch](https://cloud.githubusercontent.com/assets/11713346/19467197/aeebf7e6-9531-11e6-977d-1d56ec9ac2df.png)

**Comment by nk-the-crazy** [comment]
Images for Developer Guide:
<img src="https://cloud.githubusercontent.com/assets/11713346/19511666/fe936a6c-9609-11e6-834c-5fd2cc7ac004.png" widht="150">

**Comment by Dilshat** [comment]
Done
