### ISSUE TITLE
Cleanup "management_network" binding

### ISSUE THREAD

**Issue by tzununbekov** [subutai-io/base#1324]
Looks like in management_network command we have several deprecated functions which was kept for back compatibility (tunnel list/create, vni map list/create). Need to make sure that SS is not using those functions and if so, remove them. Otherwise ask SS to use "tunnel" subcommand.

**Comment by Dilshat** [comment]
SS uses only the following commands:
**subutai management_network p2p ...**
**subutai management_network tunnel ...**

**Comment by tzununbekov** [comment]
@Dilshat thanks

**Comment by soffokl** [comment]
In this case we can remove management_network binding at all.
And create `subutai p2p ...` and `subutai tunnel ...` for simplification.

**Comment by Dilshat** [comment]
Right

**Comment by tzununbekov** [comment]
I will create another issue for removing whole management_network then, a little later

**Comment by tzununbekov** [comment]
binding was cleaned up as part of common issue:
https://github.com/subutai-io/base/issues/1332
