### ISSUE TITLE
[Resource Hosts] UI is not consistent and might confuse users

### ISSUE THREAD

**Issue by asanaliev** [subutai-io/base#1405]
![image](https://cloud.githubusercontent.com/assets/7465404/20039995/32c2b914-a479-11e6-92e8-cfc90301bc50.png)

This UI uses elements with other meaning than in other pages. What can be improved:
- Use "green dot" to indicate online state.
- Add a new column for online state.
- Use checkbox for approved status.
- The Remove button should not black but red as it is in most places.
- Better use label "management" instead of abbreviation MH (new users might not be familiar yet with our terminology).

**Comment by Dilshat** [comment]
The Remove button is dark because red color is used for Reject action

![image](https://cloud.githubusercontent.com/assets/3367326/20048723/d0507922-a4e8-11e6-98cf-42c8f0cc8725.png)

**Comment by Dilshat** [comment]
No need to show checkbox because button combination already clarifies if it is Approved Or not

**Comment by Dilshat** [comment]
I will just change MH to management and green dot will denote connection status instead of registration status

**Comment by Dilshat** [comment]
Fixed https://github.com/subutai-io/base/pull/1407
