### ISSUE TITLE
[Environment Domain] Adding SSL certificate not works

### ISSUE THREAD

**Issue by absidish** [subutai-io/base#1447]
When user tries add SSL certificate to domain it saved successfully, but in fact domain:443 not works.
![screenshot 22](https://cloud.githubusercontent.com/assets/8696139/20342811/1a5e3d7c-ac16-11e6-88b8-40c32a6a0c30.png)

**Comment by Dilshat** [comment]
Fixed , please retest @absidish

**Comment by absidish** [comment]
confirm fixed
