### ISSUE TITLE
When template is updated in gorjun SS should allow for means to upgrade it

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/base#1463]
Right now manual intervention is needed to destroy then re-import with updates to templates. This is bad news and we need to fix this before it becomes a headache.

**Comment by Dilshat** [comment]
I think local Gorjun must do a periodic check if there is any update since last checkpoint and mark changed templates so that on the next import/clone from local client CLI, it will pull changed templates from Global Gorjun or it can do lite check-request before any clone/import to compare md5sums of local and global templates.

**Comment by akarasulu** [comment]
Periodic checks are bad news. Instead the trigger will be from SS when there's an action on using an existing imported template. This obviously trickles down to the SubOS and it can do this check too. However I think there needs to be some considerations made. Are there containers already using the OLD template and if so, then you cannot upgrade it, and thus other peers that have not imported **MUST** import the OLD template.

I had mentioned repeatedly, over a year ago the need to version templates so we do not get trapped into these situations. I imagine we did not do that? Or did we? @soffokl @tzununbekov can you guys comment as well please when you get a chance? There are other higher priority issues we're facing now.

**Comment by Dilshat** [comment]
May be we should not allow to update existing template, If Id of template does not change then the template md5um does not change. Hub passes template ids down to SS. The same way SS UI can show to user template details like author and creation date. Use will pick the template he needs (by author, name and date) and SS will use its id internally.
The update of the same template with the same id but different contents is a bad idea

**Comment by Dilshat** [comment]
SS uses only template ids in import and clone operations.
Currently SS UI shows details of template such as version, owner and size (in a tooltip when hovering over a template). This way user can precisely select which template to use. We avoid replacing templates with the same id. New templates will have new IDs and new versions respectively.
We need to show similar detailed information on template in Hub too
