### ISSUE TITLE
Cannot SSH to container without registering to the HUB

### ISSUE THREAD

**Issue by soffokl** [subutai-io/base#1465]
If you trying to ssh to container on local Peer, you need to be registered to the HUB first. 
![image](https://cloud.githubusercontent.com/assets/8612618/20510224/1d09de82-b099-11e6-8e5f-3633939fa853.png)

We should implement connecting to the local containers without HUB, or add proper description what should be done for that.

**Comment by Dilshat** [comment]
Seems tray needs info about containers from Hub.
This is why this functionality is disabled.
@Lezh1k can you comment please

**Comment by Lezh1k** [comment]
If tray hasn't info about containers from HUB it won't ez-ssh to that containers.

**Comment by Dilshat** [comment]
@spaiker please see if we can show different messages when e2e not installed and when SS is not registered with Hub

**Comment by akarasulu** [comment]
What was done for this exactly? There's nothing telling me about how we fixed this.

**Comment by Dilshat** [comment]
The notification message was changed to better inform user that peer registration with Hub is required
