### ISSUE TITLE
[Hub - SS] improve auto-authorization between Hub and SS

### ISSUE THREAD

**Issue by zubaidullo** [subutai-io/base#1486]
Hub uses token for auto-authorize to SS. Now, Hub uses one token, which comes with peer registration. 
Long time token is not secure, need to update every-time after Hub uses that token. 
How it will work: 
1) Hub signs token, sends to SS
2) SS will decrypt and then checks if token expired or not. If expired will send new token
3) Hub will get new token or old if not expired, then authorize.  

1,2 cases are not exists in current workflow. Need to implement them.

**Comment by Dilshat** [comment]
@zubaidullo @eabyshev guys please consider the following workflow:

1) We dont generate permanent tokens anymore
   neither during registration of peer, nor during environment creations

2) every user has its subutait ID stored on hub
   admin, and env owners (delegates created during env build on SS)  IDs will be stored on Hub

3) When user wants to open MH Console from Hub, Hub will pass this user ID to SS in heartbeat

4) SS will generate temp session token for user ID

5) Hub will open MH Console with this token

6) Env owners will auto-login to peers

7) Peer owners will not, they wil have to use own admin user credentials + will be more secure way

**Comment by zubaidullo** [comment]
Current workflow in Hub. 
- Environment have owner token, where Hub uses this token (only if Hub user uses not own peer) to authenticate for SS. But, that workflow don't properly used, b/c token was permanent. 

What we're changing now: 
- Changing token to temporary token. So, here we're implementing update token when lifetime ends.
- Also, one environment can have more tokens (b/c tokens changing in every peer), where this case was not used in previous workflow.  So, here Hub have to control all tokens of Hub environments. Here, we need to add multi token control for environments.

**Comment by zubaidullo** [comment]
Mar 27, 2017: BASE-1486: implementation of UserToken model

**Comment by zubaidullo** [comment]
Mar 29, 2017: BASE-1486 Refactor previous userToken implementation, change to global usable. Implement model, dao layers

**Comment by zubaidullo** [comment]
Mar 30, 2017: ASE-1486: Basic Implementation of REST user token controller and services

**Comment by zubaidullo** [comment]
Apr 3, 2017: BASE-1486: improve user token usage on Environment creation steps

**Comment by zubaidullo** [comment]
- Refactor Git project, org, rest user controller layers, change user token usages with additional fields 
- save SS user ID with token

**Comment by zubaidullo** [comment]
Had issue related to this: https://youtrack.jetbrains.com/issue/IDEA-165800

**Comment by zubaidullo** [comment]
SS built by dev snap was requesting to **dev.subut.ai,** but I configured local Hub to **hub.subut.ai** (as before, any branch snap was requesting to hub.subut.ai), this situation was blocker
