### ISSUE TITLE
Several things wrong with updates

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/base#1493]
1. I do update which takes a long long time but I think the spinner just does not return success and stop spinning - I was waiting needlessly
2. Went to the history page after noticing the update occurred and got this error:

![screen shot 2016-11-25 at 5 27 38 pm](https://cloud.githubusercontent.com/assets/10051386/20629604/25a1a0a4-b335-11e6-9871-523df8dd5fef.png)

3. I kept hitting ok to get past this popup and finally saw the following information on the History tab (note the missing table cells in the one row):

![screen shot 2016-11-25 at 5 28 54 pm](https://cloud.githubusercontent.com/assets/10051386/20629619/39425d56-b335-11e6-9f9f-4c50e858aa45.png)

Here's the About page as well:

![screen shot 2016-11-25 at 5 31 49 pm](https://cloud.githubusercontent.com/assets/10051386/20629625/4109a670-b335-11e6-866c-e94fc20bba6f.png)

**Comment by akarasulu** [comment]
[karaflogs2016-11-25 17-35-08.txt](https://github.com/subutai-io/base/files/613528/karaflogs2016-11-25.17-35-08.txt)

**Comment by Dilshat** [comment]
@Commander223  Cnn you see please why table complains when data is partial like this:

`[
  {
    "updateDate": 1480087334352,
    "prevVersion": "4.0.9-SNAPSHOT",
    "prevCommitId": "7703bc24a27b2132148d49b4879ef1073241ed2a"
  }
]`

**Comment by Dilshat** [comment]
Also we need to have a flag that update is in progress on backend so that if user goes to another page and returns back to Update , Update page will be again disabled with spinner to let user know that update is not fiinshed yet.

**Comment by Dilshat** [comment]
@akarasulu please recheck

**Comment by Dilshat** [comment]
Fixed
