### ISSUE TITLE
How about showing the name of the peer somewhere obvious so we don't get confused?

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/base#1500]
It would be nice for us to show the name of the peer. I have several peer consoles open and I have no idea which is which. After 2 consoles it gets out of control to track by peer UUID. This is madness. Let's fix this fast.

**Comment by Dilshat** [comment]
Can not this be determined by address?:
![image](https://cloud.githubusercontent.com/assets/3367326/20645254/59e3b9da-b482-11e6-8d1e-2df6e501527c.png)

**Comment by Dilshat** [comment]
For registered peers  peer name is displayed in page title
![image](https://cloud.githubusercontent.com/assets/3367326/20657636/a67a22f4-b561-11e6-9d99-b002ade91adc.png)
