### ISSUE TITLE
RAM available on unused peer looks suspiciously low 

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/base#1501]
I'm thinking we're calculating the available RAM on a peer's resource host incorrectly. An unused cloud peer RH with 3.6G of RAM is only showing 0.3G available. This simply cannot be. We have to calculate this based on the RAM reservations of all the containers and the management container if it is running on the peer.

![screen shot 2016-11-26 at 3 53 25 pm](https://cloud.githubusercontent.com/assets/10051386/20640766/c435d3be-b3f0-11e6-9cde-793463a4a265.png)

**Comment by Dilshat** [comment]
@tjamakeev how do you calculate it?

**Comment by Dilshat** [comment]
Seems metrics are close to reality:

![image](https://cloud.githubusercontent.com/assets/3367326/20645244/189e8504-b482-11e6-85a6-f5c6fdee26f4.png)


![image](https://cloud.githubusercontent.com/assets/3367326/20645248/255401c0-b482-11e6-9ad6-28e4a39a0b63.png)

**Comment by tjamakeev** [comment]
checked: 
![image](https://cloud.githubusercontent.com/assets/16950402/21226195/9afedb68-c2fe-11e6-9543-ef5b6fcb5005.png)
![image](https://cloud.githubusercontent.com/assets/16950402/21226207/a6a5b86a-c2fe-11e6-8120-30519575b5c9.png)

in high loaded RH this value (300MiB) may take place
