### ISSUE TITLE
SS not filters env names from Hub

### ISSUE THREAD

**Issue by tzununbekov** [subutai-io/base#1515]
If Hub user create environment with malformed name, SS will not filter it in its Web UI what leads to possible XSS attack:  

![image](https://cloud.githubusercontent.com/assets/13515865/20706581/2e207ef6-b652-11e6-9155-ee0f6affe92d.png)

such environment on Hub will cause following result on peer:

![image](https://cloud.githubusercontent.com/assets/13515865/20707159/a4c74376-b654-11e6-9337-602ad8317d5d.png)

**Comment by Dilshat** [comment]
@tzununbekov please recheck

**Comment by tzununbekov** [comment]
looks like fixed, thanks
