### ISSUE TITLE
Failed to rename container with unknown error

### ISSUE THREAD

**Issue by soffokl** [subutai-io/base#1532]
Environment created on HUB. Logined to my peer under admin user. 
Trying to rename container to `1`: 
![image](https://cloud.githubusercontent.com/assets/8612618/20829651/2424af2e-b8a7-11e6-8c72-274c0b72748f.png)

**Comment by soffokl** [comment]
[karaflogs2016-12-02 15-55-25.txt](https://github.com/subutai-io/base/files/626823/karaflogs2016-12-02.15-55-25.txt)

**Comment by Dilshat** [comment]
Disabled functionality for Hub containers. Needs to be implemented on Hub first.
@soffokl please recheck.

**Comment by Dilshat** [comment]
Done
