### ISSUE TITLE
Add page for orphan containers

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/base#1536]
Create a subpage under Environments section called Orphan containers.
Display containers obtained from this REST there: GET [https://ip:8443/rest/ui/local/containers/notregistered](url)
Tabular format with columns: containername, ip, X (delete link)
For deletion use this REST: DELETE https://ip:8443/rest/ui/local/containers/notregistered/{containerID}

**Comment by akarasulu** [comment]
I don't understand why this is being turned into a page in the first place. Orphaned Containers are a due to the system **NOT** working properly. Instead of making this into a page it should be fixed.

**Comment by Dilshat** [comment]
Containers might be created manually. Such containers will be shown on this page and user will be able to destroy them there.

**Comment by Dilshat** [comment]
@Commander223 lets put these containers on Containers page under item "Orphan" in Environments combobox. Destruction link should call REST as written above

**Comment by Dilshat** [comment]
Done
