### ISSUE TITLE
Having creepy looking error while trying to register my peer to the Hub

### ISSUE THREAD

**Issue by akylbekesenaliev** [subutai-io/base#1554]
![image](https://cloud.githubusercontent.com/assets/17665678/20912959/f4508b3e-bb9d-11e6-86ad-0beaeae32921.png)

I have just installed subutai (-dev) and I wanted to register it to the Hub, then I got that really long looking error.
![image](https://cloud.githubusercontent.com/assets/17665678/20912925/a18e8e0a-bb9d-11e6-9790-07295dff87dd.png)

The error I got : 
`Error registering peer public key with Hub: <!DOCTYPE html> <html lang="en"> <head> <meta charset="utf-8"> <meta name="viewport" content="width=device-width, initial-scale=1.0"> <title>Error. Internal Server Error.</title> <link href="/assets/theme/css/bootstrap.min.css" rel="stylesheet"> <link href="/assets/theme/font-awesome/css/font-awesome.css" rel="stylesheet"> <link href="/assets/theme/css/animate.css" rel="stylesheet"> <link href="/assets/theme/css/plugins/toastr/toastr.min.css" rel="stylesheet"> <link href="/assets/theme/css/style.css" rel="stylesheet"> <link href="/assets/css/plugins/helpTip/helpTip.css" rel="stylesheet"> <script src="/assets/js/html5.js"></script> <script src="/assets/theme/js/jquery/jquery-2.1.1.js"></script> <script src="/assets/theme/js/bootstrap/bootstrap.min.js"></script> <script src="/assets/theme/js/plugins/toastr/toastr.min.js"></script> <script src="/assets/js/toastrConf.js"></script> <script src="/assets/js/plugins/qrCode/jquery.qrcode-0.12.0.min.js"></script> <link href="/assets/css/custom.css" rel="stylesheet"> </head> <body class="top-navigation"> <div id="wrapper"> <div id="page-wrapper"> <div class="middle-box text-center animated fadeInDown"> <h1>500</h1> <h3 class="font-bold">Internal Server Error</h3> <div class="error-desc"> The server encountered something unexpected that didn't allow it to complete the request. We apologize.<br/> You can go back to main page: <br/><a href="/" class="btn btn-primary m-t">Main page</a> </div> </div> </div> </div> </body> </html>`

**Comment by akarasulu** [comment]
Damn that is creepy :)

**Comment by Dilshat** [comment]
Will be fixed in the course of this Hub issue https://github.com/optdyn/hub/issues/2481
