### ISSUE TITLE
Docker to Subutai 

### ISSUE THREAD

**Issue by p1gmale0n** [subutai-io/base#156]
Make tool to convert Dockerfile on bash script. Created script installing running all command from Dockerfile, contains and deploy attached files and convert CMD command (from dockerfile) to system service.

**Comment by p1gmale0n** [comment]
now, generated script include all files from dockerfile dir.
need _uuencode_ installed

**Comment by p1gmale0n** [comment]
2189278
required installed openssh-server

**Comment by Dilshat** [comment]
not actual,
