### ISSUE TITLE
Sorting by date is not correct in update history

### ISSUE THREAD

**Issue by samsonbek** [subutai-io/base#1605]
![image](https://cloud.githubusercontent.com/assets/4163679/21213467/bbef43a2-c2be-11e6-8f47-12782a7b9db4.png)
Sorting by date don't work correct, because it sorts  dates as a text. Date format should be like `YYYY-mm-DD HH24:MM:SS` in order to be sorted correctly. Or another option is to modify sorting function to parse date as is and sort correctly.

PS. Data which comes from REST endpoint for history:
`[
  {
    "updateDate": 1481781321989,
    "prevVersion": "4.0.11-SNAPSHOT",
    "currentVersion": "No change",
    "prevCommitId": "059e3e6582e8c2d63d3290a1bc6cf0e4d3100900",
    "currentCommitId": "Other (system) components updated"
  },
  {
    "updateDate": 1481643288912,
    "prevVersion": "4.0.11-SNAPSHOT",
    "currentVersion": "4.0.11-SNAPSHOT",
    "prevCommitId": "5f278147c67773a0441e9be279d23db53a95daa6",
    "currentCommitId": "059e3e6582e8c2d63d3290a1bc6cf0e4d3100900"
  },
  {
    "updateDate": 1481612975953,
    "prevVersion": "4.0.11-SNAPSHOT",
    "currentVersion": "4.0.11-SNAPSHOT",
    "prevCommitId": "391d41f39acd8b0d248dff1735b5359bafb6c987",
    "currentCommitId": "5f278147c67773a0441e9be279d23db53a95daa6"
  },
  {
    "updateDate": 1481602932009,
    "prevVersion": "4.0.11-SNAPSHOT",
    "currentVersion": "4.0.11-SNAPSHOT",
    "prevCommitId": "10c482888197bf590e3113053b540066d9ab10a3",
    "currentCommitId": "391d41f39acd8b0d248dff1735b5359bafb6c987"
  },
  {
    "updateDate": 1481522569850,
    "prevVersion": "4.0.11-SNAPSHOT",
    "currentVersion": "4.0.11-SNAPSHOT",
    "prevCommitId": "230e05928eca684086c6b4e5cac0eefa02b09d32",
    "currentCommitId": "10c482888197bf590e3113053b540066d9ab10a3"
  },
  {
    "updateDate": 1481515942319,
    "prevVersion": "4.0.11-SNAPSHOT",
    "currentVersion": "4.0.11-SNAPSHOT",
    "prevCommitId": "124dcacd29568483d61b4703ef1932b341ee317e",
    "currentCommitId": "230e05928eca684086c6b4e5cac0eefa02b09d32"
  },
  {
    "updateDate": 1481281733008,
    "prevVersion": "4.0.11-SNAPSHOT",
    "currentVersion": "4.0.11-SNAPSHOT",
    "prevCommitId": "22d6ff502d153d306fba3d737710086a868af4ba",
    "currentCommitId": "124dcacd29568483d61b4703ef1932b341ee317e"
  },
  {
    "updateDate": 1481266432469,
    "prevVersion": "4.0.11-SNAPSHOT",
    "currentVersion": "4.0.11-SNAPSHOT",
    "prevCommitId": "e0d284637055a18884b8ccc1b70558fa6cda4777",
    "currentCommitId": "22d6ff502d153d306fba3d737710086a868af4ba"
  },
  {
    "updateDate": 1481176504902,
    "prevVersion": "4.0.10-SNAPSHOT",
    "currentVersion": "4.0.11-SNAPSHOT",
    "prevCommitId": "1000347fdc642d14d8de6e7b865706af18e47ed8",
    "currentCommitId": "e0d284637055a18884b8ccc1b70558fa6cda4777"
  },
  {
    "updateDate": 1481094236632,
    "prevVersion": "4.0.10-SNAPSHOT",
    "currentVersion": "4.0.10-SNAPSHOT",
    "prevCommitId": "c8fa8ac55d21ceb6407b89ef032b77596da0d752",
    "currentCommitId": "1000347fdc642d14d8de6e7b865706af18e47ed8"
  },
  {
    "updateDate": 1481015681163,
    "prevVersion": "4.0.10-SNAPSHOT",
    "currentVersion": "4.0.10-SNAPSHOT",
    "prevCommitId": "1000fc6c78dadceaa07a4b10b2cef680fe976482",
    "currentCommitId": "c8fa8ac55d21ceb6407b89ef032b77596da0d752"
  },
  {
    "updateDate": 1481013135938,
    "prevVersion": "4.0.10-SNAPSHOT",
    "currentVersion": "No change",
    "prevCommitId": "1000fc6c78dadceaa07a4b10b2cef680fe976482",
    "currentCommitId": "Other (system) components updated"
  }
]`

**Comment by Dilshat** [comment]
@samsonbek please check and close if fixed
