### ISSUE TITLE
Handle orphan containers

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/base#1610]
1. We need to destroy orphaned containers that are left when Hub env is destroyed but peer was offline
2. Rename current orphan containers to standalone to avoid confusion
3. Notify Hub about environments destroyed when Hub was not accessible

**Comment by Dilshat** [comment]
Now every 30 min SS will sync envs with HUb

**Comment by akarasulu** [comment]
Why can't we just use the next HB instead of having another interval in the picture?

**Comment by Dilshat** [comment]
HB has a diff meaning. It polls for a Hub side command. But this env sync is SS side issue.
