### ISSUE TITLE
Respond according to network connectivity or Hub upgrade issues

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/base#1613]
While looking at the peer logs collecting in the Hub I noticed a lot of noise due to network connectivity issues. Some of these are resulting from Hub deployment. Please see https://github.com/optdyn/hub/issues/2617 for more details on deployment based network issue handling. Others especially for local peers on laptops result from networking being down. 

This is unnecessary noise that hides real issues. SS needs to be aware of when network connectivity is down so it does not blow exceptions for reasons of deployment or a laptop running offline. The offline problem can be solved with a REST endpoint where the Tray can report network connectivity issues to the management host. This way exceptions that occur are ignored or their level is dropped from ERROR to INFO without the need for a stack trace.

**Comment by Dilshat** [comment]
We might just reduce error log from stacktrace to error message

**Comment by Dilshat** [comment]
Fixed

**Comment by akarasulu** [comment]
This is NOT a fix. You're dangerously silencing the logs. We might actually need to see the stack trace if the network issue is a valid one. The key is to differentiate when it is a valid error and when it is not. If you have not done this we must reopen this issue.

I checked git. This is not a fix. Reopening...

**Comment by Dilshat** [comment]
@Lezh1k seems we need your participation

**Comment by Dilshat** [comment]
I restored the stacktraces except the one that happens on heartbeat. if HB fails then whatever reason is, SS will have the same cause - Connection Exception
