### ISSUE TITLE
MH don't have [MH] indicator in monitoring page select list

### ISSUE THREAD

**Issue by samsonbek** [subutai-io/base#1638]
![image](https://cloud.githubusercontent.com/assets/4163679/21448520/d3ac52e6-c90d-11e6-8952-165197c724b2.png)

In **Console** page we have select list of resource hosts, and management host has [MH] mark, it helps to differentiate it from others. But in **Monitoring** page same list of resource hosts is without such mark, and it's hard to detect which one of them is MH.

**Comment by Dilshat** [comment]
Fixed
