### ISSUE TITLE
Graph metrics completely wrong

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/base#1641]
Below you will see 6, 12, 24, and 48 hour snapshots of the same graph's peeks. All the numbers are changing and completely off. Something is terribly wrong and needs to be fixed immediately.

Here it shows 1.4 Mbps:

![screen shot 2016-12-24 at 8 56 00 pm](https://cloud.githubusercontent.com/assets/10051386/21468479/d60f2950-ca1b-11e6-85f7-be158e384fbf.png)

Here it shows 1.4 Mbps:

![screen shot 2016-12-24 at 8 56 16 pm](https://cloud.githubusercontent.com/assets/10051386/21468480/db1e3a80-ca1b-11e6-84d5-759f2e8d4ed6.png)

Here it shows 50 Mbps:

![screen shot 2016-12-24 at 8 56 36 pm](https://cloud.githubusercontent.com/assets/10051386/21468481/defd0ec4-ca1b-11e6-88c2-2dcdf81ffb13.png)

Here it shows 3.4 Mbps:

![screen shot 2016-12-24 at 8 56 52 pm](https://cloud.githubusercontent.com/assets/10051386/21468483/e1acccfe-ca1b-11e6-9fea-2609e7527332.png)

Which is right?

**Comment by Dilshat** [comment]
@soffokl can you check this case please

**Comment by soffokl** [comment]
@Dilshat On all screenshots points checked in different time. 
You want to have same values in different moments? 
I do not see problem here

**Comment by Dilshat** [comment]
@akarasulu can you clarify your complaint please

**Comment by Dilshat** [comment]
p1gmale0n [3:54 PM] 
i think, the point is that max value of y-axis is not permanent..
GitHub
Graph metrics completely wrong · Issue #1641 · subutai-io/base
Below you will see 6, 12, 24, and 48 hour snapshots of the same graph's peeks. All the numbers are changing and completely off. Something is terribly wrong and needs to be fixed immediately. Here i...
 

dima [3:55 PM] 
it's ok for network graph

dilshat [4:02 PM] 
on the last two screens we see time *21:00* and *21:20* whereas `eth0/wan` traffic has big difference 50 vs 2-3

dima [4:04 PM] 
on the last screenshot time range is bigger and points aggregated
looks like at 21:00 was just a peak value (edited)

dilshat
[4:04 PM] 
hmm ok

**Comment by Dilshat** [comment]
closing for now
