### ISSUE TITLE
If a specific custom name is assigned to a container please use this for the container hostname instead of appending extra information as a suffix

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/base#1642]
I created an environment and gave specific names to the containers like mysql, confluence, etc. But when the system creates these containers it appends a suffix to their hostnames like: mysql-100-4. 

Let's: 

* Adding the extra suffix only when a specific name is not provided
* Do not add suffix when a specific name is provided as both the name of the container and it's hostname.

**Comment by Dilshat** [comment]
I dont think this is right.
Container names are set on Hub or initiator peer. During speed optimization of environment creation process we saw that there can be parallel environment build processes that could try to use the same name. Attempt to reserve such names resulted in an additional reservation step that could also result in a third roundtrip if a name was already reserved. This resulted in a big latency during environment creation.
Finally, we came to the simplest and fastest solution about using suffixes.
Suffix contains a vlan, which makes a name unique on the same peer. Suffix also contains container IP's last octet which makes the name unique within the host environment. So, if two users want to use name Container1 on the same peer, the suffix makes this possible avoiding name clash at the same time.
Also if user purposefully sets the same name for several containers within the same environment, the last IP octet makes this feasible too.
Additionally, both Hub and SS UI don't show container names suffixes. They show them in tooltips or on some detailed information dialogs. 
Moreover, implementing this requirement would require a lot of changes both on Hub and SS sides and thus a long time, and considering a small benefit of this effort, I think we should cancel this issue.

**Comment by akarasulu** [comment]
I'm not talking about the name to give the container on the filesystem or elsewhere in networking ... I'm talking about the environment specific hostname which is mapped into /etc/hosts and /etc/hostname. This can be easily implemented just for hostname while leaving the other aspects as is.

**Comment by akarasulu** [comment]
There's no need to expose this implementation detail in the hostname. You're not showing these names with suffixes on the console for example.

**Comment by akarasulu** [comment]
So the Hub is showing this as the name of the container:

![screen shot 2016-12-25 at 4 21 37 pm](https://cloud.githubusercontent.com/assets/10051386/21471515/4d24b99a-cabe-11e6-9adc-2d7d3d8aaab3.png)

The SS console is showing something else:

![screen shot 2016-12-25 at 4 22 45 pm](https://cloud.githubusercontent.com/assets/10051386/21471521/69ef108e-cabe-11e6-9b37-fc0a8cf9fa50.png)

And the /etc/hosts files are showing this for hostnames:

> root@nginx-us-100-12:~# cat /etc/hosts
172.29.123.247	gw.intra.lan
172.29.123.8 galera-us-100-8.intra.lan galera-us-100-8
172.29.123.4 mysql-tr-100-4.intra.lan mysql-tr-100-4
172.29.123.3 mysql-us-100-3.intra.lan mysql-us-100-3
172.29.123.9 galera-tr-100-9.intra.lan galera-tr-100-9
172.29.123.6 appscale-us-100-6.intra.lan appscale-us-100-6
172.29.123.14 galera-us-100-14.intra.lan galera-us-100-14
172.29.123.13 nginx-tr-100-13.intra.lan nginx-tr-100-13
172.29.123.16 foobar-100-16.intra.lan foobar-100-16
172.29.123.7 appscale-tr-100-7.intra.lan appscale-tr-100-7
172.29.123.12 nginx-us-100-12.intra.lan nginx-us-100-12
172.29.123.11 zabbix-us-100-11.intra.lan zabbix-us-100-11
172.29.123.5 confluence-us-100-5.intra.lan confluence-us-100-5
172.29.123.10 wordpress-us-100-10.intra.lan wordpress-us-100-10
172.29.123.15 galera-tr-100-15.intra.lan galera-tr-100-15
127.0.0.1 localhost 

There's absolutely no reason why hostnames in /etc/hosts and /etc/hostname cannot use the short name specified by the user while SS console shows the short names too. Again the other internals can use the suffix. Makes sense ?

**Comment by Dilshat** [comment]
We can fix the UI display of hostnames in SS (seems some bug b/c it should have shown name without suffix). As about hostnames, yes this makes sense, we can omit suffix for them (as log as we dont omit if for container names).
We need an update of CLI to be able to set diff hostname in addition to container name, e.g:
subutai clone master foo-100-1 -h foo

**Comment by akarasulu** [comment]
Coolio. It will be nice to not see weird stuff like that and to have consistency NOT to mention easy names to reference when doing some setups especially with devops later on. Putting in the suffix was adding some additional pain to users.

**Comment by Dilshat** [comment]
Related https://github.com/subutai-io/base/issues/1626

**Comment by Dilshat** [comment]
Done
