### ISSUE TITLE
[Environments - > Templates -> Choose one-> Click the Plus icon on the chosen template] A typo 

### ISSUE THREAD

**Issue by akylbekesenaliev** [subutai-io/base#1645]
[Environments - > Templates -> Choose one-> Click the Plus icon on the chosen template -> result: A typo
![image](https://cloud.githubusercontent.com/assets/17665678/21498279/44cb519e-cc55-11e6-9068-3514057f1bc1.png)
It should say : Mb and GB
because there is such a unit called MiB

**Comment by Dilshat** [comment]
Also we need to change Container name to Container hostname

**Comment by Dilshat** [comment]
![image](https://cloud.githubusercontent.com/assets/3367326/21502232/a2862eda-cc78-11e6-931a-f699bf231d57.png)
here too

**Comment by Dilshat** [comment]
![image](https://cloud.githubusercontent.com/assets/3367326/21502509/8526a098-cc7a-11e6-977d-1528a3fa0a6f.png)

**Comment by Dilshat** [comment]
Done
