### ISSUE TITLE
Cleanup x-peer metadata

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/base#1651]
When a container is destroyed on a remote peer manually. the env metadata on that peer should be cleaned up too

**Comment by akarasulu** [comment]
@Dilshat please also document this maze of peer metadata management on the wiki for reference. It's getting so complex now I would like to think about strategies to refine it however I first need some background on how cross peer metadata management is taking place.

**Comment by Dilshat** [comment]
Done
