### ISSUE TITLE
[System Settings] [UX] No reason to use two separate tabs for updates and history

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/base#1661]
There is no reason why the update availability check with update button cannot be on the same tab with the previous update history. Right now this requires two operations by the user while waiting. When users land on the menu item for "System Settings"-->"Updates" users have to wait until the check occurs to even see the update history. If both were together on a single tab then that would save the user time and another click.

Also you should not initiate a check for updates right away. The user should press a check for updates button. If the update is present there should be information about the new update provided. This information is good for the user to make a decision about whether or not they want to upgrade. Then the user can either abandon upgrading or proceed to press an upgrade button to continue to upgrade.

**Comment by Dilshat** [comment]
Done
