### ISSUE TITLE
Make the popup error message more digestible for the users - `Same environment name error`

### ISSUE THREAD

**Issue by akylbekesenaliev** [subutai-io/base#1666]
![image](https://cloud.githubusercontent.com/assets/17665678/21881954/a15436fe-d8d2-11e6-841f-083c408367b0.png)
When I create environments from SS and use same names for my environments I am getting `internal error` message I think we need to make this part a little bit more digestible because users might not understand the failure reason and this might affect us in a bad way - meaning negative user satisfaction,so I suggest to change the popup message to something like : `This environment name is already in use` 
![image](https://cloud.githubusercontent.com/assets/17665678/21882089/2845cda8-d8d3-11e6-961e-e5da74dd56e7.png)

**Comment by Dilshat** [comment]
![image](https://cloud.githubusercontent.com/assets/3367326/21890377/a1d79718-d8f7-11e6-9644-8085bb6a870a.png)

**Comment by Dilshat** [comment]
Advanced mode:
![image](https://cloud.githubusercontent.com/assets/3367326/21890399/bdd52d7c-d8f7-11e6-81ac-d6a456541d67.png)

**Comment by Dilshat** [comment]
Can not reproduce

**Comment by Dilshat** [comment]
Fixed
