### ISSUE TITLE
An unclear error message  - when destroy environment item is clicked twice

### ISSUE THREAD

**Issue by akylbekesenaliev** [subutai-io/base#1667]
![image](https://cloud.githubusercontent.com/assets/17665678/21884787/ed49658c-d8de-11e6-99da-d6a57eebf3db.png)
When I destroy environments from SS I get this message `Your environment is being deleted` which is good, but if I click the same destroy item right after clicking it the first time I am getting  this ^^ unclear error message that says `Your environment is safe` so I suggest to make this easier to consume for the users and replace this message - `Your environment is safe`  to something like : 
`This environment is already in deleting progress `
To play this go to: 
1. Environments 
2. Create environment 
3. Click the Destroy environment item 
4. Right after, click the Destroy environment again 
result : 
An error message pops up saying - `Your environment is safe`

**Comment by Dilshat** [comment]
Done
