### ISSUE TITLE
Can not execute command with agent on management container

### ISSUE THREAD

**Issue by eabyshev** [subutai-io/base#167]
I tried to execute /opt/subutai-mng/bin/update-management --check on management container from system-manager module. 
Agent does not give response after executing command on management container:

```
2016-03-05 18:19:32,138 | INFO  | qtp562559869-212 | CommandProcessor                 | 199 - io.subutai.core.executor.impl - 4.0.0.RC7-SNAPSHOT | Sending:
{
  "request": {
    "type": "EXECUTE_REQUEST",
    "id": "",
    "commandId": "fcbe2b4e-c924-4606-b8bc-a0bacdee912d",
    "workingDirectory": "/",
    "command": "/opt/subutai-mng/bin/update-management --check",
    "stdOut": "RETURN",
    "stdErr": "RETURN",
    "runAs": "root",
    "timeout": 30,
    "isDaemon": 0,
    "pid": 0
  }
}
```
How to reproduce:
1) to execute command in karaf console:

```
localpeer:check-update-management
```

Tried execute command on management container manually on terminal, it is works fine

**Comment by akarasulu** [comment]
This is a pathetic bug report. How about some details?
