### ISSUE TITLE
User must be able to create a template from an existing container

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/base#1671]
We need to add functionality to enable creation of templates from existing containers via UI.

**Comment by Dilshat** [comment]
Need to have a switch to keep container alive, and get template in addition to container, so that promote does not remove the container.

**Comment by Dilshat** [comment]
Seems to solve problem with user's hub account, we might allow this option only for hub environments. Wdyt @akarasulu?

**Comment by akarasulu** [comment]
We still need to handle hub-less operation and generating templates is a must have. Without that you lose a lot of productivity. What's the problem there's no easy way to handle hub less users?

**Comment by Dilshat** [comment]
There is no value, b/c even promoted and exported templates are not accessible in local Kurjun, they must be uploaded to Hub to be accessible in SS UI (SS UI shows templates from local Kurjun list).
So only admin would be able to use them manually using subutai CLI

**Comment by akarasulu** [comment]
> There is no value, b/c even promoted and exported templates are not accessible in local Kurjun, 

This is a technical shortcoming that prevents SS UI from seeing it. We should find a way to rectify it. Here the cache is the peer. The container template is present on a resource host. The SS UI should be able to offer this promoted template to the user to create new containers with it on any RH of the peer.

When I talk about value, I'm talking about `value`, I mean to the user. Ultimately we have to design the system for usability and if there are flaws in the implementation we have to fix it. Can't just sit there and say there's no value because the system cannot do X and Y. We must find a way.

> they must be uploaded to Hub to be accessible in SS UI (SS UI shows templates from local Kurjun list). So only admin would be able to use them manually using subutai CLI

This is totally unacceptable for the user experience. Then there's no point to the SS UI.

Please find a way to have the SS UI be aware of promoted templates on the resource hosts of the peer and display them as private templates (use a special icon overlay for private templates) available to the user for local use on his peer. Promote and export is all that is need for this.

If he user is a hub user, they should also have a way in the UI to publish or push (modes: public, shared, private) to their kurjun repository. Publish adds the template to the global kurjun repository. Push goes into their personal and can be access controlled as we have it setup.

**Comment by Dilshat** [comment]
The problem is that there can be several RHs with diff local templates.
Until a template is published/pushed to Global Kurjun, it can not be cloned on an RH that does not have it, even if its neighbour RH within the same peer has it.
So we can not make it visible in Environment Builder. User must publish it and then only we can clone it on any RH. 
Another moment about environment containers:
A container can reside on any peer, it can be on a remote one,and even if we somehow make it visible, it will be physically on a remote peer, not accessible for local Gorjun or subutia cli.
So there are 2 options:
1) We add new subutai CLI command to promote and publish to Global Kurjun at once. So these 2 operations are not separate but in an atomic transaction. This would allow then to automatically see and use this template from any other RH/peer.
2) Or we allow user to manipulate containers on local RHs only and promote them to templates. This way we can register them with local Gorjun and make visible in SS UI without mandatory push to Global Gorjun. That means, user can promote container to templates in the context of a single peer where container resides physically. The template will get uploaded to MH RH and be accessible to other RHs in this peer. Later user can publish template to global Gorjun and make it visible to other peers.

**Comment by akarasulu** [comment]
> The problem is that there can be several RHs with diff local templates.

Sure. Know it.

> Until a template is published/pushed to Global Kurjun, it can not be cloned on an RH that does not have it, even if its neighbour RH within the same peer does have it.

This is a technical limitation. There's nothing preventing us from fixing this.

> So we can not make it visible in Environment Builder. User must publish it and then only we can clone it on any RH.

Again this is a limitation of the current implementation which overlooked some very important use cases. 

### The Use Case

It's very natural for a user to "work" on a container, convert it to a template, and re-use it to clone more containers. They should not have to publish it to a global repository to use it. What if it contains private stuff they don't want to expose it? What if the peer is not connected to the Internet? What if the user does not trust the Hub? These are all natural and legitimate concerns. The need is a real one. 

### The Fix

This is just an idea. Let me know what you think.

1. We can create a very simple template manager/tracker component for SS. Promotions register private templates created by promotions and keep template metadata like local user ownership and state.
2. Remove the CLI export command, merge its functionality into promote, always export into the tmpdir
3. NGINX runs on each RH, and serves the contents of tmpdir 
4. The peer's local Kurjun (on the MH?) can unify all these RH views into a single merged view:
  - SS's env creator can see all the templates from global and internal
  - SS's env creator filters private container templates: logged in user must equal template owner
  - SS's env creator displays private containers owned by user with some graphic overlay to signify they're private (i.e. closed lock in lower right of the icon). 
5. A template management UI area on SS lists local templates based on owner and logged in user. We allow users to delete, push and publish local templates. Once pushed or published the template is ignored to prevent being listed twice.
6. X-peer environments with or without the Hub should be able to access each others' local Kurjun repositories to transfer private templates and use them across peers and resource hosts just as they do public templates.

**Comment by Dilshat** [comment]
>  and keep template metadata like local user ownership
This would work if template is promoted from SS, if template is promoted manually (using subutai CLI) then no owner information will be there
>The peer's local Kurjun (on the MH?) merges all RH views of private templates into a single merged view:
This question is more to @soffokl , if local Gorjun can be made to get templates from RH nginx'es and expose them to SS. But again SS can filter templates based on owner, if it is present at all. Currently ownership is kept outside of template metadata, on Global Gorjun/Hub.

> X-peer environments with or without the Hub should be able to access each others' local Kurjun 
@soffokl please comment

>The only thing I do not know is if the env creator lists private templates kept in private kurjuns on the Hub? 
Currently we dont use private templates that are not published on Hub Gorjun

**Comment by soffokl** [comment]
Current local kurjun store nothing, it only proxies requests to the global server.

**Comment by akarasulu** [comment]
> >  and keep template metadata like local user ownership

> This would work if template is promoted from SS, if template is promoted manually (using subutai CLI) then no owner information will be there

We need to have subutai CLI announce all activities to SS to keep SS data synchronized with the state of the system. This should have been done before. In fact I thought this was already being done. If we don't do this then nothing is going to stay consistent.

> > The peer's local Kurjun (on the MH?) merges all RH views of private templates into a single merged view:

> > This question is more to @soffokl , if local Gorjun can be made to get templates from RH nginx'es and expose them to SS. But again SS can filter templates based on owner, if it is present at all. Currently ownership is kept outside of template metadata, on Global Gorjun/Hub.

Yes @soffokl it was more a question for you. You're response was:

> Current local kurjun store nothing, it only proxies requests to the global server.

Right it will still store nothing and proxy content. But this time from local RHs as well as Hub Gorjun. It will merge things together.

> > X-peer environments with or without the Hub should be able to access each others' local Kurjun 

> @soffokl please comment

@soffokl Can we proxy from multiple x-peer Kurjuns?

I think this starts to get inefficient perhaps. 

> > The only thing I do not know is if the env creator lists private templates kept in private kurjuns on the Hub? 

> Currently we dont use templates that are not published on Hub Gorjun

Yes it seems we left off many features that were supposed to be in Kurjun right after getting to Gorjun. I guess we were so happy to not die with Kurjun we forgot. I think we need a good specification on this matter.

**Comment by soffokl** [comment]
> Right it will still store nothing and proxy content. But this time from local RHs as well as Hub Gorjun. It will merge things together.

RH does not allow to download template. To proxy request it should support downloading. We can't just point local Gorjun to RH, because RH does not provide this functionality. 

> Yes it seems we left off many features that were supposed to be in Kurjun right after getting to Gorjun. I guess we were so happy to not die with Kurjun we forgot. I think we need a good specification on this matter for the long term.

Yeah, It was because we had "enough for demo", and there were higher priority requirements. All these were panned to implement when everything became better. We are still waiting this.

**Comment by akarasulu** [comment]
> > Right it will still store nothing and proxy content. But this time from local RHs as well as Hub Gorjun. It will merge things together.

> RH does not allow to download template. To proxy request it should support downloading. We can't just point local Gorjun to RH, because RH does not provide this functionality. 

How hard is it to have NGINX expose those /tmpdir files to the local Gorjun?

> > Yes it seems we left off many features that were supposed to be in Kurjun right after getting to Gorjun. I guess we were so happy to not die with Kurjun we forgot. I think we need a good specification on this matter for the long term.

> Yeah, It was because we had "enough for demo", and there were higher priority requirements. All these were panned to implement when everything became better. We are still waiting this.

Let's focus on doing this the right way now. That's why we're having these discussions. Obviously we're going to need to expose local templates from RH's. We can have NGINX on the RH serve these from some URI like /templates so local Gorjun can add them to the list. Also other RH's without the local template can pull the template when needed.

WDYT?

**Comment by Dilshat** [comment]
Done
