### ISSUE TITLE
Disk, RAM, Net, and CPU adjustments on containers

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/base#1674]
Sometimes users need to increase the amount of disk, RAM, and CPU quotas for a container. We should allow them to do so from the SS console but I'm not seeing this capability.

**Comment by Dilshat** [comment]
Is changing container size not enough, @akarasulu?

**Comment by akarasulu** [comment]
You mean changing the size to a preset size? We also have to be able to fluidly change the quotas on all the dimensions. This includes Disk, RAM, CPU, and network.

**Comment by Dilshat** [comment]
Blocked by https://github.com/subutai-io/base/issues/1678

**Comment by samsonbek** [comment]
Is this feature is allowed to all users of peer? If so, what about prices? What if user rented peer, with some price, and then increased quota values to maximum capacity?

**Comment by Dilshat** [comment]
The issue will be handled in the cours of #1733
