### ISSUE TITLE
Login UI getting confused

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/base#1675]
![screenshot1](https://cloud.githubusercontent.com/assets/10051386/21962326/d7353f6a-db2b-11e6-8a59-095c1baad33d.png)

UI is showing me normal login, but thinking I am updating my password. I am entering 'secret' and it is giving message above.

**Comment by Dilshat** [comment]
Can not reproduce, please reopen with a concrete set of steps

**Comment by akarasulu** [comment]
I have no idea what is going on with my browser. This is still happening to me now constantly and I cannot get in at all. Maybe we can trouble shoot this on my desktop. It's not like this is a workflow of steps here. You just login and it's borked.

**Comment by akarasulu** [comment]
I think this is a problem with my password manager :(. Just turned it off and the problem goes away. Weird.
