### ISSUE TITLE
New column in table for IP of the RH in the Resource Hosts View

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/base#1676]
![selection_017-thumb](https://cloud.githubusercontent.com/assets/10051386/21963691/aa039a16-db47-11e6-9b40-4264eb6d91dd.png)

Would be nice to have an IP address column here. The RH names are useless.

**Comment by Dilshat** [comment]
Done

**Comment by akarasulu** [comment]
I guess you mean LAN IP right @Dilshat ?

**Comment by Dilshat** [comment]
i mean IP from interface **wan**
