### ISSUE TITLE
Allow users to change the names and hostnames of resource hosts

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/base#1677]
The following table clearly shows how useless these computer generated names are. I cannot tell which resource host corresponds to which machine I have on the network.

![selection_017-thumb](https://cloud.githubusercontent.com/assets/10051386/21963675/6c78fc68-db47-11e6-9168-e3500eb2fe5a.png)

Users need a means to change the names of resource hosts. Also I don't understand why we're exposing these nasty names with `gw.intra.lan` etc. Please make it so the computer generated names do not include the internal fully qualified domain name.

**Comment by Dilshat** [comment]
Done
