### ISSUE TITLE
Failed to create env: failed to reserve network resources

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/base#1684]
Got this twice when trying to build an environment:

1. tried with env on main rh
2. tried with env on two rh

> 23:44:15		Logger initialized
23:44:18		Initializing environment creation
23:44:18		Securing channel
23:44:22		PEK generation succeeded on Local Peer
23:44:22		Reserving network resources
23:44:23		Failed to obtain reserved network resources from peer Local Peer. Reason: io.subutai.common.peer.PeerException: Error gathering reserved net resources on host A626F93CFB34F9B181EEC1CFA3F0CC4AC333DB35: Failed to get tunnels: io.subutai.common.command.CommandException: io.subutai.core.hostregistry.api.HostDisconnectedException: Host A626F93CFB34F9B181EEC1CFA3F0CC4AC333DB35 is not connected
23:44:23		Failed to obtain reserved network resources from all peers

Karaf logs:

[karaflogs2017-01-17 23-44-51.txt](https://github.com/subutai-io/base/files/712285/karaflogs2017-01-17.23-44-51.txt)

Everything is up to date and here's the version information:

![selection_016-thumb](https://cloud.githubusercontent.com/assets/10051386/22039248/3b2e7b3a-dd07-11e6-82ce-0f46963748e6.png)

**Comment by akarasulu** [comment]
Just in case I tried from the Hub on this peer and this is what I got:

ERROR. Preparing initial data. io.subutai.core.hubmanager.api.exception.HubManagerException: io.subutai.common.peer.PeerException: Error gathering reserved net resources on host A626F93CFB34F9B181EEC1CFA3F0CC4AC333DB35: Failed to get tunnels: io.subutai.common.command.CommandException: io.subutai.core.hostregistry.api.HostDisconnectedException: Host A626F93CFB34F9B181EEC1CFA3F0CC4AC333DB35 is not connected

**Comment by akarasulu** [comment]
STOP don't waste time here. I need to test more.

I just installed a new vbox peer. Forgot to mention this was a KVM based peer. It worked fine with vbox. I will try to do this with a fresh KVM peer and see what happens.

**Comment by Dilshat** [comment]
ok

**Comment by akarasulu** [comment]
This is obviously something really wrong with a peer I have on KVM. Let's close this up and calk it up to user error.
