### ISSUE TITLE
Tips on timeout and daemon.

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/base#172]
For replay this improvement you need:

Test case
1) Go to Subutai server and login under any account.
2) Go to 'Console' page.
Result: We see timeout and daemon features, but user may not know what does that mean. 
Recommendation: we need to have tips on them.

**Comment by larenso** [comment]
duplicate issues: https://github.com/subutai-io/base/issues/199

**Comment by NikolaiB** [comment]
Tested.
