### ISSUE TITLE
Errors when running subutai from unprivileged user

### ISSUE THREAD

**Issue by crioto** [subutai-io/base#173]
When running subutai command on behalf on unprivileged user I can see huge error dump in output, instead of one line message about requirements of root privileges. 
I've noticed this when was running the following commands:
```
subutai list -i
subutai start management
```

**Comment by tzununbekov** [comment]
User check added:
https://github.com/subutai-io/base/commit/1b93cf9e1ece6ff44772b1c0c5131748a7c7305a
