### ISSUE TITLE
Environment disappeared from SS

### ISSUE THREAD

**Issue by soffokl** [subutai-io/base#1735]
Environment disappeared from SS, but on RH containers still exists:
[karaflogs2017-02-17 14-17-12.txt](https://github.com/subutai-io/base/files/782618/karaflogs2017-02-17.14-17-12.txt)

![image](https://cloud.githubusercontent.com/assets/8612618/23057792/fa3af5b8-f51b-11e6-9bda-f8b4546a33d3.png)

**Comment by Dilshat** [comment]
Fixed
