### ISSUE TITLE
[Environments - Templates - Hover over] Normally display template sizes 

### ISSUE THREAD

**Issue by akylbekesenaliev** [subutai-io/base#1772]
![image](https://cloud.githubusercontent.com/assets/17665678/23697473/204f8f7a-0412-11e7-98c6-964d1ea681d6.png)
To play the enhancement go to: 
1. Environments
2.Templates
3.Hover over any template 
Result: 
An info line displayed with *size* looking kinda creepy/confusing I think we need to display it normally so users wont have to calculate/digest this.

**Comment by Dilshat** [comment]
done
