### ISSUE TITLE
[Environment] Takes TOO MUCH time to load templates.

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/base#178]
For replay this bug you need:

Test case:
1) Go to SS and login under any account.
2) Go to Environment page.

Result: You can't observe templates. It takes  from 5-10 sec to load them it's too much. If I renew the page or move back and forth from pages it starts to load them again.

Improvement: Improve the speed and add an indicator which will show the user that templates are running.

Commit ID 	c6e4298fc70899290b0789ec8126019b398b6b51

**Comment by Dilshat** [comment]
This is related to Kurjun, works are being done in new Kurjun. The indicator is related to UI.

**Comment by larenso** [comment]
Were changes in kurjun, and I saw improvement, consider fixed
