### ISSUE TITLE
Implement ansible configuration heartbeat processor

### ISSUE THREAD

**Issue by tjamakeev** [subutai-io/base#1802]
We need to implement additional environment workflow step that relies on heartbeat protocol and command DTOs exchange.
New step should pass a new DTO from Hub to SS that contains the following data:

1. type of change: new cluster formation, cluster growing, cluster shrinking, cluster destruction
2. ansible playbook path - to execute (this is taken from blueprint)
3. ansible template id - to use for ansible container
4. additional parameters needed for a concrete type of change: e.g. IDs of containers to remove, IDs of new containers etc. that would enable the playbook to perform the required action

**Comment by Dilshat** [comment]
Related to https://github.com/optdyn/hub/issues/2991
