### ISSUE TITLE
Sorting environments does not work properly 

### ISSUE THREAD

**Issue by soffokl** [subutai-io/base#1803]
![image](https://cloud.githubusercontent.com/assets/8612618/24785912/484aebee-1b7f-11e7-986a-456a106a10d8.png)

**Comment by soffokl** [comment]
There is another irritating behavior of sorting, it resets on automatic page refresh. 
If you choosing sort by name, after few seconds page refresh automatically and resets sorting to first column.

**Comment by Dilshat** [comment]
Done
