### ISSUE TITLE
[UI][Environment] Containers spinner synchronization while stopping containers.

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/base#183]
For replay this bug you need:

Test case
1) Go to SS and login under any account.
2) Go to Environment page and create an environment with few templates.
3) Go to Containers page and press the stop button on containers.

Result: the button turns into a spinner showing that it is stopping, then the spinner turns back into a button but is still a stop button. After a short while the page refreshes to show the button has turned into a “start” button. As far as I can tell we are not synchronizing the spinner to confirm the actual stopping of the container. The spinner is not really giving direct feedback but is probably set to some time. The same problem is not occurring when starting.

See the following attached screen video capture of this bug:

https://www.youtube.com/watch?v=lKa-BhRQ5yI

**Comment by larenso** [comment]
fixed
