### ISSUE TITLE
[IU] [Monitoring] "NO DATA" for disk graph for CH statistics on environment tab

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/base#184]
On the monitoring screen after some time of operation some graphs can disappear. This occurs both when viewing RH statistics or when CH statistics. A restart seems to fix this problem for the RH but not for CH statistics in Monitoring screen's environment tab.

<img width="1165" alt="screen shot 2016-03-07 at 9 03 49 pm" src="https://cloud.githubusercontent.com/assets/10051386/13579917/8b334ba4-e4a8-11e5-9e0b-97452c0d7a64.png">

**Comment by larenso** [comment]
tested this issue, sometimes data we recieve is empty for disks or network, or both

**Comment by akarasulu** [comment]
I never saw anything with the other graphs @larenso just disk. However if you did please let @soffokl consider it.
