### ISSUE TITLE
[UI] [Logs] Log file should show from the bottom and nice if it can also tail the log file.

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/base#185]
For replay this improvement you need:

Test case
1) Go to SS and login under any account.
2) Go to System Settings -> Advanced -> Logs.

Improvement: The log file text display area is always displaying the top of the file which could be days old. Scrolling all the way to the end is a PITA every time. How about starting off with display text at the bottom of the file. Would also be nice to have the following features:
- colourized logs with exceptions in **RED**
- tail the log file and actively view logs as they come in
- size control that shows red ticks for exceptions in the log

**Comment by NikolaiB** [comment]
Tested.
