### ISSUE TITLE
Make SS use `info` CLI command to obtain its default public URL

### ISSUE THREAD

**Issue by tzununbekov** [subutai-io/base#1853]
Current SS logic of detecting public URL sometimes sets localhost address whereas `subutai info ipaddr` output and wan interface in heartbeat contains another value. It would be easier and more correct to use dedicated `info` CLI command to determine default URL value.

**Comment by Dilshat** [comment]
Implemented for now this way.
However I think we should have agent figure out and send RH IP in heartbeat to avoid round trips from SS to agent to get this info.
