### ISSUE TITLE
Wrong message in environment table

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/base#1863]
Sometimes environment table shows incorrect `Loading` message when there are no  environments

![image](https://user-images.githubusercontent.com/3367326/26917429-128ff9b6-4c50-11e7-8085-e3de8cd9777f.png)

**Comment by samsonbek** [comment]
Sometimes having this:
![image](https://user-images.githubusercontent.com/4163679/27819200-ebddff6e-60ba-11e7-9f5e-23fb79386f11.png)
