### ISSUE TITLE
[UI] [Advanced] Karaf Console's web UI is not visible.

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/base#187]
For replay this bug you need:

Test case
1) Go to SS and login under any account.
2) Go to "System Settings"->"Advanced" page.

Result: It shows the CLI console, there still is no way to get into Karaf's UI based console.

**Comment by larenso** [comment]
related issue: https://github.com/subutai-io/base/issues/188

**Comment by Dilshat** [comment]
Fixed
