### ISSUE TITLE
Non admin user does not see Hub environments

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/base#1871]
Currently non admin users dont see own environments on SS UI.
This is because Hub created delegate user for real Hub user on SS.
That means that non admin users on Hub and SS do not match.
However we can show non admin user environments to owners by checking this relation either on Hub side or SS side (hub module).

**Comment by zubaidullo** [comment]
Can you give more info please about problem. 
> That means that non admin users on Hub and SS do not match.

**Comment by Dilshat** [comment]
Hub creates a delegate user as environment owner if user is not a peer owner at the same time.
This means there is an auto-created user that acts as a delegate user for real user. So even if there is an SS user that has the same PGP key as Hub user, but which is not peer owner, then for him there will be a delegate user on SS acting as environment owner. This leads to the problem of environment non visibility.

**Comment by Dilshat** [comment]
@zubaidullo for now seems the implementation is satisfactory however Hub should "memorize" that it has created a particular delegate user for particular real user.
This would be an additional security measure. Also lets review the current mechanism to figure out ways to implement more secure way of showing SS user his Hub env-s

**Comment by zubaidullo** [comment]
+1 for **Hub should memorize user info**. 
- Because, in current implementation SS requests to get delegate user's environments with **user ID**, which is not secure way (there is security only between Hub and SS). 
- If Hub will memorize and check if it has created delegate user on SS side, this will create one step security for this process. Because as you mentioned, SS admin have option to create fake delegate user.

**Comment by Dilshat** [comment]
@zubaidullo  I created this issue for now https://github.com/optdyn/hub/issues/3167.
as about the rest of the discussion, currenty there is no real use case for the option to show non admin SS users their Hub environments via SS UI since they can access them and see them on SS coming from Hub via Open Console functionality. So closing
