### ISSUE TITLE
Loading of "Remote peers" page is very slow, if some of registered peers are offline

### ISSUE THREAD

**Issue by samsonbek** [subutai-io/base#1875]
I have connected 2 peers to my peer via "Remove peers" feature. After some time this 2 peers were shutdown. When I open "Remote peers" page of my peer, it loads very slow, takes almost 15-20 seconds.
I think this page should load without checking if remote peer is available, then after page load state of remote peers must be checked via asynchronous request. As an example. you may look at cloud peers list on Hub.

**Comment by Dilshat** [comment]
Done
