### ISSUE TITLE
[UI] [Advanced] Karaf console authentication is different and preserved across SS authentications.

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/base#188]
For replay this bug you need:

Test case
1) Go to SS and login under any account.
2) Go to "System Settings"->"Advanced"->"Console" page.

Result: When landing for the first time there the user is presented with a HTTP domain based authentication window:
<img width="998" alt="screen shot 2016-03-07 at 9 31 41 pm" src="https://cloud.githubusercontent.com/assets/10051386/13580727/1fb28cc4-e4ac-11e5-8fc4-ab5509272c1f.png">

This authentication method needs to go away. The user authenticating into SS and having the permissions to access this console should be enough. The authentication not be integrated with SS security is creating issues for us like:
- usability with a second log in when not required
- when you log back out and log back in as another user it still seems to be available (security issue here)

**Comment by larenso** [comment]
related issue: https://github.com/subutai-io/base/issues/187

**Comment by Dilshat** [comment]
Fixed
