### ISSUE TITLE
[UI] [Monitoring] Too many values impacts usability.

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/base#189]
For replay this improvement you need:

Test case
1) Go to SS and login under any account.
2) Go to Monitoring page.

Improvement: On the Monitoring graphs (i.e. disk) usability is impacted by excessive values. The popup displayed is out of control. Let's condense some of the values into rows where it makes sense. For example here:
<img width="583" alt="screen shot 2016-03-07 at 9 36 26 pm" src="https://cloud.githubusercontent.com/assets/10051386/13580928/12f6c058-e4ad-11e5-89af-84c1453c6af0.png">

On this popup let's condense the "avialable", "used" and "total" metrics in a nice way onto a single row instead of have each one of these on its own row.

**Comment by NikolaiB** [comment]
Tested.
