### ISSUE TITLE
"Remote peers" list doesn't refresh after submitted action

### ISSUE THREAD

**Issue by samsonbek** [subutai-io/base#1898]
How to reproduce:
1. Open "Remote peers" page
2. Create request to remote peer. After you submit this request, remote peers list not updated, you can't see your request until manually refresh this list
3. On another peer, to which you created request, open "Remote peers" page, you have to see request there.
4. Click to "Approve" on request. After you clicked list again not reloaded. Request state is not changed, until you update page manually.

**Comment by samsonbek** [comment]
After "Unregister" remote peer, list also not updated.

**Comment by absidish** [comment]
1) After create request to register peer I see it on list.
2) [ minor bug ] After click approve button on second peer request didn`t change status to approved so user can click approve button again.
3) [ minor bug ] After unregister I see popup that peer unregistered, but  it still on list, after update page manually it gone.
[video_rec.zip](https://github.com/subutai-io/base/files/1141771/video_rec.zip)
