### ISSUE TITLE
[UI] [Monitoring] Selector has unnecessary empty option with check in it.

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/base#190]
For replay this bug you need:

Test case
1) Go to SS and login under any account.
2) Go to Environment and create simple environment.
3) Go to Monitoring -> Environment tab.
4) In selector chose the name of created environment -> click on appeared selector with empty name.  

Result: You can observe that the first row is empty.

<img width="851" alt="screen shot 2016-03-07 at 9 42 19 pm" src="https://cloud.githubusercontent.com/assets/10051386/13581048/a60c1dca-e4ad-11e5-8b39-876d302107b1.png">

**Comment by NikolaiB** [comment]
Tested.
