### ISSUE TITLE
SS environment not uploaded to hub after temporary Hub outage

### ISSUE THREAD

**Issue by samsonbek** [subutai-io/base#1917]
How to reproduce:
1. Register peer to Hub (if not already registered)
2. Shutdown Hub or cut network or shutdown wi-fi router or write wrong Hub IP addr. in management /etc/hosts (anything to make Hub unreachable from SS management)
3. Create environment on SS console
4. Wait 4-5 minutes
6. Restore connection to Hub (make it available to SS management)
Result: after peer sent several heartbeats to Hub, environment still wasn't uploaded to Hub.

**Comment by Dilshat** [comment]
The upload interval was too big - 30 minutes
decreased it to 10 min
however during work on this issue found another one: https://github.com/subutai-io/base/issues/1932
