### ISSUE TITLE
[UI] [Containers] Add autostart checkbox.

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/base#192]
For replay this improvement you need:

Test case
1) Go to SS and login under any account.
2) Go to Containers page.

Improvement: Right now after a restart none of the containers that were running in an environment start up automatically, even if running when the RH is power cycled. We need an autostart checkbox option for each container listed in the environment which signals that the RH should start the container up after it is power cycled. 

<img width="1165" alt="screen shot 2016-03-07 at 9 44 58 pm" src="https://cloud.githubusercontent.com/assets/10051386/13581457/a09ca3da-e4af-11e5-960b-50cc0ec80ccf.png">

Also an autostart checkbox option for the entire environment should be added. It's behavior should be as follows:

1. When checked it sets all container autostart checkboxes to checked for all containers
2. When unchecked it sets all container autostart checkboxes to unchecked
3. When even one container autostart checkbox is unchecked, the environment autostart checkbox is set to unchecked

**Comment by soffokl** [comment]
Hm, we are starting container after reboot if they were started. 
Probably this problem was in not latest version. 
Need to be checked again.

**Comment by larenso** [comment]
do we need to start all containers on startup? and frequently real subutai servers will be restarted?

**Comment by soffokl** [comment]
@larenso we are not starting all containers. We are starting only containers that were in running state. Stopped containers will be stopped after reboot.

**Comment by larenso** [comment]
@soffokl oh cool, so I don't think this feature is really necessary, wdyt?

**Comment by Dilshat** [comment]
User should just start those containers that need to be running, and they will be started after RH reboot
I think we can close this issue

**Comment by akarasulu** [comment]
That sounds even better. Let's close this issue.
