### ISSUE TITLE
[UI] [Environment Manager] Usability enhancements to templates listing.

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/base#193]
There are several issues with the templates listing in the Environment Manager:

<img width="286" alt="screen shot 2016-03-07 at 9 58 41 pm" src="https://cloud.githubusercontent.com/assets/10051386/13581615/69025a40-e4b0-11e5-9921-135b4a514f0a.png">

1. The listing takes forever to load because it seems to be hitting the global Kurjun every time: instead an index file is needed listing the templates and their categories that is checksummed. Instead of pulling down this file every time from Kurjun, the checksum should be compared via REST, only if different would the peer download and cache this index file.
2. The listing does not currently paginate (list large set one block of 10, 20 etc at a time): the template listing will soon be huge (perhaps 2000+) with several docker containers, and when that happens usability will drop.
3. The listing should allow the user to select from a dropdown of categories. When a category is selected it should be remembered for the user (setting kept in the user's profile). Templates in categories can be expanded to be displayed using an accordion control.
4. Also we need to find a way to display some kind of icon for templates that do not have one. On the first pass we can use a default icon when the template does not have some icon in its manifest. Might want to add such a manifest, or some kind of optional metadata to our image templates with such a field.

**Comment by larenso** [comment]
all are done except point 3:
separate issue:
https://github.com/subutai-io/base/issues/787
