### ISSUE TITLE
[Docker] Generating sensible icons for manifest file.

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/base#194]
First off we need some kind of descriptive manifest file. Or we need some kind of convention to package icons in the tar ball of our images. Like a simple icon.png in the tar ball top level could be enough. This can be easily accessed from the tarball to display the icon.

This however is not the main point of this enhancement issue. The main point is to generate icons for the hundreds if not thousands of docker images we will produce from the docker integration. They will look ugly and make our UI look ugly without images. I think our docker conversion tool should add some kind of automatic google "feeling lucky" lookup on google images for a picture and use that for the template icon. This is better than no icon and it's really easy to do. 
#156 @p1gmale0n ping!

**Comment by Dilshat** [comment]
Not applicable
