### ISSUE TITLE
Add API to determine if user is a hub user

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/base#1940]
We need some method like `user.isHubUser()` that would allow us to determine if this is a local user or a hub user. In case, it is an admin, it should return false.

**Comment by zubaidullo** [comment]
Now, on Subutai we divide Local user with Hub user only with email part. 
Hub user has **id@hub.subut.ai** email format. Every time, I wondered if Subutai admin creates a user with same email format. So, this user will be counted as Hub user in the current implementation.

**Comment by Dilshat** [comment]
Afaik hub user for admin is not created

**Comment by zubaidullo** [comment]
> Afaik hub user for admin is not created
Admin can see and manage it on `User Management` page

**Comment by Dilshat** [comment]
Whenever a hub user creates an environment, its delegate user with an email containing `@hub.subut.ai` is created. For peer owner, no such delegate user is created if he tries to create an environment from Hub on his own peer.

**Comment by zubaidullo** [comment]
I mean, peer owner (admin) can create a user on Subutai and can set any email to this user, this scenario is without Hub.

**Comment by Dilshat** [comment]
Whenever Hub user creates env in this case we better add new fields to user record in db whichis set only by system.
