### ISSUE TITLE
Add container resource usage metrics to container event

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/base#1945]
We need to provide Hub with container resource usage metrics on a regular basis (hourly).
Currently, container events, sent from peers to Hub, contain only states of containers.
We need to append resource usage (HDD, RAM, CPU, network) metrics to the event.

**Comment by akarasulu** [comment]
Wow, I thought this was already being done. Goes to show the review is paying off.

**Comment by zubaidullo** [comment]
We have resource host metrics, not a specific container metrics. 
We can use the same method (current existing RH metrics) with adding new fields container info.
