### ISSUE TITLE
[UI] Plugins, templates, and environments, and usability.

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/base#195]
Plugins can do anything dealing with management aspects and we have many categories of them:

1. plugins unrelated to templates
2. plugins that manage groups of templates (Cassandra, Elastic Search, Mongo, etc.)
3. plugins that manage several groups of templates in a framework (Usergrid, AppScale)

To manage additional template configuration aspects it's a major PITA to have to:

1. Create and make changes to an environment, then 
2. Go to the "Bazaar"->"Installed" area,
3. Find your plugin to manage those templates or groups of them,
4. Go back and manage your environment again

Once plugins are installed and if they are associated with a specific template or a set of templates to do their thing (i.e. mongo plugin), then the environment should give a cue to the user that it, or a group of it's containers can be managed by their respective plugins. The user can then easily link to the plugin's management tab and **MOST IMPORTANTLY** the environment can automatically be selected in the plugin's environment selector since the user's focus is already on a specific environment.

**Comment by larenso** [comment]
connected issue
https://github.com/subutai-io/base/issues/205
