### ISSUE TITLE
[UI] Navigation history, previous and next controls on a section in the notifications bar.

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/base#196]
We need breadcrumbs to show where we have gone through via history. User should be able to jump around in history easily without back and forth buttons.

**Comment by larenso** [comment]
isn't browser's history functionality enough?

**Comment by akarasulu** [comment]
Yeah you're totally right I really meant breadcrumbs. Was late and I was not expressing myself enough.

**Comment by larenso** [comment]
design team thinks that breadcrumbs are not necessary on subutai as we have only 1 level site
