### ISSUE TITLE
Removing last container from environment gives undefined error

### ISSUE THREAD

**Issue by soffokl** [subutai-io/base#1964]
![image](https://user-images.githubusercontent.com/8612618/29219916-4fea5974-7edb-11e7-9f1d-e5040a0980c8.png)
[karaflogs2017-08-11 21-12-48.txt](https://github.com/subutai-io/base/files/1218320/karaflogs2017-08-11.21-12-48.txt)

**Comment by samsonbek** [comment]
Fixed in e9bd61828c3d668a34bc865df4b996dd741b6416

**Comment by Dilshat** [comment]
Sometimes the error java.lang.reflect.InvocationTargetException is thrown which is not handled and this leads to empty error message.
However we need to find why this error is throw
