### ISSUE TITLE
[Environment] Error on getting templates Internal system Error 500.

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/base#197]
For replay this bug you need:

Test case
1) Go to SS and login under any account.
2) Go to 'Environment' page.

Result: You can observe Error on getting templates Internal system Error 500.

Commit ID 	cad1763e37d092a80f1d2481227413c69b58cdb2

![screenshot from 2016-03-09 09 11 50](https://cloud.githubusercontent.com/assets/11311924/13624371/ae2297ac-e5d7-11e5-8af4-ce9c41e10e7b.png)
[karaflogs2016-03-09 09_12_25.txt](https://github.com/subutai-io/base/files/164369/karaflogs2016-03-09.09_12_25.txt)

**Comment by asanaliev** [comment]
Obsolete.
