### ISSUE TITLE
Add a text to the after installation page 

### ISSUE THREAD

**Issue by akylbekesenaliev** [subutai-io/base#1994]
![image](https://user-images.githubusercontent.com/17665678/29854166-0bb1d766-8d66-11e7-8cf5-5b71e3a775a2.png)
Once peer is done installing and once https://localhost:9999/ is clicked sometimes users face this error:

Why dont we write a message along with this error?
Something like Subutai is firing up, please wait a bit...

**Comment by akarasulu** [comment]
See Jetty documentation on how to customize these error messages.
