### ISSUE TITLE
[System] [Updates] An update is always available even after an install

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/base#2017]
It seems even after a fresh install an update is immediately available. No new build is available. Something is wrong with the mechanism for detecting a new update.  I think we should handle this if we have the bandwidth in this release.

**Comment by Dilshat** [comment]
@akarasulu this is not related to SS.
SS executes `subutai update management -c` command which checks updates on subos level,
SS just shows the output of this command

**Comment by akarasulu** [comment]
@ztimur Please look at this when you get back and create a new issue for the update CLI command.
