### ISSUE TITLE
Tracker shows failed jobs as running

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/base#2022]
To reproduce create crazy amounts of containers in the Environment creation wizard to make build fail. Then goto tracker and you'll see those items looking green with RUNNING state. They should be read and in FAILED state.
![capture](https://user-images.githubusercontent.com/10051386/30570764-219e19e6-9d05-11e7-8319-dca60b54b59f.PNG)

**Comment by Dilshat** [comment]
Need to get access to this peer if possible
