### ISSUE TITLE
[UI] [Environment] Templates don't provide any information for users.

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/base#205]
For replay this improvement you need:

Test case
1) Go to SS login page and login under any account.
2) Go to 'Environment' page.

Result: User can observe templates but can not understand what does this templates mean.
Improvement: Should add more information about each template.

**Comment by larenso** [comment]
In design stage

**Comment by larenso** [comment]
design is completed, now need to be implemented in kurjun to bind it

**Comment by TalasZh** [comment]
it is related to template metadata while being packaged, where all these fields should be imho

**Comment by Dilshat** [comment]
This can be taken fro Hub also since Kurjun might contain custom templates without needed metadata.
Hub can contain such data like template_id -> category etc

**Comment by Dilshat** [comment]
Partially information such as version, size and owner is already displayed. The categories (or tags) will be implemented in the course of issue #787
