### ISSUE TITLE
E2E plugin suggestion link broken on Subutai Console 

### ISSUE THREAD

**Issue by zubaidullo** [subutai-io/base#2053]
"_E2E plugin suggestion Link broken on Subutai Console_" - by user Altynbek Usenov
<img width="1413" alt="subutai" src="https://user-images.githubusercontent.com/4469949/31009110-293e5992-a528-11e7-81cb-948129fdb842.png">

**Comment by zubaidullo** [comment]
Subutai E2E plugin is changed on Chrome web store. Need to refactor link and messages. 
There is Firefox suggestion too, need to remove it. B/c for now, we don't support versions upper than Firefox 49.

**Comment by zubaidullo** [comment]
Subutai E2E plugin 3.0.0 version is coming soon, it's on review. We'll update link to that version.

**Comment by akarasulu** [comment]
Are we really dead on Firefox? How big is a revamp to support it? Wondering if we can have some frontend guys help us to support it? 

@zubaidullo kick me to create a list issues people can help us with on our website - maybe on this page here: [https://subutai.io/help_us_out.html](https://subutai.io/help_us_out.html)

**Comment by zubaidullo** [comment]
Firefox has released 2 major releases in November 2016 and this coming November 2017. 
After first major release which was FF version 50, our e2e plugin started not working. The coming release also will have big changes and our plugin will be needed big refactoring (almost rewriting).
+ We don't have development documentation for our e2e plugin.
