### ISSUE TITLE
Fix bug with parsing output of "subutai map -l"

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/base#2068]
Last changes in the output of `subutai map -l` command cause a bug in SS side.
Need to fix it

**Comment by absidish** [comment]
fixed

**Comment by akarasulu** [comment]
@Dilshat This sounds like it was serious. This would have borked many things. Can you clarify the impact of this?

I'm asking because I'm dealing with other bugs and it would be good to know if this was interfering.

Thanks!

**Comment by Dilshat** [comment]
@akarasulu the bug is related to this Hub issue 
https://github.com/optdyn/hub/issues/3755
