### ISSUE TITLE
[UI] [Environment] Can't observe template at the bottom.

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/base#208]
For replay this bug you need:

Test case
1) Go to SS and login under any account.
2) Go to 'Environment' page and scroll down.

Result: you can't observe the last template at the bottom.

![capture-for-jira-screenshot-20160227-125326-230](https://cloud.githubusercontent.com/assets/11311924/13631053/c5b48c74-e60c-11e5-8e37-9037cb368b4b.png)

**Comment by larenso** [comment]
found on firefox

**Comment by NikolaiB** [comment]
Tested.
