### ISSUE TITLE
Strangely spreaded progress window 

### ISSUE THREAD

**Issue by akylbekesenaliev** [subutai-io/base#2091]
![image](https://user-images.githubusercontent.com/17665678/31940087-bccdff72-b8de-11e7-8ba0-9eb41c5db0b7.png)
![image](https://user-images.githubusercontent.com/17665678/31940117-ca491768-b8de-11e7-9131-d49fe7b575b0.png)

**Comment by akylbekesenaliev** [comment]
Screen resolution: 1366*768

**Comment by Dilshat** [comment]
can not reproduce. what are the exac steps to reproduce the bug @akylbekesenaliev ?

**Comment by samsonbek** [comment]
![image](https://user-images.githubusercontent.com/4163679/32090477-7a10916a-bb11-11e7-99c3-eee0d0da904d.png)
reproduced

**Comment by Dilshat** [comment]
This time it seems due to long log text
