### ISSUE TITLE
Duplicated configuration files after update of Subutai via deb-package

### ISSUE THREAD

**Issue by bnuriddin** [subutai-io/base#210]
Initially configuration files are stored in /opt/subutai-mng/etc/subutai-mng/

After updating Subutai via debian package following problem appears:

new configuration files appear in directory /opt/subutai-mng/etc/subutai-mng/ and in /opt/subutai-mng/etc/
What is interesting is that  config files are different in these directories even if /opt/subutai-mng/etc/subutai-mng/ files are ovewhitten

**Comment by tzununbekov** [comment]
Configuration directory moved from _/opt/subutai-mng/etc/subutai-mng/_ to _/opt/subutai-mng/etc/_
