### ISSUE TITLE
Change label for System->About->SS version

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/base#2115]
This is old for Subutai Social shorthand. Must have missed it in the renaming. Quick easy fix. Let's just call it Subutai Management Version. 

**NOTE** Also let's capitalize version because it's specific to a product component. English grammar rule: when referencing any version we can lowercase. When talking about specific version and in label I think we should follow rule to capitalize the first letter.

Again bogus quick fix.

**Comment by Dilshat** [comment]
may be just name it **Console Version** b/c it will take much space if we use **Subutai Management Version**
![image](https://user-images.githubusercontent.com/3367326/32590079-949f4234-c542-11e7-8124-873da88d8e8a.png)
