### ISSUE TITLE
Cleanup outdated p2p instances

### ISSUE THREAD

**Issue by crioto** [subutai-io/base#2119]
When p2p creates new instance it dumps it's information into a special save file, which is used to restore connection when p2p service restarted for any reason (for example, due to power outage on host). This file only depends on two p2p commands - when `p2p start ...` executed new entry being created and it will be deleted only when `p2p stop ...` executes.
However, when environment created via hub is being removed while particular resource host is offline these instance entries does not get wiped when peer becomes online next time. Basically that means, that after we start RH from significant period of "sleep" we will have some p2p instances running on this host, but those instances will be orphans and will be never used again.

**Comment by Dilshat** [comment]
@crioto as a note, we can clean up only hub or console initiated environments,
if user creates them manually and "forgets" then they will stay orphan

**Comment by Dilshat** [comment]
I see that if console obtains env id of such environment from Hub, it cleans up the env on each available 
there are only 2 cases this does not happen:

1) Hub does not provide id for some reason

2) RH was not connected to MH at the moment of cleanup

**Comment by Dilshat** [comment]
Blocked by https://github.com/subutai-io/agent/issues/197

**Comment by Dilshat** [comment]
Solution: The Console will cleanup all the environments (along with the corresponding p2p swarms)  that are not registered with it (not present atm). This would solve the issue with the offline RH at the moment of an environment removal (when the RH comes online). As about the case of a container destruction when its host RH is offline, we can compare registered containers with the ones that are on the RH (when it comes back online): if there are extra ones (not found within registered containers), then remove them, also if there are no more containers of a particular environment on a particular RH then perform an environment cleanup on that RH.
