### ISSUE TITLE
Notification about PGP plugin is shown even if I already have plugin

### ISSUE THREAD

**Issue by samsonbek** [subutai-io/base#2134]
![image](https://user-images.githubusercontent.com/4163679/33126766-eeb53a22-cfaf-11e7-9e32-14ec7d95cb9c.png)
Even if I already have PGP plugin installed in browser, Subutai Console sometimes shows notification about missing browser PGP plugin. Also there is some popup hint when mouse is hovered over "Setup Manually" button, but hint is showed on behind the border of notification frame and not visible to user.

Chrome Version 60.0.3112.101 (Official Build) (64-bit), Ubuntu 16.04.

**Comment by Dilshat** [comment]
If you install or enable the plugin and refresh the page, the notification about the plugin disappears
