### ISSUE TITLE
Created environment is not shown in UI

### ISSUE THREAD

**Issue by bnuriddin** [subutai-io/base#214]
Problem: after successful creation of environment from mongo template with one container, environment does not appear in UI, both in Env-t list and Console
![image](https://cloud.githubusercontent.com/assets/3857746/13645079/5b216a7a-e653-11e5-920f-45f1d933239e.png)
![image](https://cloud.githubusercontent.com/assets/3857746/13645089/6ce72f92-e653-11e5-8bac-2969713152da.png)
![image](https://cloud.githubusercontent.com/assets/3857746/13645118/8bd60c98-e653-11e5-97a4-9238e7e0a141.png)
![image](https://cloud.githubusercontent.com/assets/3857746/13645126/96fd22e6-e653-11e5-93ae-caa7f87e3f58.png)

**Comment by bnuriddin** [comment]
[karaf.log.txt](https://github.com/subutai-io/base/files/165822/karaf.log.txt)

**Comment by larenso** [comment]
cannot reproduce

**Comment by Dilshat** [comment]
Fixed
