### ISSUE TITLE
Restore accidentally removed plugins

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/base#215]
In order to handle problem when a plugin is accidentally deleted, we need to check this in database.
Thus if user has installed/purchased a plugin, but it is missing , user can restore it.
If a plugin is missing but it is present in the database, UI should show Restore button next to plugin listing.  When users clicks it, the plugin is restored for free (the same version)

**Comment by zubaidullo** [comment]
Hub can send list of products with adding new filed ->  Boolean is_installed
