### ISSUE TITLE
Failure to list templates when using local CDN cache node

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/base#2150]
I configured a local CDN cache node and it seems to work great from the CLI to accelerated development. I was feeling uber nice about it. I even configured the agent.gcfg file to allow insecure CDN connections:

```
[CDN]
Allowinsecure = true
URL = cdn.subut.ai
SSLport = 8338
Kurjun = 
```

Everything is dandy but I cannot see the list of templates in the Environment->Environments builder. I checked and there are several NPE exceptions occurring

[karaflogs2017-11-27 07_13_39.txt](https://github.com/subutai-io/base/files/1504430/karaflogs2017-11-27.07_13_39.txt)
 in the Karaf logs. I've attached them here:

Any idea what's going wrong from the log? Just in case here are the NGINX cache node access logs:

[access.txt](https://github.com/subutai-io/base/files/1504435/access.txt)

The error logs are empty. I think this has something to do with the CDN self-signed keys.

**Comment by Dilshat** [comment]
Seems Kurjun supplies malformed JSON with missing names of templates.
I will add check against such cases

**Comment by akarasulu** [comment]
Ok thanks @Dilshat

**Comment by akarasulu** [comment]
Tested in dev and I still see the same problems with the template manager blowing NPEs:

[karaflogs2017-11-29 05_57_18.txt](https://github.com/subutai-io/base/files/1512027/karaflogs2017-11-29.05_57_18.txt)

Here's my about screen and versions which do not look like dev at all. I think something is broken with devops. This looks like a production management:

![screen shot 2017-11-29 at 6 00 36 am](https://user-images.githubusercontent.com/10051386/33350818-fe34a396-d4ca-11e7-9d60-e8af09aacbaa.png)

**Comment by akarasulu** [comment]
This might explain why some of the version commands with CLI not working. Management must be trying to get them via the production `subutai` command and of course that does not exist but `subutai-dev` does:

```
subutai@subutai:~$ sudo subutai-dev list
CONT/TEMP
---------
management
openjre16
ubuntu16
```

**Comment by akarasulu** [comment]
Just in case I disabled my CDN node to directly hit devcdn:

```
subutai@subutai:~$ sudo subutai-dev destroy management
INFO[2017-11-29 00:08:11] management is destroyed                      
subutai@subutai:~$ ping devcdn.subut.ai
PING i-08c7895c5d5cc19a4.devcdn.subut.ai (35.158.125.126) 56(84) bytes of data.
64 bytes from ec2-35-158-125-126.eu-central-1.compute.amazonaws.com (35.158.125.126): icmp_seq=1 ttl=63 time=94.6 ms
^C
--- i-08c7895c5d5cc19a4.devcdn.subut.ai ping statistics ---
2 packets transmitted, 1 received, 50% packet loss, time 1001ms
rtt min/avg/max/mdev = 94.675/94.675/94.675/0.000 ms
subutai@subutai:~$ sudo subutai-dev import management
INFO[2017-11-29 00:09:07] Importing management                         
INFO[2017-11-29 00:09:08] Version: 6.2.3-dev                           
INFO[2017-11-29 00:09:09] Template's owner signature verified          
INFO[2017-11-29 00:09:09] Downloading management                       
 24.20 MiB / 121.68 MiB [========>--------------------------------]  19.89% 1m3s
```

**NOTE**: The version INFO[2017-11-29 00:09:08] Version: 6.2.3-dev. 

Conclusion, my local CDN is misconfigured most likely and is going to cdn.subut.ai instead of going to devcdn.subut.ai. Just to confirm here's the management about screen after the re-import:

![screen shot 2017-11-29 at 6 12 48 am](https://user-images.githubusercontent.com/10051386/33351106-5e11d120-d4cc-11e7-81b8-a2ff5e67511a.png)

@Dilshat this was my fault and I hope it did not make you change code unnecessarily. Is the change you made still valid or should we roll it out.

Please disregard my last message!

**Comment by akarasulu** [comment]
Ok here's where I am now. I think I fixed my CDN by adding the other two dev and master cdn server blocks. They were never there it seems. Now with it fixed I'm getting "**better**" results but something is still wrong. Here's the about screenshot for console and it's looking good minus a couple fields:

![screen shot 2017-11-29 at 6 49 26 am](https://user-images.githubusercontent.com/10051386/33352161-c937f2a4-d4d1-11e7-993f-54e8e540c0c5.png)

I still cannot see templates and the NPE is still continuing. It looks like I fix the CDN issues but you never know. Here's my local CDN configuration where I use separate self-signed keys for dev, master, and production with proper FQDN i.e. devcdn.subut.ai:

[default.txt](https://github.com/subutai-io/base/files/1512176/default.txt)

Here's the Karaf log:

[karaflogs2017-11-29 06_49_11.txt](https://github.com/subutai-io/base/files/1512168/karaflogs2017-11-29.06_49_11.txt)

**Comment by akarasulu** [comment]
One last thing. I just tried master now too. The problem looks exactly the same.

**Comment by akarasulu** [comment]
@Dilshat want me to test these changes?

**Comment by Dilshat** [comment]
@akarasulu yes please

**Comment by akarasulu** [comment]
@Dilshat I did not want to needlessly tire you out with this because I'm still concerned with the correctness of my local CDN cache node's NGINX configuration. @tilekasankulov @etursunbaev please privately provide the configurations I had asked for.
