### ISSUE TITLE
Get error in my peer state

### ISSUE THREAD

**Issue by amol4anoff** [subutai-io/base#2167]
I created environment on devhub.subut.ai and tried to access container via tray, it showed me error: "can't join p2p swarm". Then i checked my peer in env. and it showed that it has error in state - "ERROR. Containers configuration. io.subutai.common.peer.PeerException: Failed to add ssh keys on each host"
What is strange is that my environment state is healthy!
[ErrorLog.tar.gz](https://github.com/subutai-io/base/files/1521575/ErrorLog.tar.gz)

**Comment by Dilshat** [comment]
@amol4anoff the error you provided is not a full karaf log.
Please try to reproduce and attach full karaf log

**Comment by Dilshat** [comment]
Probably this is due to quota limit exception on RH

**Comment by amol4anoff** [comment]
@Dilshat Wasn't able to reproduce this error.
