### ISSUE TITLE
Peer updating it should be disable for modification, or something else.

### ISSUE THREAD

**Issue by AlinaPenkina** [subutai-io/base#2177]
When peer is updating should be some notification, that now peer is Under Updating and user can't use it right now, Or even make peer not available to build an environment on it And system should check, when somebody wants to update it, that this peer now is free(nobody makes modification on it).

**Comment by akarasulu** [comment]
This is extremely important. The Hub should also show this status properly.

**Comment by AlinaPenkina** [comment]
Fixed on console side on master. Now we need to implement it on hub side: When peer is being updated on console, it shouldn't be available on hub site, no actions should be performed on this peer.
