### ISSUE TITLE
[Peer registration] Can't abort peer registration process with not approved peer.

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/base#221]
For replay this bug you need

Test case
1) Go to SS and login under any account.
2) Go to Peer registration and register a peer with valid IP.
3) Click on 'Cancel' button.

Result: you can observe empty Error message and you can't abort peer registration process.

![screenshot from 2016-03-10 11 49 03](https://cloud.githubusercontent.com/assets/11311924/13661340/0e494e70-e6bc-11e5-8b6c-9b727e74afb6.png)

**Comment by tjamakeev** [comment]
fixed message display problem

**Comment by NikolaiB** [comment]
When I try to abort peer connection process and click on the button 'cancel', I can observe this message 
![screenshot from 2016-03-15 12 31 24](https://cloud.githubusercontent.com/assets/11311924/13769454/02223f2a-eaaa-11e5-8eda-ddd605c0cc2d.png)

But this message not reflect what I'm trying to do, I'm trying to abort process not connect to peer. It should be looks like: 'Can not abort process'

**Comment by tjamakeev** [comment]
please check 192.168.1.100. is it on line?

**Comment by NikolaiB** [comment]
yes

**Comment by tjamakeev** [comment]
you have communication problem. please provide karaf.log.

**Comment by NikolaiB** [comment]
Can't 'cancel' peer request if smth wrong with remote ip.

![screenshot from 2016-03-19 14 38 25](https://cloud.githubusercontent.com/assets/11311924/13897615/5a1bd2f2-ede0-11e5-97dc-0d1e0a8b440f.png)

[karaflogs2016-03-19 14_40_15.txt](https://github.com/subutai-io/base/files/180719/karaflogs2016-03-19.14_40_15.txt)
