### ISSUE TITLE
Running a command on a STOPPED container gives the message "undefined"

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/base#2223]
Instead of writing that container is not running it prints "undefined"

![image](https://user-images.githubusercontent.com/3367326/35320359-ae0b774a-010d-11e8-976e-b139aff47d1c.png)

**Comment by amol4anoff** [comment]
Fixed:

<img width="799" alt="111" src="https://user-images.githubusercontent.com/33647491/35958836-23f82492-0ccd-11e8-96c1-39e7e06b6b89.png">
