### ISSUE TITLE
Agent looks disconnected after management restart

### ISSUE THREAD

**Issue by soffokl** [subutai-io/base#223]
We have a problem with management restart. 

1) Agent works find, approved, and active in monitoring and console tabs;
2) Restarting MH: service management restart;
3) RH icon green, but it disappear from monitoring and console tabs; 

Agent now does not send heartbeats if nothing changed. 
But management stop requesting /ping on this RH after management restart.

**Comment by Dilshat** [comment]
pushed fix to dev
