### ISSUE TITLE
Subutai Console - Bazaar?

### ISSUE THREAD

**Issue by efeefe** [subutai-io/base#2238]
When reviewing documentation about the Subutai Console, I got back to a point already discussed elsewhere: it's somehow confusing to have two different Bazaars - one in the Hub and the other on Subutai Console. Someone suggested changing the Console one to "Plugins" or "Extensions". Does that make sense?

**Comment by Dilshat** [comment]
Yes in the next release the naming will be changed

**Comment by AlinaPenkina** [comment]
Fixed on master.
