### ISSUE TITLE
Subutai potty training

### ISSUE THREAD

**Issue by lbthomsen** [subutai-io/base#2251]
Subutai should learn to clean up after itself :)  No, jokes aside: 

1. Templates that are no longer referenced by any containers should be automatically destroyed.

2. Unused containers should be either automatically destroyed after a while or it should be possible for the peer owner to do so.

This also raises a question about /var/snap/subutai/common/lxc/tmpdir.  Why keep the downloaded template archives around after they are installed?  I would suggest - keep tmpdir empty.

**Comment by akarasulu** [comment]
I agree with all suggestions. It also seems that we're putting stuff into /var outside of the mountpoint for container storage too. This is one of the reasons why I gave lots of space to /var on the vagrant boxes.

**Comment by Dilshat** [comment]
Unused containers are already shown to user on Environment -> Containers section.
The rest will be handled by https://github.com/subutai-io/agent/issues/346
