### ISSUE TITLE
Create page explaning nuances of environment management

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/base#2254]
We need a page which explains what can be done via Hub to Hub and Peer environments and what can be done via Console.

**Comment by akarasulu** [comment]
@Dilshat here is a rough account, and can maybe use it in the doc:

Environments currently can be created in two modes: peer local mode, and hub mode. A peer environment can work without registering the peer with the Hub. It can also span multiple peers. If peers are subsequently registered on the Hub full management of these environments is not possible yet some functionality exists for that.

If users want to create environments that are fully manageable by the Hub they need to create hub environments. This requires using the Hub API and any peers involved need to be registered on the Hub. Just the opposite of a peer environment, a hub environment cannot be fully managed on a peer's console.

**Comment by Dilshat** [comment]
https://github.com/subutai-io/base/wiki/Environment-management-via-Hub-and-Console
