### ISSUE TITLE
Cannot uregister peer - says there're environments, but if we delete them all, it still shows this

### ISSUE THREAD

**Issue by amol4anoff** [subutai-io/base#2288]
Please help. Peer - 192.168.77.11

![screenshot from 2018-02-24 11-42-05](https://user-images.githubusercontent.com/33647491/36626189-5026f150-1958-11e8-8ee6-2a6097c0d84e.png)

**Comment by Dilshat** [comment]
This is either internal latency of Bazzar or the peer has environments of some other users.
This error comes from Bazzar and has nothing to do with Console

**Comment by amol4anoff** [comment]
ok, will re-locate
