### ISSUE TITLE
Error getting metrics from agent

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/base#272]
Sometimes the command to get metrics runs too long and we can not obtain metrics
Here are logs:

**2016-03-13 10:26:56,920 | INFO  | tp1825540462-151 | CommandProcessor                 | 190 - io.subutai.core.executor.impl - 4.0.0.RC7-SNAPSHOT | Sending:
{
  "request": {
    "type": "EXECUTE_REQUEST",
    "id": "100FEF0DE438F650116DF5C38CFDB7FA19DF0F79",
    "commandId": "69527c5d-2c83-4cc9-a67a-52046ec589d2",
    "workingDirectory": "/",
    "command": "subutai metrics rh1457847635.gw.intra.lan -s \"2016-03-13 09:26:56\" -e \"2016-03-13 10:26:56\"",
    "stdOut": "RETURN",
    "stdErr": "RETURN",
    "runAs": "root",
    "timeout": 30,
    "isDaemon": 0,
    "pid": 0
  }
}

2016-03-13 10:27:08,175 | INFO  | tp1825540462-196 | CommandProcessor                 | 190 - io.subutai.core.executor.impl - 4.0.0.RC7-SNAPSHOT | Received:
{
  "type": "EXECUTE_RESPONSE",
  "id": "100FEF0DE438F650116DF5C38CFDB7FA19DF0F79",
  "commandId": "69527c5d-2c83-4cc9-a67a-52046ec589d2",
  "pid": 0,
  "responseNumber": 1,
  "stdOut": "{\"Metrics\":\n"
}

2016-03-13 10:27:19,176 | INFO  | tp1825540462-120 | CommandProcessor                 | 190 - io.subutai.core.executor.impl - 4.0.0.RC7-SNAPSHOT | Received:
{
  "type": "EXECUTE_RESPONSE",
  "id": "100FEF0DE438F650116DF5C38CFDB7FA19DF0F79",
  "commandId": "69527c5d-2c83-4cc9-a67a-52046ec589d2",
  "pid": 0,
  "responseNumber": 2
}

2016-03-13 10:27:27,174 | INFO  | tp1825540462-197 | CommandProcessor                 | 190 - io.subutai.core.executor.impl - 4.0.0.RC7-SNAPSHOT | Received:
{
  "type": "EXECUTE_TIMEOUT",
  "id": "100FEF0DE438F650116DF5C38CFDB7FA19DF0F79",
  "commandId": "69527c5d-2c83-4cc9-a67a-52046ec589d2",
  "pid": 0,
  "responseNumber": 3,
  "exitCode": -1
}
2016-03-13 10:27:27,176 | ERROR | tp1825540462-151 | MonitorImpl                      | 195 - io.subutai.core.metric.impl - 4.0.0.RC7-SNAPSHOT | Error getting historical metrics from rh1457847635.gw.intra.lan: 
**

**Comment by soffokl** [comment]
@Dilshat Cannot reproduce this problem, metrics binding give me results fast every time. Problem could be related to very slow hardware or some internal problem in OS.

**Comment by Dilshat** [comment]
@soffokl please try to create couple of environments on these hosts and leave for couple of hours. It will happen

**Comment by soffokl** [comment]
@Dilshat my host working almost 4 hours with 5 environment on board, and it's still fast:
![image](https://cloud.githubusercontent.com/assets/8612618/13772790/2d5f1602-eac0-11e5-8125-5d5cb519370c.png)

**Comment by soffokl** [comment]
after 22 hours 
![image](https://cloud.githubusercontent.com/assets/8612618/13801644/169cb958-eb5e-11e5-9969-be53b972a2fb.png)

**Comment by soffokl** [comment]
@Dilshat here is screenshot from top command, when I opening monitoring tab. High CPU load from SS, about 30 sec. 
Uptime of this node 22 hours. As you can see from previous commend binding works fast. 
I think problem related, that you processing JSON, converting it, instead just send to browser without processing. 
![image](https://cloud.githubusercontent.com/assets/8612618/13801707/d7ed6efe-eb5e-11e5-8eab-386f82e2cdef.png)

**Comment by larenso** [comment]
@soffokl https://github.com/subutai-io/base/issues/244 related issue
