### ISSUE TITLE
[PGP] moves from popup key generation page if I click on generate button.

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/base#294]
For replay this improvement you need:

Test case:
1) Go to PGP plugin and click on generate button.
2) Click on 'generate' without no symbols in email field.

Result:
![screenshot from 2016-03-15 14 19 22](https://cloud.githubusercontent.com/assets/11311924/13771820/cbc03386-eaba-11e5-8cf2-56a042841e32.png)

Improvement:
Should check the email field on valid symbols, and if it's not valid to email, shows something like: 
'please write your valid email', without closing popup with email field .

**Comment by NickolaiVarin** [comment]
Done
