### ISSUE TITLE
[UI] [Plugin] PGP key should not be available if plugin is active

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/base#304]
In read the PGP message box should not be displayed unless user clicks show or something. Also the black box note that the plugin is not reporting what those activities are.

![selection_030](https://cloud.githubusercontent.com/assets/10051386/13799677/5d2f1f70-eb2a-11e5-80c3-16c006ce4edc.png)

**Comment by TalasZh** [comment]
@Commander223 can you hide this PGP message box (red box) into some container and expands on user click, also can you remove that colon in userId ( ":baatyr <baatyr@subut.ai>")

activities not showing in black box is mainly about localization will look at it
