### ISSUE TITLE
Agent return error while executing command in Zookeeper node.

### ISSUE THREAD

**Issue by eabyshev** [subutai-io/base#307]
Trying execte command:
`service zookeeper status`
Agent gives output:
```
stdErr= * Zookeeper Server is not running
exitCode=3
status=failed
```
In fact this command executed successfully, it gives proper output but it stdErr.

**Comment by soffokl** [comment]
@eabyshev 
This is standard behavior of service command, it print to stderr with proper exit code. 
I have no idea, what can be fixed here.

**Comment by Dilshat** [comment]
I think @eabyshev means that service zk status is normal command which should print result and exit with 0 code:

> root@management:~# service management status ; echo $?
management stop/waiting
0

**Comment by eabyshev** [comment]
But status failed. I have checks after execution of every command, to be sure that it was succeeded. commandResult.hasSucceeded() - value is false.

**Comment by soffokl** [comment]
@Dilshat 

> (amd64)root@3a7287ae-8169-42cd-87aa-0e109746680e:/# service zookeeper status; echo $?
>  Zookeeper Server is not running
>  3

**Comment by soffokl** [comment]
```
#!/bin/bash

NAME=zookeeper_server
PIDFILE=/var/zookeeper/$NAME.pid
DESC="Zookeeper Server"
CMD_PATT="zookeeper"
. /lib/lsb/init-functions


is_running()
{
  if [ -f $PIDFILE ]; then
    pid=`cat $PIDFILE`
    grep -Eq "$CMD_PATT" "/proc/$pid/cmdline" 2>/dev/null && return 0
    return 1
  fi
  return 3
}
```

**Comment by Dilshat** [comment]
@eabyshev update the script to return 0 exit code

**Comment by eabyshev** [comment]
ok. thanks, will update script. commandResult.hasSucceeded() returns true, when exitCode is 0. thats why status was failed.

**Comment by tzununbekov** [comment]
@Dilshat @eabyshev 
guys, are you seriously going to change system script? If yes, it is totally wrong, it breaks all the rules and can bring more headache in future. Please, don't do it.
