### ISSUE TITLE
[Environment] Can't create environment in simple mode if has peer connection and remote peer offline.

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/base#310]
Test case
1) Go to SS and login under any account.
2) Go to 'Peer registration' and register peer.
3) Should do remote peer offline.
3) Go to 'Environment' page and create environment in simple mode. 

Result: you can observe Error message, but if you go to advance mode and choose local peer, you can create environment. That's mean we can create environment in 'simple' mode only if all peers are available. 
There are three ways of improvements: 
- do simple mode not active if we connected to remote peers, 
- do this available but create notification that all peers must be available,
- can create environment using my peer only and then share.

![screenshot from 2016-03-16 16 41 40](https://cloud.githubusercontent.com/assets/11311924/13815647/a2e43cd6-ebb5-11e5-8a94-5d98758ad77b.png)

**Comment by larenso** [comment]
probably this workflow should be modified, in the simple creation mode, 
if some errors occurs with any peer and resource host, probably environment containers should be redistributed again among peers and rhs without errors, without any failure.
This can occur even when on some rh or management return errors.

In the example above all containers should be created in the local resource host, as remote peers is unavailable
