### ISSUE TITLE
Registration failure due to inability to find fingerprint

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/base#311]
I have a feeling this is due to the plugin not properly setting up the public key of the user. I got a message in notifications (sorry cleared it) that said the message was successfully signed. 

![selection_031](https://cloud.githubusercontent.com/assets/10051386/13823241/510a29ba-ebb1-11e5-91f6-aed147dcdc2c.png)

**Comment by akarasulu** [comment]
NOTE that the browser plugin key was the same as the key in the User Identity -> Account Settings.

**Comment by TalasZh** [comment]
@zubaidullo @eabyshev please look at this issue, seems problem in sending encrypted payload to hub, either hub cannot decrypt correctly or ss sending data in wrong format

```
2016-03-16 19:25:00,032 | INFO  | qtp781736633-246 | LoggingOutInterceptor            | 120 - org.apache.cxf.cxf-core - 3.1.0 | Outbound Message
---------------------------
ID: 76
Address: https://hub.subut.ai/rest/v1/peers/3CD8069A17CB8CA9CE985DB1A49D0A9509A6FCEC
Http-Method: POST
Content-Type: application/xml
Headers: {Content-Type=[application/xml], sbt-hdr=[3CD8069A17CB8CA9CE985DB1A49D0A9509A6FCEC], Accept=[*/*]}
Payload: -----BEGIN PGP MESSAGE-----
Version: BCPG v1.52
hQEMAyArx9GDVCL2AQf/cCjWNeumy//lYEgD3E1txeg809086i9RzwVwhpbJqK5C
SirGzLJZIGv/oWdHyW3hHtO3BnzFRbARZvnTX8n79HU2dIUiOI+1FC8KsYMwh3vS
rcB//1g7Ig/PmIEQw5M1X29ywNTETPeKGCXQV+IucEGcKEKfIWVcPDuRmfiWFA7c
NoekF402sG351jcahQ8+i/RfRjzXkhHU9o4WzTXwCyNqTWqvasXFTo4+aBr/xv69
obeaEXlIeNQYWqtrZFcZHWN4eyAhDmWUSnYeu5UCGRWa4XjJZZdYw0ymiX1UNfaH
l8d/FfSLw5MbEHFuSt/IhSqMBbmk5T4rp/N1SkRYe9LCEAFTAE69gZkM+E9OHmDd
ZFyiFqdKBcbzvH4HyxdYYa4sbMBxVUgx1D/umEwrFfowDP4TjRN2O7KBfl809d1d
qEXRVtBiWCewIBXQmkHWAg62SlkRGjx60zblk/JFQdmcS3J3Q03RNkhJlA1ohA4n
7xvffY1BOafsHFFvfcQcGMaBCOzO4fxlGrNse9sf/GJTpXsAaYH2k0Eep8bfuQP7
ZbaU6gadHVptoIXUZsvVnoYlfsNKh+c/LSicqSmJdK8W557pKV9MUzLwyRAcXnFp
oo8hXhCn0uwT0cAAxIWdw/H1SKNrnl2ZrnTlXXXjF4hiYsZiORVKSBWC21HOIPCO
anTHZp6Hv4bUOXPxHpLmPtyrQTtVW1Vk8meoHNddWXcQSAzyovFchqSrfVggjYXp
jRa1mLI421IWT4psDuKM85Q7zdIdJo7k/qPUmAbLsK1A+FooFgMxFuJ/Di5RmC9Q
Clxv1HhPTA7M6wnU6w5ll2rRS8IYD+sjyu6qQpw1azK4yJGX3aoRJrkG7ccmYXNA
SyxHmMQQ32Yahxc5kyx8BJO22t/hWSdUc9+qScpQoR4Fpqsh5HPw/D8+OMGLl2Qw
Nkfyb10C7ntH7jJBFs9KDPyKM9AxyrAY3Amz2naJskB9NEL40jtdecbZiAiuTkZF
NNp5LiPiL23ORZgYqr47GypPgMLm4G+yGGj1RivEFABxQLpoKIlSdoXQWo8hRZiL
GAwdv/T8ljLj7F1/YbO9I9CNB2QecaRTXBGV7KvBLY/VngodkUkArUTp4BOPuIqQ
l1cf6yso1guSWygqVsm9rFrVpYb+UPP+ppEbc56VjmAmDUI3KfswHwo550I9Jsso
21lz+hxweIvVrhBHn5YHqzSMvI/6PyoV76cChWp6I3gMzi34+qh/HO+ECfzzgvqT
c7LWMphU9KHvS3YLzb+YRa8VRQUMRPT+unjzU1bdkToxXQ==
=bBgx
-----END PGP MESSAGE-----
--------------------------------------
2016-03-16 19:25:00,165 | INFO  | qtp781736633-246 | LoggingInInterceptor             | 120 - org.apache.cxf.cxf-core - 3.1.0 | Inbound Message
----------------------------
ID: 76
Response-Code: 403
Encoding: UTF-8
Content-Type: text/plain; charset=UTF-8
Headers: {Cache-Control=[no-cache, no-store, max-age=0, must-revalidate], Content-Length=[43], Content-Type=[text/plain; charset=UTF-8], Date=[Wed, 16 Mar 2016 19:26:37 GMT], Expires=[Thu, 01 Jan 1970 00:00:00 GMT], Server=[Jetty(9.2.14.v20151106)]}
Payload: Cannot get the fingerprint from the request
--------------------------------------
```

**Comment by TalasZh** [comment]
@zubaidullo @asanaliev hey seems encrypted data has proper format (peer owner fingerprint), verify that hub side extracts fingerprint correctly

this is debug output of data that is sent to hub
```
{"ownerFingerprint":"f3a84a91dc73ad6ab1b9b3a9eb8f943a330152c5","ownerEmail":"***","ownerPassword":"***","peerInfo":{"id":"AFFA76724B1D0E58F6CB5286A24EDFA90487C190","name":"Peer AFFA76724B1D0E58F6CB5286A24EDFA90487C190 on ","version":"4.0.0-RC7-SNAPSHOT"}}
```

**Comment by zubaidullo** [comment]
Actually, peer fingerprint send in CertificateData, as a context parameter. Not in body.

**Comment by asanaliev** [comment]
The bug was introduced by this commit:

> commit 16a172c3c5dbc222ce1087d938f66d35f50c53ad
> Author: Nurkaly Isakov <nisakov@critical-factor.com>
> Date:   Tue Mar 15 19:52:55 2016 +0600
> 
>     Added ASYNC HTTP support and error logging for security key manager

The reason is in ServerBusListener (io.subutai.core.channel.impl.interceptor):                                                                                                                                                          
`bus.setProperty( AsyncHTTPConduit.USE_ASYNC, Boolean.TRUE);`

As I understand this property says Karaf to use Async HTTP everywhere. As a side effect of this, a client certificate is not always provided to SSL context. This is why Hub can't get a client certificate b/c it is absent.

To fix this, I disabled Async HTTP for bi-directional auth with Hub.
```
HttpClient.createTrustedWebClientWithAuth(...)
...
    Map<String, Object> requestContext = WebClient.getConfig( client ).getRequestContext();
    requestContext.put( "use.async.http.conduit", Boolean.FALSE );
...
```

**Comment by akarasulu** [comment]
Wow incredible that you caught this @asanaliev. @nk-the-crazy watch out for these dynamics. Later on this might pop up with other things as well due to SS integration with other third parties.
