### ISSUE TITLE
Configuration and settings changes should always send peer configuration on immediate forced heartbeat

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/base#312]
We need to keep peer configuration information on registered peers up to date on the Hub. When there is a change in settings (minus sensitive identity information), or for example a new plugin or template is installed, the peer should force a premature heartbeat push with the configuration information that has changed. This way the bug reports sent on error always have fresh peer configuration information.

**Comment by eabyshev** [comment]
Finished sending SS settings with force a premature heartbeat push. About sending info of new installed plugins, this info already should synchronized by Bazaar. Waiting when Kurjun will stabilized, will add notification about templates.
