### ISSUE TITLE
[UI] [Peer Registration] [Register Peer] Can not observe the bottom of drop down form.

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/base#313]
For replay this bug you need:

Test case
1) Go to SS and login under any account.
2) Click on 'Register peer' menu icon and fill out the form.
3) Go to 'Peer Registration' page and click on 'Register Peer' menu icon.

Result: you can't observe  the bottom of drop down form.

![screenshot from 2016-03-17 10 24 26](https://cloud.githubusercontent.com/assets/11311924/13836630/8b1cc208-ec2d-11e5-8b00-010dc836e501.png)
Commit ID 	81e10d4983973e23cf9e3a8ce818fffb460ca97a

**Comment by Ernisto** [comment]
resolved
