### ISSUE TITLE
[UI] [Register Peer] Observe admin name in login field.

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/base#315]
For replay this bug you need:

Test case
1) Go to SS and login under your account.
2) Click on 'Register Peer' menu icon.

Result: you can observe admin name in login field.

![screenshot from 2016-03-17 12 36 38](https://cloud.githubusercontent.com/assets/11311924/13838342/62f28dd4-ec3d-11e5-9a4d-9ee020b266dd.png)
Commit ID 	81e10d4983973e23cf9e3a8ce818fffb460ca97a

**Comment by Ernisto** [comment]
resolved
