### ISSUE TITLE
[UI] [Environments] [Advance mode] Should add the peers names. 

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/base#316]
For replay this improvement you need

Test case
1) Go to SS and login under any account.
2) Go to Peer registration and register a few peers.
3) Go to 'Environment' page, choose 'Advanced mode'.

Result: you can observe in 'Template' a few  peers: Peer 1, Peer 2. 
Improvement: should add the peers names which will help to recognize which peer is.

![screenshot from 2016-03-17 12 47 43](https://cloud.githubusercontent.com/assets/11311924/13838650/e25e0cc2-ec3f-11e5-8c67-1db0bd054e4b.png)

Commit ID 	81e10d4983973e23cf9e3a8ce818fffb460ca97a

**Comment by larenso** [comment]
connected with https://github.com/subutai-io/base/issues/317
