### ISSUE TITLE
[UI] [Peer registration] Should let the user an option to name remote peer.

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/base#317]
For replay this improvement you need:

Test case
1) Go to SS and login under any account.
2) Go to 'Peer registration' and add a few peers.

Improvement: add an option to let the user name remote peer to better identify it especially if we have more then two remote peers.

![screenshot from 2016-03-17 12 59 49](https://cloud.githubusercontent.com/assets/11311924/13840053/145f07b2-ec4a-11e5-8ee3-d1268739ea24.png)
 
Commit ID 	81e10d4983973e23cf9e3a8ce818fffb460ca97a

**Comment by larenso** [comment]
Timeout should be adjusted in the backend

**Comment by akarasulu** [comment]
What does this have to do with a timeout @larenso ?

**Comment by Dilshat** [comment]
@larenso you can use this method to rename a peer: io.subutai.core.peer.api.PeerManager#setName

**Comment by akarasulu** [comment]
So now we can set the name of our peer before registering it?

**Comment by Dilshat** [comment]
We can rename it after registration.

**Comment by Dilshat** [comment]
Will add option to name during registration

**Comment by zubaidullo** [comment]
Hub side done and tested
