### ISSUE TITLE
environmentManager.getEnvironments() freezes and doesn't respond

### ISSUE THREAD

**Issue by larenso** [subutai-io/base#322]
Reproduce:
1) setup p2p with remote peer
2) create environment on remote peer
3) disable remote peer (power off, or turn off internet, to make it inaccessible)
4) it hangs
(additionally)
5) create environment on local machine
6) still hangs, no results on created environments

UI indicates that response hangs (same behavior I observed in debug mode)

![image](https://cloud.githubusercontent.com/assets/4501130/13845608/44422e02-ec6b-11e5-91db-d904cac3910a.png)

**Comment by larenso** [comment]
when we turn on (remote) missing peer, environmentManager.getEnvironments() doesn't freeze anymore and works without problems

**Comment by NikolaiB** [comment]
when I have 2 remote peers and one of them not available has the same problems, created environments not visible/available.

**Comment by larenso** [comment]
[karaflogs2016-03-17 18-24-53.txt](https://github.com/subutai-io/base/files/177820/karaflogs2016-03-17.18-24-53.txt)
