### ISSUE TITLE
[Peer registration] Can connect the peer to dynamically changeable ip.

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/base#330]
For replay this bug you need:

Test case:
1) Go to SS and login under any account.
2) Go to peer registration and connect to not static peer like (deploy-qa.ddns.net).
you can observe: 
![screenshot from 2016-03-18 14 25 02](https://cloud.githubusercontent.com/assets/11311924/13872493/3bd94f52-ed15-11e5-8071-0d259691ce83.png)
3) Turn off remote peer then turn on. (do this several times)
4) Go to peer registration and create new connection to that peer (deploy-qa.ddns.net)
you can observe:
![screenshot from 2016-03-18 14 27 21](https://cloud.githubusercontent.com/assets/11311924/13872542/92064f1a-ed15-11e5-80b3-53ac2267cf1a.png)
5) Try to close first connection.

Result: you can observe error: Can not connect to 'https://192.168.0.100:8443/'.
![screenshot from 2016-03-18 14 29 35](https://cloud.githubusercontent.com/assets/11311924/13872603/fa4040f4-ed15-11e5-939b-b737725545f4.png)

**Comment by tjamakeev** [comment]
please set proper public name using peer:set-public-url
