### ISSUE TITLE
[UI] [Environments] Should add templates icons (webdemo, mysite, openjre8)

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/base#331]
For replay this bug you need:

Test case:
1) Go to SS and login under any account.
2) Go to 'Environments' page.

Result: you can observe that webdemo, mysite, openjre8 templates doesn't have icons.

**Comment by larenso** [comment]
webdemo and mysite, I don't know this templates. Aren't they are obsolete?

**Comment by larenso** [comment]
added icon to openjre8, mysite will be removed soon (Askhat), it is temporary, icon is not needed
