### ISSUE TITLE
Environment not functioning anymore, how to recover it?

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/base#333]
I created an environment with remote peer but remote peer IP changed, and environment not functioning anymore, how to recover it?

**Comment by Dilshat** [comment]
For now as a workaround execute in Karaf console the following command:
jdbc:execute openjpa/subutaiDS "update peer_data set publicUrl='https://<NEW_IP>:<PORT>/', ip ='<NEW_IP>' where peerId='<PEER_ID>' "

Substitute <XXX> with actual values

**Comment by NikolaiB** [comment]
But in any case, I think in close future, SS has to have migration by automatically.
