### ISSUE TITLE
[Monitoring] doesn't have host_net diagram.

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/base#340]
For replay this bug you need:

Test case
1) Go to SS and login under any account.
2) Go to Monitoring page.

Result: you can't observe host_net diagram.
Ps. on some machines you can observe it, on another don't.

![screenshot from 2016-03-19](https://cloud.githubusercontent.com/assets/11311924/13887941/c3621a6e-ed68-11e5-946b-0c25f0d1b8c2.png)

**Comment by soffokl** [comment]
After investigation, found that host_net data disappear after creating environment, before it everything fine. Will fix it today.
