### ISSUE TITLE
Adding SSH key to environment fails

### ISSUE THREAD

**Issue by asanaliev** [subutai-io/base#350]
UI shows that adding SSH key is successful:
> You have successfully added SSH key for f8bdc8d7-4fa4-4fcb-ae9e-d3387869ed1b environment!

In fact, the Karaf logs show it is failed: 
> Caused by: org.apache.openjpa.lib.jdbc.ReportingSQLException: A truncation error was encountered trying to shrink VARCHAR 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC4Nx6diz3hmi0OBt1LLmxv&' to length 255. {prepstmnt 822610163 INSERT INTO E$vironmentImpl_sshKeys (ENVIRONMENTIMPL_ENVIRONMENT_ID, element) VALUES (?, ?) [params=(String) f8bdc8d7-4fa4-4fcb-ae9e-d3387869ed1b, (String) ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC4Nx6diz3hmi0OBt1LLmxvmy6DPCX+...]} [code=20000, state=$2001]

And there is no key for an environment on UI too:  Environments => SSH Key => Remove

Testing environment:
- Commit ID: 6a95e1660eab3837ef31eb0f33d0320c50072668
- SS version: 4.0.0-RC7-SNAPSHOT
- RH version: v4.0.0-RC6-1457948772

**Comment by Dilshat** [comment]
Fixed on backend.
UI team should fix key removal and improve key display
