### ISSUE TITLE
[Peer registration] Can send peer request to your own ip.

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/base#361]
For replay this bug you need:

Test case
1) Go to SS and login under any account.
2) Go to 'peer registration' and send request to your own ip.

Result: you get an Error requesting remote peer, but when you close the popup message, you can observe not approved peer request.

![1458556981365](https://cloud.githubusercontent.com/assets/11311924/13916380/7837275a-ef84-11e5-970f-01ee89fc5ca1.jpg)
[karaflogs2016-03-21 16_46_09.txt](https://github.com/subutai-io/base/files/182014/karaflogs2016-03-21.16_46_09.txt)

Commit ID 	661f39f53bde0af78fef146cdf4709cd5d4039fc

**Comment by tjamakeev** [comment]
fixed
