### ISSUE TITLE
[Environments] Environment creation process fails on 'Generating PEKs' step. 

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/base#390]
For replay this bug you need:

Test case 
1) Go to SS and login under any account.
2) Go to Environment page and create environment.

Result: the creation process fails.

![screenshot from 2016-03-23 15 19 07](https://cloud.githubusercontent.com/assets/11311924/13980957/76f700da-f10b-11e5-9281-88718b7795b1.png)

[karaflogs2016-03-23 17_39_44.txt](https://github.com/subutai-io/base/files/185876/karaflogs2016-03-23.17_39_44.txt)

**Comment by Dilshat** [comment]
Fixed
