### ISSUE TITLE
Complete PEK generation step in environment modification workflow

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/base#393]
We need to add trust relations to PEK generation step io.subutai.core.environment.impl.workflow.modification.steps.PEKGenerationStep
See for analogy io.subutai.core.environment.impl.workflow.creation.steps.PEKGenerationStep

Also we need to make io.subutai.common.peer.Peer#createPeerEnvironmentKeyPair method to generate PEK for a given environment only once. If it exists we should just return it.
Review all Peer interface methods that work with PEK for the same mechanism:
io.subutai.common.peer.Peer#updatePeerEnvironmentPubKey
io.subutai.common.peer.Peer#addPeerEnvironmentPubKey

**Comment by TalasZh** [comment]
> We need to add trust relations to PEK generation step 
is relation between Peer and Environment?
