### ISSUE TITLE
Improve Security Manager module

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/base#394]
Currently SecurityManager and KeyManager use 2 databases for storing keys
we need to review this implementation and possible use only one database for storing keys.

Also we have many KeyManager classes:
io.subutai.common.security.crypto.key.KeyManager
io.subutai.core.security.impl.crypto.KeyManagerImpl
io.subutai.core.security.api.crypto.KeyManager

we need to leave only one

Also remove duplicate methods 

![pasted image at 2016_05_10 03_44 pm](https://cloud.githubusercontent.com/assets/3367326/15142352/73b14724-16c6-11e6-911d-88689a5646c8.png)

check all places where it can be called and update clients if needed

**Comment by nk-the-crazy** [comment]
Duplicate Key-Management REST services removed. 
PGP KeyPairs use , separate db tables. This was implemented to secure , Secret (private) key pair.
