### ISSUE TITLE
[UI] [Environments] Sometimes some page elements displace.

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/base#410]
For replay this bug you need (Approximate steps):

1) Go to SS and login under any account.
2) Go to 'Environments' page.
3) Scroll the page back and forth, create and delete environment.

Result: you can observe at the top of the page that some web elements displaced.

Notice: Can reproduce it through test automation.

![screenshot from 2016-03-24 19 32 58](https://cloud.githubusercontent.com/assets/11311924/14018557/9df57b2e-f1f8-11e5-9aff-c79d29218deb.png)

**Comment by larenso** [comment]
cannot reproduce, seems like it is happening in testing scenario, @NikolaiB should write the pause function in this moment, so we can test and fix

**Comment by larenso** [comment]
Bug occurs only in playbooks, seems like some libs can alter page content causing this bug, bug is considered not urgent
