### ISSUE TITLE
[UI] Notification bar item dialogs immediately appear then disappear without chance to enter fields

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/base#432]
The notification items like the bell for alerts, and the register button when pressed cause a dialog to appear then it quickly disappears again. This problem occurs only on Chrome on Linux. I tried to reproduce the problem by hitting the console from Mac Chrome but it did not occur. Safari and Firefox did not show this problem. This is a specific problem with Chrome on Linux.

**Comment by larenso** [comment]
I think it was z-index issue, we already improved it here
https://github.com/subutai-io/base/issues/422

**Comment by akarasulu** [comment]
I still see the issue in the following build which is before your post: ef382b9e29d2e596028fa6d49b6eb049eaf00d94

Seems Ctrl-F5 fixes the problem but this definitely needs to be fixed the right way. Please confirm the bug is gone before closing.

https://s3.amazonaws.com/uploads.hipchat.com/529982/3502974/j15e8OB3E2ujwsI/my-shy-notification-dialogs-1.ogv

**Comment by Ernisto** [comment]
Tested on MAC OS Chrome and Safari browsers. Could not reproduce the bug.
