### ISSUE TITLE
[sysnet] Although SSH works SCP to the RH does not work with ubuntu/ubuntu user

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/base#433]
On Linux v4.0.0-RC6-1458921341 snap version SSH to ubuntu@localhost works but SCP does not. I am using the vagrant box via export. I encountered the problem when trying to scp a new management debian file to the RH using -P 2022 for the port. Again SSH oddly works for ubuntu user but for SCP the password is rejected.

**Comment by soffokl** [comment]
Problem was following: incorrect usage of scp syntax. 
It requires -P flag right after scp keywork.
