### ISSUE TITLE
[UI] [Environments] Invalid date instead of the time.

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/base#434]
For replay this bug you need:

Test case
1) Go to SS and login under any account.
2) Go to Environments page and create an environment in a simple mode.

Result: During the process of creation you can observe invalid data instead of the time.

![screenshot from 2016-03-25 18 00 36](https://cloud.githubusercontent.com/assets/11311924/14057856/f8088554-f336-11e5-8332-975449218811.png)

**Comment by larenso** [comment]
fixed
