### ISSUE TITLE
[UI] [Monitoring] Can draw black lines on graphics.

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/base#441]
For replay this bug you need:

Test case
1) Go to SS and login under any account.
2) Go to Monitoring page and by holding left mouse button move the mouse from left to right.

Result: you can observe a lot of black lines on the 'Monitoring' page.
![1458982064999](https://cloud.githubusercontent.com/assets/11311924/14059109/f35c6c34-f361-11e5-9042-bc4e10c0f99f.jpg)

**Comment by larenso** [comment]
This is Mozilla browser issue, working with vector graphics sometimes causes artifacts, when you scroll down and up this lines disappears.
