### ISSUE TITLE
subutai metrics missing content

### ISSUE THREAD

**Issue by larenso** [subutai-io/base#449]
Sometimes command:
subutai metrics [rhname] -s [from] -e [to]
which run by subutai commandExecutor returns response with the missing content
stdOut: blalbalba.... [1459003020,0],[14
here you see that end has been cut

and you observe that charts on monitoring page is not loaded as it doesn't validate json

karaf log attached, read the latest commands
[karaflogs2016-03-26 21-08-33.txt](https://github.com/subutai-io/base/files/190518/karaflogs2016-03-26.21-08-33.txt)

**Comment by Dilshat** [comment]
Fixed
