### ISSUE TITLE
[Peer registration] Add an option to cancel the peer request if something goes wrong.

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/base#499]
Right now we can abort the peer request process only if everything goes well. 
But if something goes wrong we can observe an error message and can not cancel the peer request. 

Improvement: Should add an option to abort peer request process even if something goes wrong.

Error we can observe now
![screenshot from 2016-03-29 21 26 59](https://cloud.githubusercontent.com/assets/11311924/14113481/018715bc-f5f5-11e5-9f82-627dfb2f9c97.png)

**Comment by Dilshat** [comment]
Will be handled by this issue https://github.com/subutai-io/base/issues/590
