### ISSUE TITLE
[UI] [Environment] Should sort templates by the name.

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/base#503]
For replay this improvement you need:

Test case
1) Go to SS and login under any account.
2) Go to 'Environment' page.

Result: you can observe not sorted templates.

Improvement: Should sort templates by the name.

![screenshot from 2016-03-29 23 19 38](https://cloud.githubusercontent.com/assets/11311924/14117073/bf1257cc-f604-11e5-90aa-63982d347ca0.png)

**Comment by Commander223** [comment]
commit 2cbcafb9aa8755a5f1af580f342a9771e9f6b97d
