### ISSUE TITLE
[Peer registration] long response if IP is not valid.

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/base#508]
For replay this bag you need:

Test case
1) Go to SS an login under any account.
2) Go to 'Peer registration' and register peer with not valid IP.

Result: you can observe loading process, and you receive the Error message that this is not valid IP, only in a few minutes.

![screenshot from 2016-03-30 13 32 09](https://cloud.githubusercontent.com/assets/11311924/14135102/44453dd8-f67d-11e5-8090-ce0f49001a79.png)

[karaflogs2016-03-30 17_52_28.txt](https://github.com/subutai-io/base/files/195416/karaflogs2016-03-30.17_52_28.txt)

**Comment by larenso** [comment]
Problem is the server doesn't respond, and our js side just throws error

**Comment by larenso** [comment]
Actually when we enter wrong url backend takes 15 sec, to respond that url is incorrect

**Comment by Dilshat** [comment]
Will be handled by this issue https://github.com/subutai-io/base/issues/590
