### ISSUE TITLE
Management doesn't respond after some period of time (high CPU)

### ISSUE THREAD

**Issue by larenso** [subutai-io/base#510]
Management doesn't respond after some period of time (high CPU)

![image](https://cloud.githubusercontent.com/assets/4501130/14141230/b5d60ff0-f69f-11e5-8636-42f063492616.png)

**Comment by larenso** [comment]
could be memory exception
memory usage of rh:
![image](https://cloud.githubusercontent.com/assets/4501130/14141392/8b18d62a-f6a0-11e5-8d73-d1ab3c2d1dc0.png)

**Comment by larenso** [comment]
Any suggestions?

**Comment by kylycht** [comment]
@larenso what is the "period"?

**Comment by larenso** [comment]
@kylycht ~ 12h

**Comment by kylycht** [comment]
@larenso can you attach thread dumps and heap dumps when load is high?

**Comment by larenso** [comment]
@kylycht oh I have already restarted, ok I will attache on the next occurrence

**Comment by Dilshat** [comment]
you have to enable JMX Connection first then you will be able to attach @larenso 
See src/main/assembly/bin/setenv  section "JMX connection for Karaf "

**Comment by Dilshat** [comment]
Can not reproduce
