### ISSUE TITLE
[Register peer] Can send heartbeat and unregister the peer if the peer on the Hub was deleted.

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/base#516]
For replay this bug you need:

Test case
1) Go to SS and login under any account.
2) Go to 'Register peer' menu item and register peer, send heartbeat.
3) Go to Hub by 'Go to Hub' link and remove the peer.
4) Go to SS, click on 'Online' menu item and click on 'unregister' then 'send heartbeat'.

Result: you can observe this error messages:

![screenshot from 2016-03-30 19 10 33](https://cloud.githubusercontent.com/assets/11311924/14143210/ea80222a-f6ab-11e5-9db4-22a8a77f1763.png)

![screenshot from 2016-03-30 19 10 14](https://cloud.githubusercontent.com/assets/11311924/14143214/ef6d81c4-f6ab-11e5-99c9-022f84f78aad.png)

[karaflogs2016-03-30 19_15_53.txt](https://github.com/subutai-io/base/files/195554/karaflogs2016-03-30.19_15_53.txt)

**Comment by eabyshev** [comment]
done
