### ISSUE TITLE
P2P error on frequent create/remove environment

### ISSUE THREAD

**Issue by larenso** [subutai-io/base#517]
How to reproduce:
try to create environments one after another, and destroying old

karaf log is attached:
[karaflogs2016-03-30 20-34-39.txt](https://github.com/subutai-io/base/files/195725/karaflogs2016-03-30.20-34-39.txt)

![image](https://cloud.githubusercontent.com/assets/4501130/14145744/c687ea5a-f6b6-11e5-8e99-fa549f47843c.png)

**Comment by larenso** [comment]
I have removed all environments, but observe p2p interfaces, is that correct behavior?

![image](https://cloud.githubusercontent.com/assets/4501130/14145969/c8ae08f4-f6b7-11e5-86d6-1770c880539b.png)

**Comment by Dilshat** [comment]
Now we are checking for existing interfaces on SS side
