### ISSUE TITLE
While creating a mega environment 20+ master containers I got this DataTables error

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/base#520]
![screen shot 2016-03-30 at 4 00 03 pm](https://cloud.githubusercontent.com/assets/10051386/14155646/94b34ca2-f690-11e5-93e1-50a2cd707aae.png)

After this even previous environments that I created disappeared:

![screen shot 2016-03-30 at 4 02 11 pm](https://cloud.githubusercontent.com/assets/10051386/14155712/dc5ed40e-f690-11e5-86da-ab9899831b6b.png)

**Comment by akarasulu** [comment]
Then magically they came back after the UI tried to refresh itself:

![screen shot 2016-03-30 at 4 03 12 pm](https://cloud.githubusercontent.com/assets/10051386/14155761/153845f8-f691-11e5-92e5-0228135388c2.png)

**Comment by akarasulu** [comment]
@Commander223 this is an uber annoying problem and I just realized it has nothing to do with the database. Could you please fix this as soon as possible?

**Comment by larenso** [comment]
couldn't reproduce it, need to check on slow machine

**Comment by akarasulu** [comment]
I have fast machine @larenso !!! Dude this thing happens often. If you like I can prep you a peer to test. Want that ?
