### ISSUE TITLE
[VM] fails in an hour of work.

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/base#521]
For replay this bug you need

Test case
1) Go to SS and login under any account and you should work there for an hour or a few hours.

Result: during this time the VM drops down and you need to run it again.

[karaflogs2016-03-31 17_13_33.txt](https://github.com/subutai-io/base/files/197474/karaflogs2016-03-31.17_13_33.txt)

**Comment by Dilshat** [comment]
Could not reproduce

**Comment by soffokl** [comment]
@NikolaiB Sounds like it is your local problem with VirtualBox, no one else have such problems.
