### ISSUE TITLE
[Environment] Can't create an environment get an error.

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/base#529]
For replay this bug you need

Test case 
1) Go to SS and login under any account.
2) Go to 'Environment' page and create an environment. If it'll create it, delete it and repeat the environment creation process again.

Result: you can observe Error message
![screenshot from 2016-03-31 23 21 07](https://cloud.githubusercontent.com/assets/11311924/14184638/f21cf232-f797-11e5-978f-47ca7c73767c.png)

[karaflogs2016-03-31 23_21_52.txt](https://github.com/subutai-io/base/files/198230/karaflogs2016-03-31.23_21_52.txt)

Commit ID 	0ba0244428af72b3be72d48f83d828511a072108

**Comment by Dilshat** [comment]
Fixed
