### ISSUE TITLE
Stereo overlapping views after destroying management and importing again

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/base#547]
After running into bug #520 again, I said F'it and destroyed my management container from the RH. Then I imported it back again. Then when I refreshed my view in Safari I so this nastiness start to happen:

<img width="1781" alt="screen shot 2016-04-01 at 7 55 50 pm" src="https://cloud.githubusercontent.com/assets/10051386/14222899/dbfafece-f844-11e5-8551-7a8360e686ad.png">

This got so bad it cooked my CPU both on the client machine and the remote machine where I was running the peer.  The CPU on the Java Karaf process went up to ~45-65% and has just stayed there since.

**Comment by larenso** [comment]
fixed with https://github.com/subutai-io/base/issues/595
