### ISSUE TITLE
[VM] [Environment] Fails in an hour of work and after run has an error of p2p.

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/base#549]
Guys something wrong with my SS: I updated snappy, run new VM with management and it worked well, I could create an environments without errors. Then in 40 min VM dropped down. I run VM then went to Environment page and tried to create an environment but got an p2p error. Help me to find a  reason of such error? 

![screenshot from 2016-04-02 11 26 43](https://cloud.githubusercontent.com/assets/11311924/14224663/16c40bb4-f8c6-11e5-87b8-d421cfc4067d.png)

[karaflogs2016-04-02 11_17_30.txt](https://github.com/subutai-io/base/files/200693/karaflogs2016-04-02.11_17_30.txt)

**Comment by Dilshat** [comment]
according to log, command to p2p time out

2016-04-02 05:16:29,162 | INFO  | pool-64-thread-1 | CommandProcessor                 | 191 - io.subutai.core.executor.impl - 4.0.0.RC7-SNAPSHOT | Sending:
{
  "request": {
    "type": "EXECUTE_REQUEST",
    "id": "F2DD41B693481614EE60600BF52E44E87AC1B9ED",
    "commandId": "49a956fe-ca12-4080-a479-f038d09486fb",
    "workingDirectory": "/",
    "command": "subutai management_network",
    "args": [
      "p2p",
      "-p"
    ],
    "stdOut": "RETURN",
    "stdErr": "RETURN",
    "runAs": "root",
    "timeout": 30,
    "isDaemon": 0,
    "pid": 0
  }
}
2016-04-02 05:16:40,094 | INFO  | tp1863265084-217 | CommandProcessor                 | 191 - io.subutai.core.executor.impl - 4.0.0.RC7-SNAPSHOT | Received:
{
  "type": "EXECUTE_RESPONSE",
  "id": "F2DD41B693481614EE60600BF52E44E87AC1B9ED",
  "commandId": "49a956fe-ca12-4080-a479-f038d09486fb",
  "pid": 0,
  "responseNumber": 1
}
2016-04-02 05:16:51,079 | INFO  | tp1863265084-151 | CommandProcessor                 | 191 - io.subutai.core.executor.impl - 4.0.0.RC7-SNAPSHOT | Received:
{
  "type": "EXECUTE_RESPONSE",
  "id": "F2DD41B693481614EE60600BF52E44E87AC1B9ED",
  "commandId": "49a956fe-ca12-4080-a479-f038d09486fb",
  "pid": 0,
  "responseNumber": 2
}
2016-04-02 05:16:59,350 | INFO  | tp1863265084-217 | CommandProcessor                 | 191 - io.subutai.core.executor.impl - 4.0.0.RC7-SNAPSHOT | Received:
{
  "type": "EXECUTE_TIMEOUT",
  "id": "F2DD41B693481614EE60600BF52E44E87AC1B9ED",
  "commandId": "49a956fe-ca12-4080-a479-f038d09486fb",
  "pid": 0,
  "responseNumber": 3,
  "exitCode": -1
}

**Comment by soffokl** [comment]
@NikolaiB Is this single RH with management?  Please provide your VM configuration: 
* number of CPU
* RAM

Also please provide output from following commands in RH:
```
cat /proc/cpuinfo
cat /proc/meminfo
```

**Comment by NikolaiB** [comment]
`ubuntu@ubuntu:~$ cat /proc/cpuinfo
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 60
model name	: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
stepping	: 3
microcode	: 0x19
cpu MHz		: 3600.000
cache size	: 8192 KB
physical id	: 0
siblings	: 8
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm ida arat epb pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm xsaveopt
bugs		:
bogomips	: 7183.36
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 60
model name	: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
stepping	: 3
microcode	: 0x19
cpu MHz		: 3600.140
cache size	: 8192 KB
physical id	: 0
siblings	: 8
core id		: 1
cpu cores	: 4
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm ida arat epb pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm xsaveopt
bugs		:
bogomips	: 7183.36
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 2
vendor_id	: GenuineIntel
cpu family	: 6
model		: 60
model name	: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
stepping	: 3
microcode	: 0x19
cpu MHz		: 3600.000
cache size	: 8192 KB
physical id	: 0
siblings	: 8
core id		: 2
cpu cores	: 4
apicid		: 4
initial apicid	: 4
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm ida arat epb pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm xsaveopt
bugs		:
bogomips	: 7183.36
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 3
vendor_id	: GenuineIntel
cpu family	: 6
model		: 60
model name	: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
stepping	: 3
microcode	: 0x19
cpu MHz		: 3600.000
cache size	: 8192 KB
physical id	: 0
siblings	: 8
core id		: 3
cpu cores	: 4
apicid		: 6
initial apicid	: 6
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm ida arat epb pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm xsaveopt
bugs		:
bogomips	: 7183.36
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 4
vendor_id	: GenuineIntel
cpu family	: 6
model		: 60
model name	: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
stepping	: 3
microcode	: 0x19
cpu MHz		: 3599.718
cache size	: 8192 KB
physical id	: 0
siblings	: 8
core id		: 0
cpu cores	: 4
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm ida arat epb pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm xsaveopt
bugs		:
bogomips	: 7183.36
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 5
vendor_id	: GenuineIntel
cpu family	: 6
model		: 60
model name	: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
stepping	: 3
microcode	: 0x19
cpu MHz		: 3600.281
cache size	: 8192 KB
physical id	: 0
siblings	: 8
core id		: 1
cpu cores	: 4
apicid		: 3
initial apicid	: 3
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm ida arat epb pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm xsaveopt
bugs		:
bogomips	: 7183.36
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 6
vendor_id	: GenuineIntel
cpu family	: 6
model		: 60
model name	: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
stepping	: 3
microcode	: 0x19
cpu MHz		: 3600.140
cache size	: 8192 KB
physical id	: 0
siblings	: 8
core id		: 2
cpu cores	: 4
apicid		: 5
initial apicid	: 5
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm ida arat epb pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm xsaveopt
bugs		:
bogomips	: 7183.36
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:

processor	: 7
vendor_id	: GenuineIntel
cpu family	: 6
model		: 60
model name	: Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
stepping	: 3
microcode	: 0x19
cpu MHz		: 3600.281
cache size	: 8192 KB
physical id	: 0
siblings	: 8
core id		: 3
cpu cores	: 4
apicid		: 7
initial apicid	: 7
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm ida arat epb pln pts dtherm tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm xsaveopt
bugs		:
bogomips	: 7183.36
clflush size	: 64
cache_alignment	: 64
address sizes	: 39 bits physical, 48 bits virtual
power management:
`


`ubuntu@ubuntu:~$ cat /proc/meminfo
MemTotal:        8044668 kB
MemFree:         2747180 kB
MemAvailable:    3442696 kB
Buffers:           12412 kB
Cached:           832548 kB
SwapCached:         2352 kB
Active:           133104 kB
Inactive:         775576 kB
Active(anon):      58916 kB
Inactive(anon):     6388 kB
Active(file):      74188 kB
Inactive(file):   769188 kB
Unevictable:           0 kB
Mlocked:               0 kB
SwapTotal:       8253436 kB
SwapFree:        8220324 kB
Dirty:               880 kB
Writeback:             0 kB
AnonPages:         63120 kB
Mapped:          4265740 kB
Shmem:              1428 kB
Slab:              98044 kB
SReclaimable:      42164 kB
SUnreclaim:        55880 kB
KernelStack:        3456 kB
PageTables:        12360 kB
NFS_Unstable:          0 kB
Bounce:                0 kB
WritebackTmp:          0 kB
CommitLimit:    12275768 kB
Committed_AS:    4471728 kB
VmallocTotal:   34359738367 kB
VmallocUsed:      359328 kB
VmallocChunk:   34359366100 kB
HardwareCorrupted:     0 kB
AnonHugePages:     36864 kB
CmaTotal:              0 kB
CmaFree:               0 kB
HugePages_Total:       0
HugePages_Free:        0
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
DirectMap4k:       78172 kB
DirectMap2M:     1888256 kB
DirectMap1G:     7340032 kB
`

**Comment by soffokl** [comment]
@NikolaiB these commands should executed on RH

**Comment by soffokl** [comment]
@NikolaiB I thought that it could be problem with weak hardware. But you have really powerful machine, it is definitely not this case. 

Try to update your VirtialBox and whole system with something like this:
`apt update && apt upgrade `

It could help with problems about stopping VM.

**Comment by NikolaiB** [comment]
thanks, will try and will let you know

**Comment by NikolaiB** [comment]
Didn't help still has the same problem

![screenshot from 2016-04-02 16 49 29](https://cloud.githubusercontent.com/assets/11311924/14225845/4e8eca98-f8f3-11e5-96de-b9b8388f2eff.png)

[karaflogs2016-04-02 16_51_44.txt](https://github.com/subutai-io/base/files/200788/karaflogs2016-04-02.16_51_44.txt)

**Comment by soffokl** [comment]
@NikolaiB 
@crioto has fixed problem with p2p after reboot. Now after reboot everything should be OK.

**Comment by NikolaiB** [comment]
@soffokl fixed, just checked.
