### ISSUE TITLE
[UI] [Bazaar] Should do popup Additional Dependences more informative.

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/base#561]
For replay this improvement you need:

Test case
1) Go to SS and login under any account.
2) Go to Bazaar page and click on Install 'Spark' plugin.

Result: you can observe message on popup Additional Dependences.
Improvement: Add an additional information about additional plugins which will be installed.

![screenshot from 2016-04-02 22 05 09](https://cloud.githubusercontent.com/assets/11311924/14227422/0531cc84-f91f-11e5-8697-d6822958ccb3.png)

**Comment by larcohex** [comment]
Added
