### ISSUE TITLE
[UI] [Monitoring] Remove 'Select host' from the list of options.

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/base#565]
For replay this bug you need

Test case
1) Go to SS and login under any account.
2) Go to 'Monitoring' page and click on RH selector.

Result: you can observe 'Select recourse host' like an option to choose.

![1459623746953](https://cloud.githubusercontent.com/assets/11311924/14228535/ddf6f030-f938-11e5-827f-5b80f1a8c9bb.jpg)

**Comment by Commander223** [comment]
fixed ef0dd7c3ea218f10e85adf42d2f84789ac3f9d63
