### ISSUE TITLE
[P2P] After peer connection show the remote peer offline.

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/base#567]
For replay this bug you need:

Test case
1) Go to SS and login under any account.
2) Go to peer registration and register peer.

Result: you can observe that remote peer offline. If you will go to Environments -> Advance mode you can observe remote peer there but without rh.

![screenshot from 2016-04-03 10 33 23](https://cloud.githubusercontent.com/assets/11311924/14230778/9f3e58fc-f987-11e5-884a-0b3f58277491.png)

![screenshot from 2016-04-03 10 32 58](https://cloud.githubusercontent.com/assets/11311924/14230780/a402e498-f987-11e5-9666-39ade66552cf.png)

[karaflogs2016-04-03 10_27_58.txt](https://github.com/subutai-io/base/files/201171/karaflogs2016-04-03.10_27_58.txt)

**Comment by Dilshat** [comment]
According to logs, remote peer was inaccessible within specific timeout
