### ISSUE TITLE
Implement proper peer registration

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/base#590]
Current implementation of peer registration is not satisfactory due to various cases that are not considered. We need to improve this process in the following way:
1. Add option to remove registration even if remote peer is not accessible. It may be the same "Unregister" method with a confirmation popup if the peer is used for hosting environment containers. If user selects Yes then remove.
2. When sending registration ,cancellation or unregistration request check the peer for accessibility with small timeout on http client so that it does not hang.
3. When approving registration request, check if the provided public URL in peer_info is accessible. This can be done when registration request is being approved and relevant error message should be shown.
This will handle the case when remote peer sends its local url as public url.
4. When sending registration request to URL that is different from peer public URL (diff from local subnet), show confirmation popup with recommendation for user to check if public URL is set to external forwarded interfaces.
5. Change one long public url to separate public IP, public port1 and public port2 (secure port) with relevant help information on UI like: public port 1 corresponds to 8443 and public port 2 to 8444 which should be forwarded/available via Internet along with public IP.
6. When performing registration request, in case there is a public URL specified for local peer, enable user to choose which URL to supply to remote peer: local intranet or public. 
7. During registration approval, in case there is a public URL specified for local peer, enable user to choose which URL to supply to request initiator peer: local intranet or public.

**Comment by nk-the-crazy** [comment]
Added control statement to check Remote peer status (availability). 
For removal operations add ForceRemoval options that forces some operation to continue even remote peer is not responding.
