### ISSUE TITLE
[Environment menu item] Become not clickable until renew the page.

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/base#595]
For replay this bug you need:

Test case
1) Go to SS and login under any account.
2) Go to Peer request and send the request to remote peer.
3) Go to remote peer and approve the request. 
4) Change the ip in address bar which return you back to your server.
5) Click on Environment menu item.

Result: It's not clickable until you renew the page.

**Comment by Commander223** [comment]
fixed in b014f5fd1e4e63455565a3a2358dd25d343dd294
