### ISSUE TITLE
[Cross peer] Can unrigiser a peer if environment already exist.

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/base#596]
For replay this bug you need:

Test case
1) Go to SS and login under any account.
2) Send a peer request to remote peer which it has to accept.
3) Create an environment with your rh's and remote peer rh's.
4) Go to remote peer and unregister a peer.

Result: you can unregister a peer without any problems.

**Comment by Dilshat** [comment]
Will be handled by this issues https://github.com/subutai-io/base/issues/590
