### ISSUE TITLE
[Cross Peer Environment] Can delete an environment when remote peer offline. 

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/base#597]
For replay this bug you need:

Test case
1) Go to SS and login under any account.
2) Register a peer and create an environment with remote peer by using all rh's.
3) Turn off remote peer.
4) Delete an environment.

Result: you can observe that at first environment becomes under modification then it removes.

**Comment by Dilshat** [comment]
what is the problem? if peer is inaccessible, the same logic applies as if user unregistered that peer, environment gets destroyed, corresponding errors that environment part failed to destroy on Peer X is logged to tracker
