### ISSUE TITLE
[Environment] Should add an option to remove 'under modification' Environments.

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/base#606]
Description: If the during the process of environment creation user will face with some unfavourable situations, like an SS dropped down or the light went out, he can observe 'under modification' Environment. And the user can't remove it.

Improvement: should add in option to remove 'under modification' Environments in an hour for example, SS will check if the Environment under modification more then hour, the user get an option to remove it.

**Comment by Dilshat** [comment]
Destroy will cancel active workflow and destroy environment
