### ISSUE TITLE
Password-less Hub trust based authentication to third party peer

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/base#621]
Right now the Hub is being authorized by the SS peer (when registered with the Hub) to create a user account. This account is created to establish the environment owner on the console of someone else's peer so they may view and administer their environments on it. 

You can see the user identity that is being created on OPPs here:

![screen shot 2016-04-05 at 5 38 34 pm](https://cloud.githubusercontent.com/assets/10051386/14298894/64cc7026-fb55-11e5-9f19-8872dfada929.png)

This decreases usability, bypasses the entire point of having the e2e plugin and our advanced security model and potentially creates a security hole. It's much better to simply create a trust chain from the peer and its owner to the owner of the environment through their mutual hub trust like so:

[peer owner id] ---owner---> [peer id] ---trust---> [hub id] ---trust---> [member id] ---owner---> [env id]

At the end, the net result should be to authenticate onto the SS console without a password using your Hub account based on this trust chain. The login screen combined with the browser plugin should work together to ask if you want to login as a user defined in the browser plugin. 

Notes:

* The peer owner and their registered peers trust the hub, perhaps each peer that is setup as public or shared can have different kinds of trust authorizations
   * sharing with friends statically causes direct trusts between the peer id and hub member id
   * public access for dynamic use causes transitive trusts that go through the hub id 
* The hub trusts the environment owner who owns their environment to manage it
* The hub id must be setup and this key pair must be protected
* This need represents the first big integration step using the security model of SS with the Hub and should be done properly

**Comment by nk-the-crazy** [comment]
Authentication by SignedMessage feature is added. User can use PGPKeyPairs , create a signedMessage and authenticate itself to the system.
