### ISSUE TITLE
[critical] Env mngr apply button not activated 

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/base#623]
This is a pretty bad bug and it seems @bnuriddin it's happening because you've setup Keshig incorrectly. I have installed a peer using the officially released installer for Mac and the downloaded manage image should not have changed but it did. @larenso talk to @bnuriddin. @Dilshat @subutai-io/admins you need to be aware of this to fix.

Here's the bug and as a result I cannot create an environment. This means all our users are now having this problem as well. 

![selection_102](https://cloud.githubusercontent.com/assets/10051386/14299800/8901eac0-fb5a-11e5-94ac-bd661c387dc0.png)

**Comment by akarasulu** [comment]
@bnuriddin see below to confirm that you've NOW overwritten our stable version with the dev branch changes. This is horrible man. It puts us in a serious situation with our users. Please fix Keshig ASAP:

![image](https://cloud.githubusercontent.com/assets/10051386/14299924/45d72b56-fb5b-11e5-8614-70cb0ac703c2.png)

**Comment by akarasulu** [comment]
@soffokl @tzununbekov can you guys see if we can recover our release images from backups. We could not do a tag based release because of the breakage so I cannot build again from a tag.

**Comment by akarasulu** [comment]
The button may be working but there is a delay due to activity or some odd quirk. I'm going to close this issue now and note the bug on Keshig.

**Comment by larenso** [comment]
Apply button works, styles were overwritten by merge, currently styles are fixed
