### ISSUE TITLE
Env build failure while cloning containers

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/base#625]
![image](https://cloud.githubusercontent.com/assets/10051386/14300903/83ca4654-fb61-11e5-8a9d-201ece9535c8.png)

![image](https://cloud.githubusercontent.com/assets/10051386/14300942/bb44ef26-fb61-11e5-85c3-8185157e88cf.png)

[karaflogs2016-04-06 02-06-29 (1).txt](https://github.com/subutai-io/base/files/205502/karaflogs2016-04-06.02-06-29.1.txt)

**Comment by Dilshat** [comment]
@soffokl  Found strange log:
{
  "request": {
    "type": "EXECUTE_REQUEST",
    "id": "0F4723C0FF064E59214AE3752A0A13DBFB4FD900",
    "commandId": "b5ac10f3-5505-4f08-b5e0-d4a3412a0689",
    "workingDirectory": "/",
    "command": "subutai clone master b23f1c12-10bd-4819-98a1-94215e00ad17 -i \"192.168.1.7/24 100\" -e 934e61fb-4a3a-4886-9cf7-edad19bc2b8a -t 3c535abc-a522-47d8-b4eb-769ca7265fb1",
    "stdOut": "RETURN",
    "stdErr": "RETURN",
    "runAs": "root",
    "timeout": 300,
    "isDaemon": 0,
    "pid": 0
  }
}

2016-04-05 23:05:16,020 | INFO  | tp1689879544-253 | CommandProcessor                 | 191 - io.subutai.core.executor.impl - 4.0.0.RC7-SNAPSHOT | Received:
{
  "type": "EXECUTE_RESPONSE",
  "id": "0F4723C0FF064E59214AE3752A0A13DBFB4FD900",
  "commandId": "b5ac10f3-5505-4f08-b5e0-d4a3412a0689",
  "pid": 0,
  "responseNumber": 2
}
2016-04-05 23:05:16,193 | INFO  | tp1689879544-257 | CommandProcessor                 | 191 - io.subutai.core.executor.impl - 4.0.0.RC7-SNAPSHOT | Received:
{
  "type": "EXECUTE_RESPONSE",
  "id": "0F4723C0FF064E59214AE3752A0A13DBFB4FD900",
  "commandId": "b5ac10f3-5505-4f08-b5e0-d4a3412a0689",
  "pid": 0,
  "responseNumber": 1
}

2016-04-05 23:05:17,363 | INFO  | tp1689879544-301 | CommandProcessor                 | 191 - io.subutai.core.executor.impl - 4.0.0.RC7-SNAPSHOT | Received:
{
  "type": "EXECUTE_RESPONSE",
  "id": "0F4723C0FF064E59214AE3752A0A13DBFB4FD900",
  "commandId": "b5ac10f3-5505-4f08-b5e0-d4a3412a0689",
  "pid": 0,
  "responseNumber": 3,
  "stdOut": "time\u003d\"2016-04-05 23:05:13\" level\u003dfatal msg\u003d\"Importing Management public key to keyring, exit status 2\" \n",
  "exitCode": 1
}

**Comment by soffokl** [comment]
@Dilshat does something changed in key exchange on container and management from SS side? 
How can I reproduce this situation for debugging? 
Is it permanent problem?

**Comment by Dilshat** [comment]
Nothing changed. I didn't encounter such problem

**Comment by Dilshat** [comment]
Can not reproduce on last dev. Closing
