### ISSUE TITLE
[Environment] Can't create an Environment with any templates besides master.

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/base#649]
For replay this bug you need:

Test case
1) Go to SS and login under any account.
2) Go to 'Environment' and try to create an environment with 'Master' template. (Result: you can create it.)
3) Try to create an Environment with 'Mongo' or 'Casandra' template. 

Result: it fails on preparing templates or cloning containers.
![screenshot from 2016-04-07 18 12 46](https://cloud.githubusercontent.com/assets/11311924/14350746/f1e8b5bc-fcec-11e5-9c9a-99c9d77e6c58.png)

[karaflogs2016-04-07 18_13_12.txt](https://github.com/subutai-io/base/files/208327/karaflogs2016-04-07.18_13_12.txt)

**Comment by Dilshat** [comment]
2016-04-07 12:12:33,255 | INFO  | tp1017977050-598 | CommandProcessor                 | 191 - io.subutai.core.executor.impl - 4.0.0.RC7-SNAPSHOT | Received:
@nk-the-crazy, @kylycht  seems problems on Kurjun side

{
  "type": "EXECUTE_RESPONSE",
  "id": "9AA1C3F1F9F1506E2B4CFFEC81BD097A0561FB11",
  "commandId": "7de457e1-0058-4192-ac53-aa29a5f43e8d",
  "pid": 0,
  "responseNumber": 1,
  "stdOut": "time\u003d\"2016-04-07 12:12:32\" level\u003dinfo msg\u003d\"[Importing apache]\" \ntime\u003d\"2016-04-07 12:12:32\" level\u003dinfo msg\u003d\"[Version: 4.0.0, branch: dev]\" \n\r 0 B / 25 B    0.00%time\u003d\"2016-04-07 12:12:33\" level\u003derror msg\u003d\"[Failed to check MD5 after download. Please check your connection and try again.]\" \n",
  "exitCode": 1
}
