### ISSUE TITLE
[Environment] Can start to create an environment with too long name.

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/base#651]
For replay this improvement you need:

Test case
1) Go to SS and login under any account.
2) Go to Environment page and create an environment with this name (HIPI is an image processing library designed to be used with the Apache Hadoop MapReduce parallel programming framework. HIPI facilitates efficient and high-throughput image processing with MapReduce style parallel programs typically executed on a cluster. It provides a solution for how to store a large collection of images on the Hadoop Distributed File System (HDFS) and make them available for efficient distributed processing. HIPI also provides integration with OpenCV, a popular open-source library that contains many computer vision algorithms.) 

Result: you can observe Error message.

Improvement: should add the symbols limit in Environment name field.

![screenshot from 2016-04-07 18 34 00](https://cloud.githubusercontent.com/assets/11311924/14351273/19181242-fcf0-11e5-8582-e17a2f9bcb5f.png)

**Comment by larenso** [comment]
Seems like database constraint, I guess I can improve log

**Comment by Dilshat** [comment]
Larenso can you just set max limit in text field?
