### ISSUE TITLE
[Plugin] Should add the operation name by default in execute selector.

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/base#665]
For replay this improvement you need: 

Test case
1) Go to SS -> Bazaar page -> Generic plugin and create an operation.
2) Go to Manage page.

Result: you can observe in execute selector empty space.
![upload1](https://cloud.githubusercontent.com/assets/11311924/14379970/fb43e822-fd9e-11e5-9578-191841cdcd5b.png)

Improvement: Add the operation name by default in execute selector.
![upload2](https://cloud.githubusercontent.com/assets/11311924/14379987/131333ea-fd9f-11e5-9013-6bd981dd1b52.png)

**Comment by larcohex** [comment]
fixed
