### ISSUE TITLE
[Plugin] Have an option to choose empty space in selector.

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/base#666]
For replay this bug you need:

Test case
1) Go to SS -> Bazaar page -> Generic plugin and create an operation.
2) Go to Manage page.
3) Click on 'Environment' selector and 'Profile' selector. 

Result: you can observe empty fields. If you choose this fields other become unavailable until you renew the page. (You can reproduce this in all selectors in plugin)

**Comment by larcohex** [comment]
fixed
