### ISSUE TITLE
[Plugin] Can duplicate profile names.

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/base#672]
For replay this bug you need

Test case
1) Go to SS -> Bazaar page -> Generic plugin and create a profile with the name 'test profile'.
2) Again create a profile with the name 'test profile'

Result: you can observe two profiles with the same name.
![screenshot from 2016-04-08 20 29 09](https://cloud.githubusercontent.com/assets/11311924/14387070/6beacac6-fdc9-11e5-82de-3dc5692dd0a5.png)

**Comment by larcohex** [comment]
Fixed
