### ISSUE TITLE
[UI] [Template] Does't appear AppScale template in template list.

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/base#683]
For replay this bug you need:

Test case
1) Go to SS -> Kurjun and add the AppScale template.

Result: you can't observe this template in Kurjub template list. Bit if you go to Environment page you can observe it there.

![screenshot from 2016-04-10 17 02 09](https://cloud.githubusercontent.com/assets/11311924/14409746/fcbd1f3e-ff3d-11e5-93bd-985fa210a1fd.png)

**Comment by larenso** [comment]
![image](https://cloud.githubusercontent.com/assets/4501130/15434920/3d7ef382-1edb-11e6-8bd7-ecc8a9701421.png)
seems like another problem, kurjun related

**Comment by NikolaiB** [comment]
Fixed.
