### ISSUE TITLE
Heartbeat failure after restart on SS console

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/base#688]
Reproduce by:

1. restart your instance
2. login to console
3. send heartbeat to the hub

You will see this error message on the SS console:

![screen shot 2016-04-10 at 4 04 17 pm](https://cloud.githubusercontent.com/assets/10051386/14413680/5c62d3c8-ff4f-11e5-9db4-3ab04bbff0f8.png)

Here's the karaf logs:

[karaflogs2016-04-10 16-06-40.txt](https://github.com/subutai-io/base/files/212060/karaflogs2016-04-10.16-06-40.txt)

**Comment by asanaliev** [comment]
This is more related to Hub. Assigning to @zubaidullo.

**Comment by akarasulu** [comment]
This was fixed with mac installer.
