### ISSUE TITLE
[Plugin] [Cassandra] 'Move nodes' buttons don't work.

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/base#708]
For replay this bug you need:

Test case:
1) Go to SS -> Environment -> create the Cassandra environment.
2) Go to Bazaar page -> Cassandra plugin.
3) Click on 'move nodes' button.

Result: buttons doesn't work.
![1460557171886](https://cloud.githubusercontent.com/assets/11311924/14496648/a4fab0c0-01b5-11e6-8966-623f0f7eac44.jpg)

**Comment by Commander223** [comment]
fixed in plugins project, commit 98e0be1a862970f7a7d7a006153f40d329bf3dd9
