### ISSUE TITLE
[UI] [Create user] Email and password fields already filled out.

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/base#713]
For replay this bug you need:

Test case:
1) Go to SS -> User management -> Create user.

Result: you can observe 'admin' word in email field and 'secret' password in password field.
![1460614753061](https://cloud.githubusercontent.com/assets/11311924/14518757/de8b7e7e-023b-11e6-842a-917eb6ab6e41.jpg)

**Comment by larenso** [comment]
on firefix
