### ISSUE TITLE
[Advanced] [Logs] What if the system will send the logs directly to developers?

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/base#719]
What we have if the user faces with some errors on SS? 
How it looks now: If this happens, the user has to go to Advance -> Logs and send logs.
What if we automate this process? And if the error appears, system gathering errors to reports and send it developers like Microsoft does. Also it will help to predict the user's misbehaviour.

**Comment by Dilshat** [comment]
Now error logs are periodically sent to Hub
