### ISSUE TITLE
Immediately after post install "About" page shows "No RH connected"

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/base#735]
This bug is associated with release version 4.0.0-RC8.

On all platforms, with installers, we've noticed with @tzununbekov that occasionally right after an installation the "System Setting"->"About" page shows no RH version: "No RH connected" is displayed where the RH version should be. The bug occurs with 50% of the installations across platforms so it's not installer dependent. NOTE that in the "Resource Hosts" section the RH is seen with a green status:

![selection_140](https://cloud.githubusercontent.com/assets/10051386/14585112/0b8be0ac-0436-11e6-807f-ba4c95472c47.png)

The behavior suggests some kind of race condition here while installing and preparing the machine on first startup. A restart of the RH VM from the vbox manager fixes the problem which does not reappear after subsequent restarts. The behavior is really elusive, the Karaf file seems to say very little about the problem. I need to be able to dump all the configuration information we have from SS and subos. 

Here are the Karaf logs of 3 machines I installed at the same time with the Windows release installer:

### Win7
- show's bug
- Env creation succeeds (but I think problem corrected itself)
- After some time (~10m) corrects itself
- [karaflogs2016-04-17 08-08-20.txt](https://github.com/subutai-io/base/files/222509/karaflogs2016-04-17.08-08-20.txt)
- restart of vm fixes bug

### Win8
- no bug
- [karaflogs2016-04-17 08-13-15.txt](https://github.com/subutai-io/base/files/222510/karaflogs2016-04-17.08-13-15.txt)
- restart of vm does not show bug

### Win10
- show's bug
- Env creation failed
- Problem did not correct itself
- [karaflogs2016-04-17 08-19-56.txt](https://github.com/subutai-io/base/files/222511/karaflogs2016-04-17.08-19-56.txt)
- restart of vm fixes bug

I'll update for Mac once I get the error again on that platform.

**Comment by Dilshat** [comment]
According to log agent does not send heartbeat. Heartbeats are logged.

**Comment by soffokl** [comment]
@Dilshat Agent sends heartbeat until get HTTP 202 response. After that Agent will send only changes. 
SS also could trigger /heartbeat to force Agent send heartbeat. 
How it's possible that logs does not contains heartbeats?

**Comment by Dilshat** [comment]
We dont receive any heartbeats. May be agent sends them but due to networking problems it does not arrive to SS. As I said SS logs any received heartbeat.

**Comment by soffokl** [comment]
@Dilshat Agent will resend heartbeat if not get 202 status. It couldn't be a network problem. 
We need agent logs to compare time with karaf.logs

**Comment by Dilshat** [comment]
@akarasulu please attach the logs.
@soffokl As I said, SS sometimes can not access agent and fails with Socket timeout exception from time to time even without any load on agent. First we thought that may be agent in loaded with clone tasks. But this happens in idle time too. Seems this is networking between MH container and host RH. So you need to figure out why networking has such hiccups

**Comment by soffokl** [comment]
@Dilshat What timeout do you use? Could you also provide REST endpoint that fail?

**Comment by Dilshat** [comment]
5 sec which is enough. Agent ping URL

**Comment by soffokl** [comment]
@Dilshat What about /heartbeat endpoint? If you do not use it - we can remove it. If you are using it, why can't you get heartbeat with it?

**Comment by Dilshat** [comment]
We use it once we have at least one heartbeat arrived to SS. In the problems described above we don't get the first heartbeat.

**Comment by Dilshat** [comment]
Also removing any functionality will not help with the networking problem I described. Please, lets handle the actual problem
