### ISSUE TITLE
Subutai cleanup should support termination of active command for the vlan being destroyed

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/base#747]
SS might issue env destroy command for the environment being created at the moment.
From SS side all processes are terminated, however some already sent commands like network setup or container clone can be in progress by agent. Once agent receives cleanup command for a vlan, it must terminate all ongoing process for this vlan and then do the cleanup

**Comment by soffokl** [comment]
@Dilshat Cleanup is CLI command, it does not have any knowledge about command in progress. 
Moreover, even agent does not have any command queue. And even if this queue could be exist, we do not have any processing to compare commands, group them by some attribute and terminate before cleanup. 
Adding all this features to agent will take weeks. 
From other side, SS could just wait of finishing this commands, and do not send cleanup until get all responses. It looks much easy.

**Comment by Dilshat** [comment]
We can not wait, we terminate all our process immediately to make environment destroy fast. If we wait it can be very long.

**Comment by soffokl** [comment]
@Dilshat :D You cannot wait, we cannot implement it - dead end. 
We need someone to help us. @tzununbekov @akarasulu can you help us?

**Comment by Dilshat** [comment]
We can figure out some other workaround on SS side later maybe. Lets postpone this then if you can not handle it

**Comment by Dilshat** [comment]
We will add cleanup of containers in case environment destruction was launched during environment creation

**Comment by Dilshat** [comment]
Added timeout 10 sec to wait for agent to complete cloning
