### ISSUE TITLE
User needs feedback on download progress during the "Preparing templates" phase

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/base#764]
Some templates that are huge can make users feel like the "Preparing templates" phase is stuck. We need to prevent this feeling from our users so they see what's happening. Below is a screen shot of the first time creation of an AppScale environment, and it's taking a few minutes for me so .. yeah i get anxious thinking something is messed. It would be nice to see a download progress bar that REALLY tells the user where we are in the download.

![selection_147](https://cloud.githubusercontent.com/assets/10051386/14661446/a3558afe-067b-11e6-92d9-5c573ddf3800.png)

We will need some support from subos on this @tzununbekov.

**Comment by Dilshat** [comment]
We need a percentage in subutai import command output

**Comment by soffokl** [comment]
@Dilshat we have percentage.

**Comment by Dilshat** [comment]
2016-05-03 06:24:54,491 | DEBUG | pool-68-thread-2 | CommandProcessor                 | 194 - io.subutai.core.executor.impl - 4.0.0.RC11-SNAPSHOT | Sending:
{
  "request": {
    "type": "EXECUTE_REQUEST",
    "id": "9AF4E662009093D35E3EC5166133A3FD0940561F",
    "commandId": "0214506e-acbc-406c-aec2-5ca517aca994",
    "workingDirectory": "/",
    "command": "subutai import cassandra",
    "stdOut": "RETURN",
    "stdErr": "RETURN",
    "runAs": "root",
    "timeout": 18000,
    "isDaemon": 0
  }
}
2016-05-03 06:25:13,239 | DEBUG | qtp181091718-532 | CommandProcessor                 | 194 - io.subutai.core.executor.impl - 4.0.0.RC11-SNAPSHOT | Response:
{
  "type": "EXECUTE_RESPONSE",
  "id": "9AF4E662009093D35E3EC5166133A3FD0940561F",
  "commandId": "0214506e-acbc-406c-aec2-5ca517aca994",
  "pid": 0,
  "responseNumber": 1,
  "stdOut": "time\u003d\"2016-05-03 06:24:54\" level\u003dinfo msg\u003d\"[Importing cassandra]\" \ntime\u003d\"2016-05-03 06:24:54\" level\u003dinfo msg\u003d\"[Version: 4.0.0, branch: dev]\" \ntime\u003d\"2016-05-03 06:24:57\" level\u003dinfo msg\u003d\"[Downloading cassandra]\" \n\r 0 B / 23.33 MB    0.00%\r 6.55 MB / 23.33 MB   28.06% 0\r 13.55 MB / 23.33 MB   58.07% 0\r 21.75 MB / 23.33 MB   93.24% 0time\u003d\"2016-05-03 06:25:01\" level\u003dinfo msg\u003d\"[Unpacking template cassandra]\" \n\r 23.33 MB / 23.33 MB  100.00% 0time\u003d\"2016-05-03 06:25:02\" level\u003dinfo msg\u003d\"[Parent template required: openjre7]\" \ntime\u003d\"2016-05-03 06:25:02\" level\u003dinfo msg\u003d\"[Importing openjre7]\" \ntime\u003d\"2016-05-03 06:25:02\" level\u003dinfo msg\u003d\"[Version: 4.0.0, branch: dev]\" \ntime\u003d\"2016-05-03 06:25:03\" level\u003dinfo msg\u003d\"[Downloading openjre7]\" \n"
}
2016-05-03 06:25:23,254 | DEBUG | qtp181091718-536 | CommandProcessor                 | 194 - io.subutai.core.executor.impl - 4.0.0.RC11-SNAPSHOT | Response:
{
  "type": "EXECUTE_RESPONSE",
  "id": "9AF4E662009093D35E3EC5166133A3FD0940561F",
  "commandId": "0214506e-acbc-406c-aec2-5ca517aca994",
  "pid": 0,
  "responseNumber": 2
}
....
2016-05-03 06:25:23,254 | DEBUG | qtp181091718-536 | CommandProcessor                 | 194 - io.subutai.core.executor.impl - 4.0.0.RC11-SNAPSHOT | Response:
{
  "type": "EXECUTE_RESPONSE",
  "id": "9AF4E662009093D35E3EC5166133A3FD0940561F",
  "commandId": "0214506e-acbc-406c-aec2-5ca517aca994",
  "pid": 0,
  "responseNumber": 28
}
...
2016-05-03 06:33:44,997 | DEBUG | qtp181091718-578 | CommandProcessor                 | 194 - io.subutai.core.executor.impl - 4.0.0.RC11-SNAPSHOT | Response:
{
  "type": "EXECUTE_RESPONSE",
  "id": "9AF4E662009093D35E3EC5166133A3FD0940561F",
  "commandId": "0214506e-acbc-406c-aec2-5ca517aca994",
  "pid": 0,
  "responseNumber": 52,
  "stdOut": "\r 0 B / 61.67 MB    0.00%\r 7.69 MB / 61.67 MB   12.47% 1s\r 14.94 MB / 61.67 MB   24.22% 1s\r 23.03 MB / 61.67 MB   37.35% 0\r 31.91 MB / 61.67 MB   51.74% 0\r 39.86 MB / 61.67 MB   64.63% 0\r 47.89 MB / 61.67 MB   77.66% 0\r 55.42 MB / 61.67 MB   89.87% 0\r 61.67 MB / 61.67 MB  100.00% 0time\u003d\"2016-05-03 06:33:38\" level\u003dinfo msg\u003d\"[Unpacking template openjre7]\" \ntime\u003d\"2016-05-03 06:33:38\" level\u003dinfo msg\u003d\"[Installing template openjre7]\" \ntime\u003d\"2016-05-03 06:33:41\" level\u003dinfo msg\u003d\"[Installing template cassandra]\" \n",
  "exitCode": 0
}

**Comment by Dilshat** [comment]
As you see we can not get percent from output unless it is the last chunk

**Comment by soffokl** [comment]
Oh, that is because embedded Kurjun does not send any information to CLI. CLI can't show progress, until start getting data. Then this information should be retrieved from embedded Kurjun.

**Comment by Dilshat** [comment]
Currently not possible to implement this since we removed Kurjun

**Comment by akarasulu** [comment]
OK but let's not close and leave this for later on.

**Comment by soffokl** [comment]
@Dilshat agent shows download progress in output. Can't you parse it? There is not stuck output anymore, because kurjun removed.

**Comment by Dilshat** [comment]
@soffokl 
Can we poll embedded Gorjun REST to get template download percent by template id?
Like if template is dowloaded it will return 100, if not it will return its current downloaded percentage

**Comment by soffokl** [comment]
@Dilshat template download works for each RH. Template can be downloaded on one RH, but have 10% progress on another. I think it should be retrieved from import on each RH, not on embedded gorjun.

**Comment by Dilshat** [comment]
Fixed
