### ISSUE TITLE
Management UI shows old Resource host name

### ISSUE THREAD

**Issue by soffokl** [subutai-io/base#766]
After changing RH hostname, Management server shows old hostname in Resource host tab:
![screenshot from 2016-04-20 15-25-06](https://cloud.githubusercontent.com/assets/8612618/14669813/54e3a1e4-070c-11e6-8a50-fc179f1f1696.png)

But in monitoring drop-down menu everything fine: 
![screenshot from 2016-04-20 15-24-51](https://cloud.githubusercontent.com/assets/8612618/14669841/6fe38dc4-070c-11e6-9d81-c2fbe7374939.png)

**Comment by Dilshat** [comment]
What does peer:hosts show?

**Comment by soffokl** [comment]
I do not have this instance now. You can easily reproduce it by changing RH hostname and restart RH.

**Comment by Dilshat** [comment]
Fixed
