### ISSUE TITLE
[Plugin] [Ceph] Get en error after pushing 'Create' button.

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/base#784]
For replay this bug you need:

Test case
1) Go to SS -> Bazaar and install Ceph plugin.
2) Go to Environment -> click on 'plugin' icon -> choose ceph plugin and create an environment.
3) Go to Ceph plugin -> put 'testClas' in cluster field and click on 'Create' button.

Result: you can observe Error message
![screenshot from 2016-04-22 14 12 36](https://cloud.githubusercontent.com/assets/11311924/14735682/4c5772a6-0894-11e6-8b02-4d0e45edba91.png)

**Comment by larcohex** [comment]
Moved to plugins repo
