### ISSUE TITLE
Control logging level and collect p2p logs from Subutai

### ISSUE THREAD

**Issue by crioto** [subutai-io/base#786]
We want to be able to swtich p2p log level by issuing the following command:
```
p2p set -log <LEVEL>
```
<LEVEL> can be:

- TRACE
- DEBUG
- INFO
- WARNING

Also, we need to be able to collect and see logs from Subutai UI

**Comment by Dilshat** [comment]
Also we need to log p2p logs properly, currently they logged as INFO
which can be checked by journalctl -p INFO ...

**Comment by soffokl** [comment]
Snappy Ubuntu does not allow to configure service unit to set log level. Stdout logs getting single level.
We can use grep for filtering logs with required levels.
