### ISSUE TITLE
Kurjun, add categories

### ISSUE THREAD

**Issue by larenso** [subutai-io/base#787]
We need to have category for each template, so by selecting category we will receive specific templates (i.e. big data). think how this categories will be managed (predefined or user will be able to create new category)

**Comment by Dilshat** [comment]
see https://github.com/subutai-io/base/issues/205

**Comment by Dilshat** [comment]
Will be handled when Kurjun provides API to add tags to artifacts. Currently is blocked

**Comment by Dilshat** [comment]
Done
