### ISSUE TITLE
Concurrent plugin downloads causes one to go into "Restore" state

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/base#797]
@larcohex: if user tries to concurrently download more than one plugin from the bazaar we get weird condition where one of the plugins is in “Restore” state. Also we cannot revert from this state.

![screen shot 2016-04-27 at 9 20 10 am](https://cloud.githubusercontent.com/assets/10051386/14853402/70ca8cea-0c59-11e6-8729-ac0ca159d9b5.png)

**Comment by larcohex** [comment]
Fixed
