### ISSUE TITLE
Allow user to change hostname of CH and RH

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/base#798]
This also needs to be handled in the Hub @larenso! Here's what it looks like right now:

![screen shot 2016-04-27 at 9 31 00 am](https://cloud.githubusercontent.com/assets/10051386/14854146/864c2652-0c5c-11e6-9fe3-cdd9362ee0a1.png)

Users will get annoyed by this ugly hash for the name. Might be ok for mass creation but not for someone wanting to create a long term environment.

![screen shot 2016-04-27 at 9 35 27 am](https://cloud.githubusercontent.com/assets/10051386/14854149/8971328c-0c5c-11e6-894e-3503436dabda.png)

Might consider adding hostname aliases however this will not fix user's ability to see a command link like this where I renamed manually in /etc/hosts and /etc/hostname to cat:

![screen shot 2016-04-27 at 9 45 33 am](https://cloud.githubusercontent.com/assets/10051386/14854214/d3f5e0be-0c5c-11e6-98fe-9bf05d255353.png)

**Comment by Dilshat** [comment]
Done
