### ISSUE TITLE
Add subutai cli command to get p2p version

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/base#817]
We need to be able to get p2p version using subutai cli command

**Comment by soffokl** [comment]
Added here: https://github.com/subutai-io/base/commit/e1c346a1c71efda10bf00ee50898f03a2d91d0bf
```
(amd64)root@rh1462335313:~# subutai management_network p2p -v
p2p Cloud project 4.0.0-RC10. Packet version: 4
```
