### ISSUE TITLE
Key equivalence relations and synchronization to prevent user from having to move keys

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/base#831]
NOTE: @nk-the-crazy, @zubaidullo this will involve you guys as well.

Right now users are creating key pairs on different machines and even on the same machine with different browsers via the browser plugin. There are going to be situations where this could become a serious problem: for example when using different keys with the Hub and a peer. It certainly already presents a usability issue to have to move (export then import) a key pair and doing so is a security risk.

Also right now the Hub and the peer have one key to identify the user. There should probably be more than one key associated, and those keys should be deemed equivalent. The Hub should provide a means for the user to add keys that are considered equivalent. There could be one master key, and the others considered equivalent keys. 

This mechanism we can use is to have the master key sign an relation document stating that another key is considered equivalent to it. The Hub could provide a REST service for accessing these relationships when authenticated to determine key equivalence. This should be a two way relation for security purposes. Meaning one key must sign that it is equivalent to the other and vice versa. So a user with two keys on separate browsers (same machine or different machine) will have to sign such a relationship document. Peers registered with the Hub should push these signed documents to the Hub via authenticated REST calls. This will also require some plugin work. 

I think if authenticated to the Hub and a user is using a key different than the one they have registered with the Hub. Then they can be notified that they have a key different than the one they originally used to register. And they can be asked if they want to begin the process of making them equivalent. The user will then need to use both key pairs to sign each directional relation.

**Comment by Dilshat** [comment]
Current implementation of browser plugin, SS and Hub is based on usage of single key which is reflected throughout the entire chain starting from browser cookie thru SS and till Hub and Kurjun. This would require a complete change of the security core.

**Comment by Dilshat** [comment]
Also, SS already allows to define which key to use in settings. So user can set any key on a given peer, thus having different keys on different peers.
However for this feature to work we need Hub side to handle different keys that are associated with the main key in Hub account. Also this should propagate from Hub to Kurjun because peer uses Kurjun directly.
And if user decides to use multiple keys this should be handled in one place on Hub and get reflected in Kurjun automatically. Otherwise is user is ok and uses default single key option then everything stays as it is.

**Comment by Dilshat** [comment]
For one peer there should be one key at a given moment of time, but this can should be changeable (as is now). On Hub, however, user keys might be numerous. So moving this issue to Hub.
