### ISSUE TITLE
[Login] Should show the new user's login and password.

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/base#932]
For replay this improvement you need:

Test case
1) Go to SS.

Result: after installation process you can observe login page. The user has no idea what login should he use. We have to put it the first time by default or let him register it.
![screenshot_3](https://cloud.githubusercontent.com/assets/11311924/15469397/e2ad381e-210b-11e6-8a9d-9cf3a9f2d249.png)

**Comment by nk-the-crazy** [comment]
Default , UserName and Password should be indicated in Installer , not in Application itself
