### ISSUE TITLE
Put settings to database

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/base#954]
We need to store settings in database because all settings that are present in karaf assembly get overwritten during SS update. Also we need to prune unnecessary settings such as *Enabled ones and review the rest of the settings. Storing settings in db also will remove problems withsychronization between db settings and file settings.

**Comment by nk-the-crazy** [comment]
Removed ,security settings from properties file. Added new DAO managers and Entity classes to system-manager module. Moved part of the configs into Database.
