### ISSUE TITLE
[UI] Some styles are broken on Firefox

### ISSUE THREAD

**Issue by TalasZh** [subutai-io/base#964]
Login to SS via Firefox. create environment, go to environments and in last Actions column first icon is not visible

![screenshot from 2016-05-31 13 50 36](https://cloud.githubusercontent.com/assets/3873442/15672431/81bbd126-2752-11e6-95bd-db7247a1837b.png)

**Comment by larenso** [comment]
![image](https://cloud.githubusercontent.com/assets/4501130/15744006/1df91d84-28eb-11e6-94cc-5a5f141fefae.png)
firefox 46.0.1
looks ok
