### ISSUE TITLE
Use template ids instead of templates names 

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/base#974]
During environment creation we need to pass template ids to participating peers instead if template names.
This will help when there is already a private template with the same name on a remote peer.
Also, it will be used in the future when subutai bindings will be updated to use template id instead of template name.

**Comment by Dilshat** [comment]
This issue depends on https://github.com/subutai-io/subos/issues/486

**Comment by Dilshat** [comment]
@soffokl is **template** name unique in gorjun?

**Comment by soffokl** [comment]
@Dilshat no, templates name is not unique.

**Comment by Dilshat** [comment]
@soffokl then we need to have an additional switch for *subutai clone* command to pass template id instead of template name like:
*subutai clone -id ${TEMPLATE_ID} foo*

**Comment by soffokl** [comment]
@Dilshat sure, we can add this. Could you create issue for that?

**Comment by Dilshat** [comment]
@soffokl sure here it is https://github.com/subutai-io/subos/issues/511

**Comment by Dilshat** [comment]
Inside **io/subutai/core/environment/rest/ui/RestServiceImpl.java** we need to pass template ids or template POJOs (**io/subutai/common/protocol/Template.java**) instead of template names to backend.
It uses Environment manager methods: build, buildAdvanced, modify i modifyAdvanced.
Currently it passes template names inside **Node** and **NodeSchema** class instances.
For now we can add templateId field to these classes and set it from UI side.
