### ISSUE TITLE
Change text on a window after update is complete 

### ISSUE THREAD

**Issue by akylbekesenaliev** [subutai-io/base#976]
![change line](https://cloud.githubusercontent.com/assets/17665678/15737984/c3ead212-28b1-11e6-8e87-b045ffb778fb.png)
After completion of update a window appears saying "Your settings were saved"  this message is confusing and brings no clear info related to the Subutai update, to make it more clearer we need to change the text to "Successfully updated Subutai".

**Comment by eabyshev** [comment]
done
