### ISSUE TITLE
[Peer registration] Can do 'peer registration' by using own ip.

### ISSUE THREAD

**Issue by NikolaiB** [subutai-io/base#977]
For replay this bug you need:

Test case
1) Go to SS -> Peer registration -> do 'peer registration' using your own ip.

Result: you can observe the request, if you click on 'Reject' you can observe 'Error requesting remote peer 'https://158.181.145.77:8443': Can not reject registration request..'

If you click on approve you can observe: 'Peer approve error: Error requesting remote peer 'https://158.181.145.77:8443': Internal system Error 500.'

![subutai social - google chrome](https://cloud.githubusercontent.com/assets/11311924/15746623/250e2c0a-28f9-11e6-8fe9-f169e8d107c1.jpg)
[karaflogs2016-06-02 19-34-59.txt](https://github.com/subutai-io/base/files/295701/karaflogs2016-06-02.19-34-59.txt)

**Comment by nk-the-crazy** [comment]
Issue is fixed , by adding Error Check for PeerIDs (local peer and remote peer)
