### ISSUE TITLE
[acceptance-testing] Cannot create cross-peer env

### ISSUE THREAD

**Issue by p1gmale0n** [subutai-io/base#978]
Test Plan: Subutai Social 
Step: Cross-peer environment

Cross-peer registered.
creating cross-peer env failed:
![2016-06-03_11-57-06](https://cloud.githubusercontent.com/assets/1177402/15770180/54d030b6-2983-11e6-885e-1b4156410efc.png)

version (both hosts):
![2016-06-03_12-02-29](https://cloud.githubusercontent.com/assets/1177402/15770188/625ab756-2983-11e6-93d8-e7ad70b76160.png)

karaf log:
[karaflogs2016-06-03 12-02-15.txt](https://github.com/subutai-io/base/files/296984/karaflogs2016-06-03.12-02-15.txt)

**Comment by Dilshat** [comment]
Tested . Could not reproduce

**Comment by p1gmale0n** [comment]
not rolled on b12603cf37a50edaa917a7621a66123260b1a8f8
