### ISSUE TITLE
[acceptance-testing] [cross-peer] only 1 peer in env creation list 

### ISSUE THREAD

**Issue by p1gmale0n** [subutai-io/base#985]
Created cross-peer connection.
Connection status green on each peer.

on 1st peer have only 1 peer in "Environments - Advanced - Peers" list
on 2nd - have 2 peers

**Comment by asanaliev** [comment]
Can it be related to #967?

**Comment by p1gmale0n** [comment]
@asanaliev ports opened
cross-peer connected

**Comment by p1gmale0n** [comment]
network problem on one peer.
