### ISSUE TITLE
[acceptance-testing] [peer-registration]After Peer registration, peer status is offline

### ISSUE THREAD

**Issue by TalasZh** [subutai-io/base#997]
After I have successfully registered two peers, I still do have OFFLINE status on both peers.

Peer A:
```
Commit ID	         52d4e6d1efe36acb8969a358948ffe200a62991e
Branch	                 origin/dev
Committer name	 Larik
Committer e-mail	 larensolarsuss@gmail.com
Builder name	         Jenkins Admin
Builder e-mail	         jenkins@subut.ai
Build Time	         06.06.2016 @ 07:55:42 EEST
SS version	         4.0.0-RC14-SNAPSHOT
RH version	         4.0.0-RC14-SNAPSHOT
P2P version	         4.0.0-RC14. Packet version: 4
```

Peer B:
```
Commit ID		52d4e6d1efe36acb8969a358948ffe200a62991e
Branch			origin/dev
Committer name	Larik
Committer e-mail	larensolarsuss@gmail.com
Builder name		Jenkins Admin
Builder e-mail		jenkins@subut.ai
Build Time		06.06.2016 @ 07:55:42 EEST
SS version		4.0.0-RC14-SNAPSHOT
RH version		4.0.0-RC14-SNAPSHOT
P2P version		
[karafA.txt](https://github.com/subutai-io/base/files/300539/karafA.txt)
[karafB.txt](https://github.com/subutai-io/base/files/300543/karafB.txt)

4.0.0-RC14. Packet version: 4
```

![screenshot from 2016-06-06 19 41 29](https://cloud.githubusercontent.com/assets/3873442/15823933/af4ea4bc-2c1e-11e6-8553-7f426e3ac945.png)

![screenshot from 2016-06-06 19 42 14](https://cloud.githubusercontent.com/assets/3873442/15824288/4c2d0796-2c20-11e6-9db5-545e34c052e8.png)

[karafA.txt](https://github.com/subutai-io/base/files/300548/karafA.txt)

[karafB.txt](https://github.com/subutai-io/base/files/300549/karafB.txt)

**Comment by Dilshat** [comment]
@TalasZh attach logs

**Comment by Dilshat** [comment]
Probable related to #1000

**Comment by Dilshat** [comment]
Done

**Comment by TalasZh** [comment]
Lived some problems with wan interface on both peers, each time I register them, wan ip changes. But couldn't reproduce second time.

**Comment by Dilshat** [comment]
Wan ip changes will be handles with p2p Ips later
